### ISSUE TITLE
Fehler beim Entziehen von Berechtigungen (V3)

### ISSUE THREAD

**Issue by pettobia** [elan-ev/studip-opencast-plugin#1022]
Wenn ich bei einem Video anderen Studierenden Leserechte erteile und dann den Berechtigungsdialog erneut öffne, kann ich diese Rechte nicht wieder entziehen, da das Symbol ausgegraut ist. Das Symbol bei der eigenen Berechtigung (als Besitzer) ist nicht ausgegraut, hat aber auch keine Wirkung.
(Im Screenshot heißen leider alle Max Mustermann, es sind aber verschiedene Studentenaccounts)

![Screenshot from 2024-10-17 12-18-54](https://github.com/user-attachments/assets/2fc180c0-126e-439f-bd6b-2046d723e0e2)

Bezieht sich auf Version 3

**Comment by tgloeggl** [comment]
Ich hatte versucht das lokal nachzustellen, konnte es aber leider nicht reproduzieren. Gibt es irgendwelche sachdienlichen Meldungen in der Entwicklerkonsole?
