### ISSUE TITLE
"Video weltweit zugreifbar machen" kann nicht rückgängig gemacht werden (V3)

### ISSUE THREAD

**Issue by pettobia** [elan-ev/studip-opencast-plugin#1031]
Wenn ich ein Video über die Funktion "Video weltweit zugreifbar machen" zugänglich mache und dies anschließend über "Video nur berechtigten Personen zugreifbar machen" wieder rückgängig mache, lässt sich über den generierten Link das Video trotzdem weiterhin öffentlich abspielen. 
Außerdem: Klicke ich anschließend nochmal auf den Button "Video weltweit zugreifbar machen" wird im Hintergrund eine Fehlermeldung angezeigt: "Beim übertragen der Änderungen zum Videoserver ist ein Fehler aufgetreten."

**Comment by tgloeggl** [comment]
Das ist leider ein bekanntes Problem, Opencast lässt sich einfach lange Zeit und braucht einen speziellen Workflow, um ACL-Änderungen durchzuführen, siehe https://github.com/opencast/opencast/pull/6033
Meine Hoffnung war, dass sich das Opencast 16 erledigt hätte, dem ist aber leider nicht so. Ich ergänze nun zumindest einen Hinweis, dass Änderungen mehrere Minuten dauern.

Auf der UI ist das schwierig zu handeln, man möchte Nutzende auch nicht zwei minutenlang mit eingefrorener UI sitzen lassen, bis die Änderung durch ist. Man könnte natürlich versuchen den Sachverhalte im Frontend zu visualisieren, aber da fehlte mir bisher die zündende Idee das sinnvoll zu tun.

**Comment by tgloeggl** [comment]
Könnte es sein, dass der Workflow noch nicht durchgelaufen war, als versuche wurde den Link aufzurufen? Oder wurde es tatsächlich permanent falsch im Plugin angezeigt?

**Comment by dennis531** [comment]
> Die Deaktivierung scheint dauerhaft nicht zu funktionieren. Wenn ich die Freigabe erstelle, kann ich den Link nach kurzer Zeit nutzen. Nach der Deaktivierung funktioniert der Link aber auch lange Zeit danach immer noch.

Das Problem tritt bei mir ebenfalls auf. In Opencast wird die Rolle `ROLE_ANONYMOUS` am Video nicht entfernt. Ich bin aktuell dran, das zu fixen.
