### ISSUE TITLE
"Kursinhalte übertragen" funktioniert nicht (V3)

### ISSUE THREAD

**Issue by pettobia** [elan-ev/studip-opencast-plugin#1033]
Wenn ich die Funktion "Kursinhalte übertragen" nutze, wird die Wiedergabeliste zwar in der anderen Veranstaltung angezeigt, die Videos sind jedoch "nicht verfügbar". Bei der Übertragung wurde keine Fehlermeldung angezeigt.

![grafik](https://github.com/user-attachments/assets/57405dc2-619b-4a8a-a51e-9552888af7e9)

**Comment by tgloeggl** [comment]
Konnte ich leider auch noch nicht so nachstellen, gibt es da noch weitere sachdienliche Hinweise?

Auf jeden Fall gab es noch ein Problem beim übertragn mit indirekten Rechten, das habe ich zumindest einmal behoben.

**Comment by dennis531** [comment]
Auf einem frisch installierten System erhalte ich das gleiche Problem, wenn ich eine Playlist kopiere.

[Screencast from 2024-10-30 15-54-17.webm](https://github.com/user-attachments/assets/e0609d22-23e4-4822-8a66-99a809f78cc2)

![image](https://github.com/user-attachments/assets/5be79a55-67d7-4ae5-9c79-497cabff0d90)


![image](https://github.com/user-attachments/assets/4f3af8d5-d8df-4c93-bedf-f4ac661d3f73)

**Comment by tgloeggl** [comment]
Danke für die Hinweise! Ich konnte das Problem nun lokalisieren und beheben.
