### ISSUE TITLE
Fehlermeldung bei Ausführung der Cronjob-Aufgabe "Opencast - Queue" (V3)

### ISSUE THREAD

**Issue by pettobia** [elan-ev/studip-opencast-plugin#1034]
Wenn ich die Cronjob-Aufgabe "Opencast - Queue" manuell starte, erhalte ich folgende Ausgabe (mehrmals mit verschiedenen Videonummern):

```
updating video: 8
<br />
<b>Warning</b>:  implode(): Invalid arguments passed in <b>.../public/plugins_packages/elan-ev/OpenCast/cronjobs/opencast_worker.php</b> on line <b>110</b><br />
<br />
<b>Warning</b>:  implode(): Invalid arguments passed in <b>.../public/plugins_packages/elan-ev/OpenCast/cronjobs/opencast_worker.php</b> on line <b>111</b><br />
<br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>.../public/plugins_packages/elan-ev/OpenCast/lib/Models/Videos.php</b> on line <b>703</b><br />
```

**Comment by tgloeggl** [comment]
Die warnings in Stud.IP sollten generell ausgeschaltet werden, das müsste dann eigentlich auch noch an anderen Stellen Probleme machen.

Ich lasse das Ticket aber offen, da der Anspruch natürlich sein sollte, keine Warnings mehr zu haben.

**Comment by dennis531** [comment]
Mein System mit PHP 8.2.23 wirft sogar einen Fehler an dieser Stelle:

![image](https://github.com/user-attachments/assets/a3005314-0dd1-414d-a1c3-ef8b443e118c)


`[Wed Oct 30 16:11:57.673184 2024] [php:notice] [pid 63308] [client 127.0.0.1:33476] TypeError: implode(): Argument #1 ($array) must be of type array, string given in /home/dennis/studip/public/plugins_packages/elan-ev/OpenCast/cronjobs/opencast_worker.php:110\nStack trace:\n#0 /home/dennis/studip/public/plugins_packages/elan-ev/OpenCast/cronjobs/opencast_worker.php(110): implode()\n#1 /home/dennis/studip/lib/models/CronjobTask.class.php(151): OpencastWorker->execute()\n#2 /home/dennis/studip/app/controllers/admin/cronjobs/tasks.php(180): CronjobTask->engage()\n#3 /home/dennis/studip/vendor/trails/trails.php(558): Admin_Cronjobs_TasksController->execute_action()\n#4 /home/dennis/studip/app/controllers/studip_controller.php(123): Trails_Controller->perform()\n#5 /home/dennis/studip/vendor/trails/trails.php(154): StudipController->perform()\n#6 /home/dennis/studip/vendor/trails/trails.php(121): Trails_Dispatcher->map_uri_to_response()\n#7 /home/dennis/studip/public/dispatch.php(25): Trails_Dispatcher->dispatch()\n#8 {main}, referer: http://localhost/studip/dispatch.php/admin/cronjobs/tasks`

**Comment by tgloeggl** [comment]
fixed in 7d653bbeb1e1615e3e58771fbeccfc4816111e93
