### ISSUE TITLE
Link zum erweiterten Player fehlt

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/studip-opencast-plugin#104]
Alle anderen Links stehen in einer Reihe rechts vom Vorschaubild. Nur der erweiterte Player ist hinter dem Bild versteckt. Der konsistenz halber sollte auch er einen Platz rechts bekommen:

![screenshot from 2018-05-04 13-31-54](https://user-images.githubusercontent.com/1008395/39625857-b797b9a0-4f9f-11e8-8c63-43f8c3e1850a.png)

**Comment by tgloeggl** [comment]
Die anderen Buttons (ReferentIn, Bildschirm, Audio) sind Downloadlinks, der "Erweiterte Player" hingegen verhält sich da ja völlig anders.
Ich finde das so, wie es jetzt ist, konstistent und verständlich gelöst, weshalb ich von dem zusätzlichen Button absehen würde.
