### ISSUE TITLE
Problems with new cookie policy in Firefox 132.0

### ISSUE THREAD

**Issue by pettobia** [elan-ev/studip-opencast-plugin#1045]
**Version**
3.17

**Describe the bug**
After updating to Firefox 132.0, the plugin does not work properly anymore when Strict Mode is activated at the browsers tracking protection settings. 
E.g. the video preview images cannot be loaded
The browser console shows the following error:
`Cookie “JSESSIONID” has been rejected because it is foreign and does not have the “Partitioned“ attribute.`

**To Reproduce**
1. Update Firefox
2. Enable Strict Mode

**Expected behavior**

**Screenshots**

**Comment by tgloeggl** [comment]
Opencast needs to facilitate https://developer.mozilla.org/en-US/docs/Web/Privacy/Privacy_sandbox/Partitioned_cookies
I will check on how it is possible to achieve that.

**Comment by tgloeggl** [comment]
The picures are now proxied like in V2. What still might make problems is uploading videos.

**Comment by tgloeggl** [comment]
Issues about changes needed in opencast reported in #1085
