### ISSUE TITLE
Video not shown in Courseware block

### ISSUE THREAD

**Issue by pettobia** [elan-ev/studip-opencast-plugin#1049]
**Version**
3.17

**Describe the bug**
When adding an Opencast block in Courseware as a lecturer, the video is shown at first. After switching to a student account, it just shows an error message "Es ist ein Verbindungsfehler zum Opencast Server aufgetreten. Das ausgewählte Video kann zurzeit nicht angezeigt werden.". When I re-switch to the lecturer account, it doesn't show the video anymore, too.

**To Reproduce**
1. create Opencast block in courseware
2. switch user

**Expected behavior**

**Screenshots**
![Screenshot from 2024-11-05 11-40-59](https://github.com/user-attachments/assets/a885b5bd-208e-40de-b6a8-9746fe932df1)

**Comment by dennis531** [comment]
It seems that the authentication call (`/lti`) to Opencast is missing.
