### ISSUE TITLE
Downloadqualität auswählen und Größe anzeigen

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/studip-opencast-plugin#106]
Wenn ich beispielsweise die aktuelle Bildschirmaufzeichnung meiner Veranstaltung über Stud.IP herunterlade bekomme ich ein Video mit einer Auflösung von 384x288. Da ist nicht viel Text zu erkennen. Dabei bietet Opencast bessere Qualitäten an. Sinvoll wäre es daher:

- Eine Auswahl der Qualitätsstufen für den Download zu haben
- Eine Anzeige der Dateigröße zu haben
- Eine Anzeige der Auflösung zu haben

**Comment by tgloeggl** [comment]
Welche Route(n) liefern einem denn die verschiedenen Qualitätsstufen?

**Comment by Jano1** [comment]
So würde es mit der Erweiterung aussehen:
![screenshot-2018-5-31 vorlesung opencast-schedule-test - opencast player - oc-dev - stud ip entwicklungsinstallation](https://user-images.githubusercontent.com/6250158/40782759-a4c5dd38-64e0-11e8-9660-366668dddf32.png)

**Comment by lkiesow** [comment]
Das sieht doch schon ganz gut ein. Mögliche Probleme, dir mir damit gerade einfallen:

- Ich vermute das „HD“ kommt von irgendwelchen Tags? Das sind optionale metadaten. Eine verlässlichere Angabe wäre die Auflösung an den Tracks:

        <mp:track ...>
          <mp:mimetype>video/mp4</mp:mimetype>
          ...
          <mp:video id="video-1">
            ...
            <mp:resolution>512x288</mp:resolution>
          </mp:video>
        </mp:track>

- Die Auflöungen von mehreren Tracks muss nicht gleich sein. Bspw. wird im 42/E05 der UOS gerade 1080p Kamerasignal aber nur ~720p Bildschirmsignal aufgezeichnet.
