### ISSUE TITLE
Option to disable "share links"

### ISSUE THREAD

**Issue by pettobia** [elan-ev/studip-opencast-plugin#1067]
**Is your feature request related to a problem? Please describe.**
As suggested in #1036, but so far only realised for "public access", it would be nice to have an option to disable the creation of "share links".

**Describe the solution you'd like**
An option to globally disable the creation of "share links".

**Comment by tgloeggl** [comment]
fixed in 1b32cf32081ac9b02e599fd4379cef404d8cd0c4
