### ISSUE TITLE
Es ist nicht klar welcher Workflow konfiguriert ist

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/studip-opencast-plugin#108]
Nach dem Ändern des Workflows in dem Dialog „Workflow konfigurieren“ ist mir nicht klar welcher Workflow für die bereits geplanten Events genutzt wird. Aktualisiert sich das? Gilt die Einstellung nur für neu geplante Aufzeichnungen?

**Comment by Jano1** [comment]
Hab grad mal den Code nachverfolgt, wird der Workflow geändert bezieht sich das nur auf zukünftige Planungen, bei bereits geplanten Events lässt sich maximal Start- und Endzeit aktuell ändern.

**Comment by tgloeggl** [comment]
Es war ja zweitweise mal drin, dass man den Workflow für jede Palung angeben und sogar im Nachhinein ändern kann. Das haben wir aber nach Absprache bewußt wieder rausgenommen, da das zu viel für den Standardnutzer war - direkte Änderungen des Workflows sind dann aber trotzdem noch in Opencast selbst möglich.
Aber mit dem Hinweistext sollte das jetzt ausreichend klar sein, notfalls kann man die Planung löschen und neu setzen.
