### ISSUE TITLE
Opencast needs to change the cookie settings

### ISSUE THREAD

**Issue by tgloeggl** [elan-ev/studip-opencast-plugin#1085]
Opencast needs to facilitate

    https://developer.mozilla.org/en-US/docs/Web/Privacy/Privacy_sandbox/Partitioned_cookies
    https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#samesitesamesite-value

Without these changes, LTI WILL break soon completly and is already broken in Strict mode in Firefox! Currently only the folling (maybe iconmplete list) of features are affected:
- Video upload 
- Courseware block

These need cookies to work in an iframe and therefore the `Partitioned`-Attribte and `SameSite=None` needs to be set for the cookies from Opencast.

![Screenshot 2024-11-27 at 11-25-17 Screenshot_from_2024-11-26_12-45-30 png (PNG Image 3738 × 1845 pixels) — Scaled (46%)](https://github.com/user-attachments/assets/93587014-9276-4494-8b4a-9b97d0d3294c)

**Comment by KatrinIhler** [comment]
If this is something Opencast needs to do, does it make sense to create an issue there as well?

**Comment by mtneug** [comment]
I preached this for ages about LTI and yes, `Partitioned` will be a solution. However, this is currently not implemented in Safari (as mentioned in the MDN Web Docs). See https://github.com/WebKit/standards-positions/issues/50 for a discussion.

**Comment by tgloeggl** [comment]
I will have to further investigate this issue regarding Safari, but without researching the reasons it a quick test it seems to just work in as of now.
