### ISSUE TITLE
Protokoll wird überschrieben

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/studip-opencast-plugin#111]
OCJobManager.php:111

```php
$target = str_replace(array('http://','https://'),'',$configuration['service_url']);
```

Nicht sicher ob das ein Fehler ist aber das wirkt sehr merkwürdig. Warum wird hier die URL umgeschrieben? Wenn HTTP konfiguriert ist sollte das auch genutzt werden, oder? Das HTTPS verfügbar ist, ist an sich nicht garantiert.

**Comment by Jano1** [comment]
**TL;DR:** Das liegt an 'fsockopen' (die Funktion wird anschließend genutzt um die Verbindung zu testen). 


**Genaue Erklärung:** Das Problem ist, das bei dem zu überprüfenden Hostnamen nur eine gewisse Liste von bereits registrierten Stream-Sockets existiert (abrufbar mit 'stream_get_transports()').

Dort erzeugt der Standard aber nur folgende Ausgabe:
```php 
Array (
  [0] => tcp
  [1] => udp
  [2] => unix
  [3] => udg
)
```

'http' und 'https' sind dort nicht angegeben, das erzwingt eine Eingabe des dazugehörigen Ports in 'getsocket', was wiederum erfordert das der Hostname kein Protokoll mehr enthält.

Deswegen werden 'http://' und 'https://' entfernt.

**Comment by Jano1** [comment]
Ich denke damit kann das hier geschlossen werden :+1:
