### ISSUE TITLE
Stud.IP-Versionskompatibilität

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/studip-opencast-plugin#118]
Es sollte kargestellt werden mit welcher Stud.IP-Version das Plugin läuft. Funktioniert es z.B. mit Stud.IP 4.1?

**Comment by tgloeggl** [comment]
Das Plugin lässt sich so oder so nur bei der korrekten Stud.IP Version installieren.
Ich habe jetzt aber die README ergänzt, um deutlicher zu zeigen, für welche Versionen (Stud.IP und Opencast) das Plugin geeignet ist.

https://github.com/elan-ev/studip-opencast-plugin/commit/1de7029a72c258d0c15e88acd76585b1f7d76252
