### ISSUE TITLE
Support für Opencast 5

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/studip-opencast-plugin#131]
Soweit ich weiß ist das aktuelle Plugin zwar Kompatibel zu Opencast 5, das Release sagt aber sehr klar Opencast 3 & 4 (inpliziert also „nicht 5“). Das sollte eventuell klargestellt werden.

Eine mögliche Lösung wäre das Release durchzunmummerieren oder nach Datum zu benennen und dann zu beschreiben was unterstützt wird um Fehlannahmen zu vermeiden. Z.B.:

> *Release 20180618*
> Unterstützt Stud.IP 3.5 bis 4.2 und sowohl den Scheduler von Opencast 3 als auch den mit Opencast 4 neu eingeführten Scheduler.

Alternativ ginge natürlich auch ein neues Release für opencast 5

**Comment by tgloeggl** [comment]
Wir nehmen OC 5 einfach in die Liste der untersützten Version mit auf. In der README ist ja ziemlich klar dargestellt, was in welcher Version unterstützt wird, das wird einfach angepasst:

Plugin-Version: 1.1.12
Kompatibel zu Stud.IP Versionen: 3.5 - 4.2
Kompatibel zu Opencast Versionen: 3.x, 4.x, 5.x
