### ISSUE TITLE
Button "Mediendownload" ist in der Studierendenansicht effektlos

### ISSUE THREAD

**Issue by tleilax** [elan-ev/studip-opencast-plugin#132]
Klickt man als Studierender in der Sicht "Aufzeichnungen" auf den Button "Mediendownload", tut sich gar nichts.

Als Lehrender oder Root geht alles problemlos.

Bei uns verwendete Version: 1.1.11

**Comment by Jano1** [comment]
Das Problem war, das eine wichtige JavaScript Funktion nur ab der Rechtestufe Tutor geladen wurde.
