### ISSUE TITLE
Play-Symbol bei hellen Videos kaum erkennbar

### ISSUE THREAD

**Issue by tgloeggl** [elan-ev/studip-opencast-plugin#133]
Hat man ein besonders helles Vorschaubild, kann man das  Play-Symbol kaum erkennen, evtl. könnte man es nochmal mit einer anderen Farbe versuchen?

**Comment by lkiesow** [comment]
Das wäre sinnvoll. Hier ein gutes Beispiel für einen Problemfall:

![screenshot from 2018-10-22 23-26-45](https://user-images.githubusercontent.com/1008395/47320952-4864df00-d653-11e8-91b7-d2dcddb52b0a.png)

Wie wäre es mit einer einfachen Umrandung. Beispiel:

![screenshot from 2018-10-22 23-28-56](https://user-images.githubusercontent.com/1008395/47320977-5fa3cc80-d653-11e8-835f-444976295688.png)

bzw. mit dunkelem Hintergrund:

![screenshot from 2018-10-22 23-29-32](https://user-images.githubusercontent.com/1008395/47320993-70ecd900-d653-11e8-989a-a73511505d14.png)

Getestet mit:

```html
<img class="playbutton"
     style="max-height: 60px; padding-bottom: 30px;"
     src="https://data.lkiesow.de/opencast/play.svg">
```

**Comment by tgloeggl** [comment]
Fixed:
https://github.com/elan-ev/studip-opencast-plugin/commit/8431030c23bf40b3f5655ac51667342d97918c36
https://github.com/elan-ev/studip-opencast-plugin/commit/38254c5d1a06e26f98af29bb500df7b4a644f297
https://github.com/elan-ev/studip-opencast-plugin/commit/870595e87c3d560176ec681a065cb3d3c7b61cd3
