### ISSUE TITLE
Mobile Ansicht des Plugins

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/studip-opencast-plugin#137]
In der mobilen Ansicht wird durch die Tabellenstruktur sehr viel Platz vertan und Texte werden sher zusammengedrängt bzw. teilweise sogar abgeschnitten:

<img src="https://user-images.githubusercontent.com/1008395/47439861-6cd4ce80-d7ad-11e8-9935-7f42126ece7c.jpg" width=200px />

Sinnvoller wäre es in der Mobilversion die Texte unter den Vorschauvideos darzustellen.

**Comment by tgloeggl** [comment]
Ist in der aktuellsten master-Version behoben
