### ISSUE TITLE
Schedule Zeit-puffer verringern

### ISSUE THREAD

**Issue by CGreweling** [elan-ev/studip-opencast-plugin#140]
Momentan wird beim Planen einer aufzeichnung immer ein Zeitpuffer von 5Minuten abgezogen. z.B. Planen von 8:00-10:00Uhr resultiert in einer Aufnahme von 8:00-9:55Uhr.
Das ist mit den aktuellen Aufzeichnungsrechnern nicht mehr nötig.
1Minute Puffer würde genügen.

**Comment by Jano1** [comment]
Unter dem Punk 'Opencast-Einstellungen' lässt sich ein Zeitpuffer einstellen (in Sekunden) für jede Konfiguration.

**Comment by Jano1** [comment]
Sieht dann so aus:
![screenshot_2018-11-12 opencast administration - oc-dev - stud ip entwicklungsinstallation](https://user-images.githubusercontent.com/6250158/48350839-a69c4500-e688-11e8-93c0-a833d9bea39e.png)
