### ISSUE TITLE
Liste der Endpunkte wird nie gesäubert

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/studip-opencast-plugin#141]
Selbst wenn ein neuer Opencast-Server eingetragen wird oder sich dessen Endpunkte ändern säubert das Plugin nie seine gecachten Endpunkte sondern függt lediglich ggf neue hinzu.

**Comment by lkiesow** [comment]
Hier werden die jeweils neuen Endpunkte gesetzt:

https://github.com/elan-ev/studip-opencast-plugin/blob/f7b4c1fc26e7e1bce3c681e1fc77d6d882bece22/controllers/admin.php#L174-L176

Als SQL-Code wird also nur ausgeführt:

```sql
REPLACE INTO `oc_endpoints` (config_id, service_url, service_type) VALUES (?,?,?);
REPLACE INTO `oc_endpoints` (config_id, service_url, service_type) VALUES (?,?,?);
…

Der generierte SQL-Code sollte stattdessen irgendetwas in diese Richtung sein:


```sql
START TRANSACTION;
DELETE FROM `oc_endpoints`;
REPLACE INTO `oc_endpoints` (config_id, service_url, service_type) VALUES (?,?,?);
REPLACE INTO `oc_endpoints` (config_id, service_url, service_type) VALUES (?,?,?);
…
COMMIT;
```

Damit würden alle Endpunkte auf einmal ersetzt sobald neue geladen werden.

**Comment by Jano1** [comment]
Theoretisch richtig, aber ein paar Zeilen vorher wird `OCRestClient::clearConfig($config_id);` aufgerufen, das macht dann das hier: 
`    function clearConfig($config_id)
    {
        $stmt = DBManager::get()->prepare("DELETE FROM `oc_config` WHERE config_id = ?;");
        $stmt->execute([$config_id]);
        $stmt = DBManager::get()->prepare("DELETE FROM `oc_endpoints` WHERE config_id = ?;");

        return $stmt->execute([$config_id]);
    }` 
Dort sollten eigentlich alle alten Endpoints mit entfernt werden soweit ich das sehe?

**Comment by Jano1** [comment]
Ich bennene die Methode um von `clearConfig($config_id)` zu `clearConfigAndAssociatedEndpoints($config_id)`!
