### ISSUE TITLE
Geplante Zeiten weichen in Opencast ab

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/studip-opencast-plugin#142]
Werden Aufzeichnungen über das Plug-in geplant so werden sie automatisch um 5min verkührzt. Das scheint ein Workaround für probleme mit älteren Capture-Agents gewesen zu sein und heute in den meisten Fällen wohl nicht nötig. Im Optimalfall sollte das verhalten konfigurierbar sein. Ansonsten sollte es entweder klar dokumentiert sein oder es sollten die tatdächlichen zeiten übernommen werden.

**Comment by Jano1** [comment]
duplicate of #140
