### ISSUE TITLE
Editor aus dem Plugin heraus aufrufen

### ISSUE THREAD

**Issue by CGreweling** [elan-ev/studip-opencast-plugin#143]
Es wäre schön für gewisse Serien aus dem Plugin heraus auf den Opencast-Videoeditor zu greifen zu können.
Sobald das Event zum schneiden fertig ist, sollte ein link zum Editor aufrufbar sein.

**Comment by Jano1** [comment]
Scheint nicht allzu kompliziert zu sein, der Link ist 'https://<SERVER>/admin-ng/index.html#/events/events/<UUID>/tools/editor', wobei die UUID die id der Episode zu sein scheint?

**Comment by tgloeggl** [comment]
Leere Seite nach dem erfolgreichen schneiden - Hinweis vorher in Stud.IP anzeigen.

**Comment by luniki** [comment]
Reicht es, den im Issue angegebenen Link anzubieten? Oder muss das in irgendeiner Weise mit LTI verknüpft sein?

**Comment by CGreweling** [comment]
@CGreweling rausfinden wie man sieht Obst zum schneiden bereit ist.
