### ISSUE TITLE
Stud.IP legt passende Rolle in Opencast an

### ISSUE THREAD

**Issue by tgloeggl** [elan-ev/studip-opencast-plugin#153]
Stud.IP legt Rollen für die verschiedenen Rechtestufen einer Veranstaltung in Opencast an und ordnet diese der entsprechenden Serie hinzu.

Man braucht vermutlich typischerweise 2 Rollen:
* Dozent: Darf auch Videos sehen, welche er für seine Studierenden unsichtbar geschaltet hat.
* Student: Darf nur sichtbare Videos sehen.

**Comment by Jano1** [comment]
![screenshot_2019-03-01 opencast](https://user-images.githubusercontent.com/6250158/53646127-b8572780-3c3a-11e9-931c-54a81d46011c.png)
Rollen werden passend angelegt.
