### ISSUE TITLE
LTI

### ISSUE THREAD

**Issue by tgloeggl** [elan-ev/studip-opencast-plugin#154]
Stud.IP authentifiziert sich ab sofort via LTI bei Opencast.

**Comment by Jano1** [comment]
Es wird! 
![screenshot_2019-02-28 vorlesung opencast-schedule-test - opencast player - oc-dev - stud ip entwicklungsinstallation](https://user-images.githubusercontent.com/6250158/53574009-00a91380-3b6f-11e9-9a2f-aba040009704.png)

**Comment by Jano1** [comment]
![screenshot_2019-03-01 vorlesung opencast-schedule-test - opencast player - oc-dev - stud ip entwicklungsinstallation](https://user-images.githubusercontent.com/6250158/53648131-7086cf00-3c3f-11e9-8072-aa08d9115f13.png)

So sieht es aktuell aus :)
