### ISSUE TITLE
Emebed Player Link ändern

### ISSUE THREAD

**Issue by CGreweling** [elan-ev/studip-opencast-plugin#157]
Der aktuell generierte Embed Link funktioniert nicht.

$this->video_url = $this->search_client->getBaseURL() . "/engage/ui/embed.html?id=";

So müsste das aussehen.
/engage/theodul/ui/core.html?mode=embed?id=

Oder für den Paella Player:
/paella/ui/embed.html?id=

**Comment by CGreweling** [comment]
zu finden in 
controllers/course.php:184:
controllers/course.php:621:
OpenCast.class.php:273:

**Comment by tgloeggl** [comment]
Fixed through pull-request https://github.com/elan-ev/studip-opencast-plugin/pull/159
