### ISSUE TITLE
icon in plugin.manifest aufnehmen

### ISSUE THREAD

**Issue by JFD23** [elan-ev/studip-opencast-plugin#158]
icon=images/oc.png

Dann hätte Opencast in der Tool-Auswahl auch ein Icon wie alle anderen Plugins...

Am Besten wäre eine svg Variante des icons.
(Das Umwandeln in SVG könnte mein StuMi machen.)

**Comment by tgloeggl** [comment]
Fixed through pull-request https://github.com/elan-ev/studip-opencast-plugin/pull/159
