### ISSUE TITLE
Fehlerhafte Planungen löschen

### ISSUE THREAD

**Issue by tgloeggl** [elan-ev/studip-opencast-plugin#165]
Gibt es geplante Aufzeichnungen, wo der Raum nicht mehr mit dem geplanten Raum übereinstimmt, so sollen diesen Planungen gelöscht und der Dozent via interner Nachricht informiert werden.
Angestoßen werden soll das über den stündlichen Cronjob.

**Comment by tgloeggl** [comment]
Es gibt bereits einen Cronjob dafür, es muss nur getestet werden, ob er wie gewünscht funktioniert.

**Comment by nimuelle** [comment]
Funktioniert leider nicht, trotz Raumänderung, wird die geplante Aufzeichnung aufm Streaming-Server nicht gelöscht.
