### ISSUE TITLE
Datenschutztext für Dozierende

### ISSUE THREAD

**Issue by tgloeggl** [elan-ev/studip-opencast-plugin#167]
* In den Opencast-Einstellungen WYSIWG-Text hinterlegen + I18N
* Dozierende müssen Text zustimmen, wenn sie planen wollen - keine Anzeige der Daten bevor zugestimmt wurde
* In der Sidebar Möglichkeit, das Einverständnis zurückzuziehen mit Stornierung aller Termine

**Comment by nimuelle** [comment]
Der Datenschutztext ist sehr lang und muss formatierbar sein, der wysywig wäre hier gut.
