### ISSUE TITLE
Encoding in Media Upload Broken

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/studip-opencast-plugin#169]
Special characters in the media upload dialog are broken. This picture was taken from Chrome:

![Screenshot from 2019-07-10 20-13-47](https://user-images.githubusercontent.com/1008395/60994444-d2bfb100-a350-11e9-9226-86f2d236dccb.png)

The problem can be confirmed using cURL. The page contains `<meta charset="utf-8">` but if you actually decode e.g. the `§60 UrhG` using UTF-8, the characters are mangled. Manually switching to latin1 fixes the encoding but that's… no solution ;-)

**Comment by tgloeggl** [comment]
fixed in 9aa143f6482d271528a4b9c0a6616235cc38cf44
