### ISSUE TITLE
Layout broken on less wide screens

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/studip-opencast-plugin#170]
If you resize Stud.IP and give it less horizontal space (e.g. by opening the developer tools) the layout breaks and the play arrow sticks out of the preview images.

![Screenshot from 2019-07-10 20-31-27](https://user-images.githubusercontent.com/1008395/60995164-43b39880-a352-11e9-9418-60ebb27ed469.png)

**Comment by tgloeggl** [comment]
fixed in 134b3c6586d59036982829da377e08f738ad30ef
