### ISSUE TITLE
Verknüpfen mehrerer Serien zu einer Veranstaltung

### ISSUE THREAD

**Issue by JFD23** [elan-ev/studip-opencast-plugin#174]
Um Serien inhaltsorientiert gestalten und Zielgruppen gerichtet verknüpfen zu können, wäre es sinnvoll, mehrere Serien einer Veranstaltung zuordnen zu können. Dies würde auch den Mehrwert bringen, dass Serien nicht dupliziert werden müssen auf OC, um eine Teilmenge von Videos einer Serie in einer anderen Serie anzubieten. 
Die Darstellung könnte ähnlich wie in der Courseware mit Kapiteln in der Sidebar sein.

**Comment by JFD23** [comment]
ist ein enhancement für künftige releases. ich habe aber das Label nicht hinzufügen können.

**Comment by tgloeggl** [comment]
Es können monentan schon mehrere Serien für einen Kurs verknüpft werden, das geht bisher aber nur via händischem Eingriff.
Deshalb und aufgrund weiterer Probleme ist es sinnvoll, dafür eine komfortable GUI zu haben. Die wird dann bei nächster Gelegenheit eingebaut.

**Comment by tgloeggl** [comment]
Das wird leider nicht funktionieren. Wir haben entschieden, dass zukünftig eine Serie zu maximal einem Kurs hinzugefügt werden kann und jeder Kurs auch nur maximal eine Serie haben kann. Alles andere ist momentan nicht sinnvoll umsetzbar.

**Comment by JFD23** [comment]
Ok. Danke dennoch fürs Überlegen.

**Comment by tgloeggl** [comment]
Ich erinnere mich an deine Anforderung, dass man eine Episode in mehreren Veranstaltungen haben möchte. Der Ablauf dafür wäre jetzt wie folgt: 
* Jede Veranstaltung hat eine Serie
* Episode aus einer Serie soll in eine andere Serie integriert werden
* Dies geschieht durch duplizieren der Episode und zuordnen zu der neuen Serie
* Nach Aussagen von Opencast-Experten führt dies NICHT zu einem erhöhten Speicherbedarf, da im Dateisystem dafür Hardlinks verwendet werden.

Damit solltest du dann eigentlich auch zum gewünschten Ergebnis kommen können, oder täusche ich mich da?

**Comment by JFD23** [comment]
ja, das wäre ok. 
Ich habe auch schon über die Ausblenden Funktion nachgedacht. Also angenommen 20 Videos in einer Serie. 12 sind für Veranstaltung a) und andere 15 (davon gleiche und andere Videos) sind für Veranstaltung b). Dann müsste man aber eine Serie mehreren Veranstaltungen zu ordnen könne. Aber das wollt ihr verhindern?
Wieso das?

**Comment by tgloeggl** [comment]
Das Problem sind die Berechtigungen bzw. Sichtbarkeit der Videos. Die Sichtbarkeit der Videos wird jetzt im Prinzip in Opencast gespeichert. Es gibt folgende Sichtbarkeiten:
* Nur für Lehrende/n
* Nur für VA-Teilnehmer
* Öffentlich

Hängt man nun eine Serie in mehrere Veranstaltungen ein, so hat man ein konzeptionelles Problem. Veranstaltung A schaltet Video 1 sichtbar für Teilnehmde. Damit ist es in Veranstaltung B ebenfalls sichtbar.

Technisch ist es (seit der Änderung die ich hier gleich verlinke :) ) nun sauber möglich, eine Serie in mehreren Veranstaltungen einzuhängen, allerdings eben mit dem oben genannten Effekt. Um unterschiedliche Sichtbarkeiten derselben Videos in verschiedenen Veranstaltungen zu haben, müssen diese separaten Serien zugeordnet sein.

Das Verknüpfen von mehreren Serien zu einer Veranstaltung würde den obigen Fall sehr viel häufiger werden lassen, was im Endeffekt nur Verwirrung stiften wird. Mittels dem Konzept eine Serie für eine VA umgeht man dieses Problem.
