### ISSUE TITLE
Schalter für Mediendownload

### ISSUE THREAD

**Issue by nimuelle** [elan-ev/studip-opencast-plugin#184]
Der Mediendownload soll für Studierende einer Veranstaltung optional vom Lehrenden einstellbar sein. Default sollte AUS sein. Der Lehrende soll entscheiden dürfen, ob man das möchte.

**Comment by luniki** [comment]
Im Gespräch mit @nimuelle haben wir herausgefunden, dass wir keine VA-spezifische Einstellung benötigen. Eine systemweite Einstellung genügt.

Ist der Download systemweit abgeschaltet, sollen (nur) Dozenten dennoch herunterladen können.

**Comment by luniki** [comment]
Reicht das globale Abschalten überhaupt? @nimuelle scheint das zu genügen. @rrolf ist das ausreichend?

**Comment by rrolf** [comment]
Ich würde es lieber haben, wenn Lehrende das abweichend vom Default für ihre LV selber entscheiden können. 
Bisher haben verhältnismäßig wenige das abschalten verlangt - dafür aber lautstark. 

Und besonders in der erwarteten Netzwerklast durch Corona, wäre es mir lieb wenn viele Lernende auch bei bedarf runterladen könnten.

**Comment by luniki** [comment]
Ok.

Dann sollten wir das hier genau spezifizieren.

- Es gibt einen globalen Schalter. Er kann die Werte [Download erlaubt, nicht erlaubt] einnehmen.
- Es gibt einen lokalen, veranstaltungsspezifischen Schalter.

**Fragen:**

- Darf sich dieser lokale Schalter über den globalen hinwegsetzen?
- Falls ja, hat der lokale Schalter drei Werte: [globalen Wert übernehmen, erlauben, nicht erlauben]. Ist das richtig?

**Comment by luniki** [comment]
Letztlich ist nur wichtig zu wissen, was ein "Download verboten" auf Systemebene bedeutet:

- Das ist ein globales Veto. Lehrende können dann Download nicht erlauben.
- Das ist eine globale Default-Einstellung. Solange Lehrende keine andersweitigen Einstellungen vornehmen, gilt die globale Einstellung. Lehrende können aber gezielt für ihre VA erlauben.

Welches Szenario darf es sein @rrolf @nimuelle ?

**Comment by nimuelle** [comment]
dann nehme ich den zweiten Spiegelstrich....

**Comment by CGreweling** [comment]
@luniki Oldenburg und UOS haben eine unterschiedliche Standard Vorgabe. 

- Oldenburg Standard -> Download ausgeschaltet
  -  Lehrende dürfen runterladen und lokal download ggf. erlauben.

- Osnabrück Standard -> Download eingeschaltet
  - Lehrende dürfen lokal download ggf. verbieten

Ich hoffe das schafft etwas Klarheit?
