### ISSUE TITLE
Auswahl des Republish Workflow

### ISSUE THREAD

**Issue by Rillke** [elan-ev/studip-opencast-plugin#196]
Hallo, die MLU Halle-Wittenberg hat ihre Workflows angepasst. Die angepassten (und gut getesteten) Workflows haben neue IDs erhalten, um Verwechslungen zu vermeiden.

Das Plugin [hardcodiert](https://github.com/elan-ev/studip-opencast-plugin/blob/cd856edb6939f88cb369d15d98dec6682e5a3b68/classes/OCRestClient/ApiWorkflowsClient.php#L33) den Republish Workflow.

Könnte es eine Auswahl in den Einstellungen ähnlich dem Standardworkflow in den Opencast Ressourcen geben, der die Auswahl des Republish Workflows erlaubt?

![image](https://user-images.githubusercontent.com/2311611/75995145-4922ac00-5efc-11ea-85ea-3011cc5480d6.png)

**Comment by tgloeggl** [comment]
Moin! Ja, das sollte prinzipiell machbar sein, Ich setz es auf die Liste für die Version 2 des Plugins, an 
der ich gerade arbeite.

**Comment by tgloeggl** [comment]
So, ich habe mir das gerade angesehen und muss da nochmal einen Schritt zurück machen: Warum möchte man diesen Workflow anpassen können? 

Der von dir verlinkte Workflow wird lediglich dazu genutzt, um ein Update der Metadaten und ACLs durchzuführen, um die Sichtbarkeitseinstellungen vorzunehmen.

Was ist genau das Problem, welches du mit dieser Einstellung lösen möchtest?

**Comment by Rillke** [comment]
> Der von dir verlinkte Workflow wird lediglich dazu genutzt, um ein Update der Metadaten und 
> ACLs durchzuführen, um die Sichtbarkeitseinstellungen vorzunehmen.

Das ist beim default Workflow so. Anpassungen wurde u.a. am OAI-PMH publishing vorgenommen; perspektivisch soll der WF beim Abschluss ggf. alte Snapshots löschen, um Duplikate beim Backup mit einem bekannten IBM-Produkt zu umgehen. Da es für uns signifikante Unterschiede sind, bekommt der Workflow eine eigene ID.

> Was ist genau das Problem, welches du mit dieser Einstellung lösen möchtest?

Ich möchte, dass die Übernahme der Zugriffsrechte (ACLs) nach Engange funktioniert.

Vermutlich könntet ihr für dieses Plugin einfach dokumentieren, dass der Republish-Metadata-Workflow die ID `republish-metadata` haben muss und was er genau erfüllen muss, damit das Plugin funktioniert. Dann würde ich vermutlich einen auf der Opencast GUI versteckten WF mit ID=`republish-metadata` anlegen, der unseren angepassten `republish-metadata-llz` einbindet.

Berechtigte Frage ist: Benötigt dieses Plugin ggf. einen angepassten Republish Workflow (der anders ist als bei Benutzung des Opencast Interface). Kann ich noch nicht sagen. Sicher kein Feature, welches wir bald benötigen, da kommen vorher andere. Also: Dokumentation reicht aus meiner Sicht vorerst aus.

**Comment by tgloeggl** [comment]
Moved this to the 2.0 milestone, since it depends on improvements made there

**Comment by tgloeggl** [comment]
Man im neuen Plugin nun die Workflows entsprechend zuweisen, so ist man nicht auf Standardnamen angewiesen.
