### ISSUE TITLE
Wenn man aus Versehen außerhalb des Datei-Hochlade-Fensters klickt schließt sich das Fenster und alle Eingaben sind verloren

### ISSUE THREAD

**Issue by Rillke** [elan-ev/studip-opencast-plugin#198]
Wenn man aus Versehen außerhalb des Datei-Hochlade-Fensters klickt schließt sich das modale Fenster und alle Eingaben sind verloren.

Erwartetes Verhalten:
Nur beim Klick auf "Abbrechen" oder Esc wird das Fenster geschlossen.

![image](https://user-images.githubusercontent.com/2311611/76108237-85c4d500-5fda-11ea-8fff-6de0425d74fc.png)

**Comment by tgloeggl** [comment]
Das ist Stud.IP Standard, da hat das Plugin in seiner jetzigen Form keinen Einfluss darauf.
Wird aber in der Version 2.x des Plugins berücksichtigt.

**Comment by luniki** [comment]
Ist das ein Duplikat von #221 ?

**Comment by Rillke** [comment]
Hängt von der Lösung des Problems ab.
