### ISSUE TITLE
Medien hochladen funktioniert nicht

### ISSUE THREAD

**Issue by Rillke** [elan-ev/studip-opencast-plugin#199]
Beim Klicken auf "Medien hochladen" sehe ich im Netzwerkinspektor einen POST-Request:

![image](https://user-images.githubusercontent.com/2311611/76108935-c7a24b00-5fdb-11ea-892d-c7352b57a3d5.png)

POST https://staging.studip.uni-halle.de/plugins.php/opencast/upload/upload_file/?cid=47994b76c309fd2885800fb6e6cd3b9d&uuid=7ed8e3d201819606da043e5ae7db961f
```
-----------------------------9819284361650019881690093150
Content-Disposition: form-data; name="series_id"
-----------------------------9819284361650019881690093150
Content-Disposition: form-data; name="title"
Bunny3
-----------------------------9819284361650019881690093150
Content-Disposition: form-data; name="creator"
no name
-----------------------------9819284361650019881690093150
Content-Disposition: form-data; name="recordDate"
2020-03-06
-----------------------------9819284361650019881690093150
Content-Disposition: form-data; name="startTime"
10:00
-----------------------------9819284361650019881690093150
Content-Disposition: form-data; name="contributor"
no name
-----------------------------9819284361650019881690093150
Content-Disposition: form-data; name="subject"
Medienupload, Stud.IP
-----------------------------9819284361650019881690093150
Content-Disposition: form-data; name="language"
de
-----------------------------9819284361650019881690093150
Content-Disposition: form-data; name="description"
test
-----------------------------9819284361650019881690093150
Content-Disposition: form-data; name="video"; filename="Big_Buck_Bunny_first_23_seconds_1080p.ogv"
Content-Type: video/ogg
OggS....
```

Der `series_id` Parameter ist leer. Die Serie wurde aber von StudIP in Opencast angelegt.

Der StudIP Server antwortet mit 302 (Found) location: /plugins.php/opencast/course/index?cid=47994b76c309fd2885800fb6e6cd3b9d

Diese Seite enthält keine Hinweise auf einen erfolgreichen Upload.

Und das Video kommt nie in Opencast an.

Das hat, wenn ich mich recht erinnere in früheren Versionen dieses Plugins funktioniert.

**Comment by Rillke** [comment]
Ich habe mal spaßeshalber den Code von https://raw.githubusercontent.com/blueimp/jQuery-File-Upload/master/js/jquery.fileupload.js in der JavaScript Konsole ausgeführt. Damit wurde die Datei in Chunks hochgeladen und ich erhielt folgende Meldung:
![image](https://user-images.githubusercontent.com/2311611/76145657-c4669800-608b-11ea-9cd0-0ce69bda0a9e.png)

In Opencast kam das Video jedoch nie als Episode an.

**Comment by tgloeggl** [comment]
Das hängt wahrscheinlich mit #197 zusammen und wird behoben sein, wenn das dortige Problem behoben ist.

**Comment by Rillke** [comment]
@tgloeggl Habe den WYSIWYG editor eingeschaltet. Episode/Video kommt immer noch nicht in Opencast an. Welche Logs/ Verzeichnisse sollte ich mir ansehen?

**Comment by Rillke** [comment]
@tgloeggl Danke für Version 1.2.103. Damit muss ich den WYSIWYG editor nicht mehr eineschalten, um den Uploade-Forschrittsbalken zu erhalten. Dennoch sehe ich als Admin keine neuen Events in der Opencast UI nach dem Hochladen in StudIP. Schreibt das Plugin Logs oder hast du Ideen, wie ich das Problem debuggen könnte?

**Comment by Rillke** [comment]
Aha, it was an issue with file permissions:

```
# ls -lha /tmp/studip41/opencast
total 8,0K
drwxr-xr-x 2 root     root     4,0K Mär  9 17:00 .
drwxr-xr-x 5 www-data www-data 4,0K Mär  9 18:50 ..

# chown -R www-data:www-data /tmp/studip41/opencast
```
