### ISSUE TITLE
Cross-Origin request to the Opencast host failing

### ISSUE THREAD

**Issue by Rillke** [elan-ev/studip-opencast-plugin#204]
When visiting the Opencast tab of a seminar page, I see the following request in the browser:

![Screenshot from 2020-03-07 15-39-26](https://user-images.githubusercontent.com/2311611/76145538-78ffba00-608a-11ea-9984-e2aea1193490.png)

as well as

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://staging.opencast.XXXXXXXXX:8443/lti. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://staging.opencast.XXXXXXXXX:8443/lti. (Reason: CORS request did not succeed).
```

Is this intended behaviour? What's this request's purpose? If it is LTI login, can't that be performed when a user actually clicks a video instead of causing error messages in the browser's JavaScript console?

**Comment by Rillke** [comment]
BTW, the response is only a 302 redirect to https://staging.opencast.XXXXXXXX:8443/ltitools

**Comment by Rillke** [comment]
The following logs were generated by the Opencast presentation node:
```
presentation_1       | 2020-03-07T15:52:34,046 | INFO  | (LtiLaunchAuthenticationHandler:252) - Returning user with 1 authorities
presentation_1       | 2020-03-07T15:52:34,047 | WARN  | (LtiServlet:221) - The 'custom_tool' parameter was invalid: 'null'. Reverting to default: '/ltitools'
```

**Comment by tgloeggl** [comment]
This request is the LTI login. This is necessary to load the preview images for the episodes, therefore it is not an option to do the LTI authentication after the user clicks a video.
BTW, if the Opencast system resides on a different domain than Stud.IP does, you need to configure your Opencasts NGINX accordingly to allow CORS.

I will add this to the installation notes.

**Comment by Rillke** [comment]
> you need to configure your Opencasts NGINX accordingly to allow CORS.

There is no nginx (yet) so I have to configure Jetty which comes bundled with Opencast.

**Comment by tgloeggl** [comment]
> > you need to configure your Opencasts NGINX accordingly to allow CORS.
> 
> There is no nginx (yet) so I have to configure Jetty which comes bundled with Opencast.

Alright, but i would recommend using an Nginx.
