### ISSUE TITLE
Is-writable check on /tmp/.../opencast

### ISSUE THREAD

**Issue by Rillke** [elan-ev/studip-opencast-plugin#207]
Would it make sense to you to add a check on `/tmp/.../opencast` to see if that directory is writable and provide the result to Stud.IP root users?

**Comment by tgloeggl** [comment]
Sure, why not.

**Comment by Rillke** [comment]
Some background information: We had a cron job that was misconfigured to run as root and it changed the directory's owner when executing some Stud.IP opencast plugin cron jobs.

**Comment by luniki** [comment]
Ist das noch erforderlich? Ich nehme an, dass es sich um Chunk-Uploads handelt?

**Comment by Rillke** [comment]
@luniki Wenn das Verzeichnis nicht schreibbar ist, kommt es zu einem Fehler. Das Plugin versucht dort folgende Daten abzulegen:
```
root@container:/tmp/studip41/opencast/0be6455246cf326e7bf76bcb5ca25100# ls
job_data.json  local_chunk_info.json  opencast_info.json  upload_chunk_info.json
```

**Comment by luniki** [comment]
Ok, das muss Till wissen.

**Comment by Rillke** [comment]
Mhhm, wenn der LTI-Upload gegen unseren Ingest-Server funktioniert, bin ich happy und brauche das hier nicht mehr. Wir werden schon irgendwann auf Opencast 8.3+ aktualisieren.

**Comment by tgloeggl** [comment]
Da der chunck upload rausgeflogen ist, hat das nun keine Relevanz mehr. :)
