### ISSUE TITLE
[Cronjobs] Fehlerhafte Ausführung: Opencast - "Reupload"

### ISSUE THREAD

**Issue by Rillke** [elan-ev/studip-opencast-plugin#208]
Nach dem frisch installierten Opencast Plugin und einem manuellen Medien-Upload ist bei uns folgender Fehler aufgetreten. Dabei ist ein Medien-Upload fehlgeschlagen und ein anderer war erfolgreich:

Der Cronjob "Opencast - "Reupload"" wurde deaktiviert, da bei der Ausführung ein Fehler aufgetreten ist.

Typ: PDOException
Nachricht: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'workflow_id' cannot be null
Code: 23000
Stack trace:
```
#$ lib/classes/StudipPDO.class.php(521)
#0 lib/classes/StudipPDO.class.php(521): PDOStatement->execute()
#1 public/plugins_packages/elan-ev/OpenCast/models/OCModel.php(509): StudipPDOStatement->execute(Array)
#2 public/plugins_packages/elan-ev/OpenCast/classes/OCJob.php(377): OCModel::setWorkflowIDforCourse(NULL, '07dd9e1c81af912...', 'cli', 1584021603)
#3 public/plugins_packages/elan-ev/OpenCast/classes/OCJob.php(417): OCJob->trigger_ingest()
#4 public/plugins_packages/elan-ev/OpenCast/classes/OCJobManager.php(214): OCJob->try_upload_to_opencast()
#5 public/plugins_packages/elan-ev/OpenCast/cronjobs/try_reupload_failed_jobs.php(24): OCJobManager::try_reupload_old_jobs()
#6 lib/models/CronjobTask.class.php(113): TryReuploadFailedJobs->execute('1', Array)
#7 lib/models/CronjobSchedule.class.php(212): CronjobTask->engage('1', Array)
#8 lib/classes/CronjobScheduler.class.php(330): CronjobSchedule->execute()
#9 cli/cronjob-worker.php(34): CronjobScheduler->run()
#10 {main}
```

**Comment by luniki** [comment]
Durch das Verwenden des LTI-Uploads (siehe #233) sollte dieses Problem nicht mehr relevant sein.

**Comment by Rillke** [comment]
LTI Upload benötigt OC 8.3 ... während des Semesters ein Upgrade nicht denkbar, aber egal. So wichtig ist das hier nicht.

**Comment by luniki** [comment]
Ok, das klären wir noch.

**Comment by Rillke** [comment]
Mhhm, wenn der LTI-Upload gegen unseren Ingest-Server funktioniert, bin ich happy und brauche das hier nicht mehr. Wir werden schon irgendwann auf Opencast 8.3+ aktualisieren. Es gibt nur Bedenken den Admin-Knoten an die Welt freizugeben. Das kann ich durchaus nachvollziehen.

**Comment by Rillke** [comment]
Wir haben seit 1 Jahr Opencast 8, das issue ist damit gegessen.
