### ISSUE TITLE
Standardworkflow für Uploads: Es werden nur WFs mit Tag schedule und schedule-ng gefunden

### ISSUE THREAD

**Issue by Rillke** [elan-ev/studip-opencast-plugin#215]
Es werden nur Workflows mit Tag `schedule` und `schedule-ng` gefunden. Somit ist es nicht möglich beim Standardworkflow für Uploads einen Workflow zu wählen, der ausschließlich mit `upload` getagged ist, aber kein Scheduling unterstützt. Das ist z.B. für den neuen `studio-upload` Workflow sinnvoll. s. https://github.com/opencast/opencast/pull/1478

**Comment by luniki** [comment]
Ist das noch weiter erforderlich? IMHO sollte #253 das Problem lösen.

**Comment by Rillke** [comment]
Es geht um die Auswahl des Workflows fürs Hochladen, für den der Studio WF auch viel geeigneter ist, weil er nahezu alle Video-Formate verarbeiten kann.

![image](https://user-images.githubusercontent.com/2311611/79833902-7217d700-83ac-11ea-8131-5d02167cb925.png)

**Comment by luniki** [comment]
Was wäre dein Vorschlag, welche der Workflows gesucht werden sollen? Alle scheint mir auch nicht besonders praktikabel?

**Comment by Rillke** [comment]
Solche, die mit `upload` markiert sind? Dass man für Capturing Agents auch nur `schedule` WFs findet ist total in Ordnung. [Aber für Uploads](https://github.com/elan-ev/studip-opencast-plugin/blob/63970c0f83ed417aaf8d76c65e15a5a8fed8c5e2/controllers/course.php#L637)?
