### ISSUE TITLE
Anzeige des Bearbeitungsstatus von Videos die via OC Studio hochgeladen wurden

### ISSUE THREAD

**Issue by tgloeggl** [elan-ev/studip-opencast-plugin#219]
Außerdem auch solche die direkt in OC hochgeladen werden.

**Comment by luniki** [comment]
Irgendwelche Ideen, wie man das herausfindet? @CGreweling ?

**Comment by CGreweling** [comment]
Till hatte in eine Version des Plugins schon einen Vortschrittsanzeige eingebaut. Die erschien, wenn man Videos über Medienhochladen eingefügt hatte.
Im Zweifel muss @tgloeggl  hier sagen, wo das ist

**Comment by luniki** [comment]
@tgloeggl hat angemerkt, dass ein Fortschrittsbalken nicht hilfreich sein wird. Genügt dann also der vorhandene Tooltip?

**Comment by luniki** [comment]
@rrolf hat angemerkt, dass man einen nicht deterministischen Fortschrittsbalken anzeigen könnte.

Eventuell wird es demnächst aus Opencast selbst ein Attribut geben, dass diesen Fortschritt angibt.

**Comment by tgloeggl** [comment]
Ist erledigt! Siehe #286
