### ISSUE TITLE
Hochladen: UX: Fenster nicht schließen, Warnung beim Verlassen der Seite

### ISSUE THREAD

**Issue by Rillke** [elan-ev/studip-opencast-plugin#221]
Beim Hochladen der Mediendateien ist nicht ganz klar, wie sich Benutzer verhalten sollen: Der Button "Medien hochladen" ist nach einem Klick weiter anklickbar, der Fortschrittsbalken ist ggf. aus dem Sichtbereich gescrollt und darf man das Fenster bei100% schließen?

Ich wünsche mir den Hinweis: Fenster nicht schließen, es schließt sich automatisch wenn das Hochladen abgeschlossen ist oder wie in Opencast Studio einen eindeutigen Indikator. Außerdem wäre es gut, wenn man die Browser-Warnung beim Verlassen der Seite, dass Daten verloren gehen könnten schalten würde, falls der Upload noch nicht vollständig ist.

Aktuell erhalten wir ca. 40% an Episoden ohne Medien-Datei. Das bessert sich sicher, wenn es alle raushaben, aber besser ein gutes Benutzererlebnis als ein enttäuschendes.

**Comment by CGreweling** [comment]
Ein Nutzer berichtet:
- Wenn man auf StudIP versucht über "Medien hochladen" eben das zu tun,
sollte man tunlichst nicht irgendwo in den Browser klicken. Der upload
wird dann sofort und ohne Rückfrage abgebrochen. Das ist wirklich sehr
sehr unglücklich.

**Comment by luniki** [comment]
Würde es helfen, wenn der Medien-Upload kein Dialog wäre, sondern eine einfache Seite?

**Comment by Rillke** [comment]
> Würde es helfen, wenn der Medien-Upload kein Dialog wäre, sondern eine einfache Seite?

Das würde versehentliches Schließen immerhin unwahrscheinlicher machen. Bevor der Upload nicht komplett ist oder fehlgeschlagen, sollte der Benutzer beim Verlassen der Seite oder des Tabs auf jeden Fall eine Warnung erhalten.

Es wäre ein guter erster Schritt. Folgendes bitte unter der Prämisse: [_Be careful that perfect does not become the enemy of good._](https://en.wikipedia.org/wiki/Perfect_is_the_enemy_of_good)

Wäre es als Seite implementiert - bereits jetzt lässt sich schon eine Seite an Stelle des jQuery UI Dialogs aufmachen, indem der Link im neuen Tab geöffnet wird - könnte man darüber nachdenken, ob die aktuelle Hauteinteilung sinnvoll ist:

- Aufzeichnungen (mit den Aktionen hochladen, Studio etc.)
- Aufzeichnungen planen

IMHO sind "Aufzeichnungen planen", hochladen und Studio gleichwertige Aktionen, die sich nicht auf die Anzeige von Aufzeichnungen (Sichtbarkeit etc) beziehen. Entweder man zieht alle Hinzufüge-Aktionen ins Aktionsmenü oder ins Hauptmenü des Opencast Reiters.

**Comment by luniki** [comment]
Der Upload erfolgt jetzt im eigenen Fenster.

**Comment by luniki** [comment]
@tgloeggl als PO sollte entscheiden, ob die Navigation angepasst wird oder nicht. Das wäre dann allerdings ein eigenes Issue.

**Comment by tgloeggl** [comment]
Das überarbeiten der Navigationsstruktur würde ich später in einem eigenen Ticket mit weiteren Dingen sammeln wollen. Der eigentliche Inhalt dieses Tickets ist erledigt, deshalb schließe ich das jetzt.
