### ISSUE TITLE
Jahreszahl abgeschnitten

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/studip-opencast-plugin#224]
![Screenshot from 2020-03-30 18-38-23](https://user-images.githubusercontent.com/1008395/77938376-f13a5380-72b5-11ea-877a-b7062877c7f3.png)

Das Jahr sollte da eigentlich 2020 sein aber man sieht nur die ersten drei Ziffern.

**Comment by Rillke** [comment]
Auch die Uhrzeit ist teilweise abgeschnitten und ich muss AM/PM angeben. Das bekommen die meisten Dozenten gar nicht hin.
