### ISSUE TITLE
Existierende ACLs werden beim Einbinden einer Series entfernt

### ISSUE THREAD

**Issue by Rillke** [elan-ev/studip-opencast-plugin#228]
Beim Einbinden einer Serie ersetzt das Plugin die existierenden ACLs vollständig. Dadurch ist es z.B. nicht möglich, eine Serie in 2 Stud.IP Veranstaltungen zu nutzen oder in Stud.IP und ILIAS.

Die Stärke von Opencast liegt gerade darin, dass multiple Publikationskanäle unterstützt werden.

Wenn es ein Feature und kein Bug ist, könnte man darauf hinweisen?

**Comment by luniki** [comment]
Ist #258 ein Symptom dieses Issues?

**Comment by Rillke** [comment]
> Ist #258 ein Symptom dieses Issues?

Ja.

**Comment by tgloeggl** [comment]
https://github.com/elan-ev/studip-opencast-plugin/commit/4d56d3c4f60ae2ea6a2ff446c1c5f3fd87d874ce

**Comment by tgloeggl** [comment]
Das ist nun eingebaut und muss noch extensiv getestet werden.

**Comment by Rillke** [comment]
https://github.com/elan-ev/studip-opencast-plugin/commit/4d56d3c4f60ae2ea6a2ff446c1c5f3fd87d874ce#diff-47e37b8c30e452353b684f575f7a27b6R144

Das berücksichtigt vermutlich vorerst nur in Stud.IP eingebundene Serien?
Ist ein 2. Issue, mit dem Wunsch, Serien in anderen LMS gleichzeitig mit Stud.IP einbinden zu können sinnvoll?

**Comment by rrolf** [comment]
Prinzipiell funktioniert dieses Feature mit Admin, Dozent und Autor. 

Aktuell hab ich noch ein paar kleinere Probleme:
 - Bevor ich egal ob in der original Serie oder der Eingebundenen noch keinen Sichtbarkeit gesetzt habe und dann die Sichtbarkeit ändern will, wird mir der aktuelle Status nicht schon vorausgewählte angezeigt.  Der Status bei einer Aufzeichnung ist aber korrekt angezeigt. 
-  Wenn ich dann die Sichtbarkeit setze (egal ob auf Sichtbar oder Unsichtbar) wird mir bei allen  Modaldialogen zum setzen der Sichtbarkeit immer unsichtbar angezeigt.

**Comment by tgloeggl** [comment]
> [4d56d3c#diff-47e37b8c30e452353b684f575f7a27b6R144](https://github.com/elan-ev/studip-opencast-plugin/commit/4d56d3c4f60ae2ea6a2ff446c1c5f3fd87d874ce#diff-47e37b8c30e452353b684f575f7a27b6R144)
> 
> Das berücksichtigt vermutlich vorerst nur in Stud.IP eingebundene Serien?

Ja, das ist richtig. 

> Ist ein 2. Issue, mit dem Wunsch, Serien in anderen LMS gleichzeitig mit Stud.IP einbinden zu können sinnvoll?

Denkbar, kannst du gerne erstellen. :) So ist es zumindest dokumentiert und man kann das falls nötig angehen.
