### ISSUE TITLE
Browser-Kompatiblitätslevel ist nicht spezifiziert und entspricht nicht dem von Stud.IP

### ISSUE THREAD

**Issue by Rillke** [elan-ev/studip-opencast-plugin#229]
Internet Explorer 11 und andere ältere Browser kommen noch irgendwie mit den meisten Funktionen von Stud.IP klar. Allerdings nicht mit diesem Plugin seit es die `async` function gibt.

Um unnötige Support-Anfragen zu vermeiden und überhaupt ein Kompatibilitätslevel festzulegen, habe ich javascripts/application.js durch babel und webpack gejagt.

Im aktuellen offiziellen Release steckt das Script einfach so drin.

Zusätzlich habe ich eine Warnung für Benutzer einiger alte Browser eingebaut:

> Ihr Browser wird leider nicht vollständig unterstützt. Wenn Sie sich an den Support wenden, nennen Sie bitte folgende Information ... UA string ...

**Comment by luniki** [comment]
Unterschiedliche Stud.IP-Versionen spezifizieren unterschiedliche "Kompatibilitätslevel". Insbesondere gilt schon seit der Stud.IP-Version v4.3, dass der IE11 nicht unterstützt wird.

Dennoch würde es nicht schaden, das Plugin-Javascript durch babel zu schicken.

**Comment by Rillke** [comment]
> Unterschiedliche Stud.IP-Versionen spezifizieren unterschiedliche "Kompatibilitätslevel".

Dann wäre es cool, wenn Stud.IP das dem Nutzer auch irgendwie sagt. In 4.1 jedenfalls gibt's diese Info nicht.

**Comment by luniki** [comment]
In Stud.IP vor v4.3 war immer die generelle Aussage, dass die letzten 2 Browserversionen (ausgehend vom Release-Zeitpunkt) unterstützt würden.
Nachdem nicht klar war, wie es dann mit IE und Edge aussieht, wurde das zur Stud.IP v4.3 so entschieden (dass IE11 nicht mehr unterstützt wird).
