### ISSUE TITLE
Studierende sollten Videos in Opencast Hochladen können.

### ISSUE THREAD

**Issue by rrolf** [elan-ev/studip-opencast-plugin#232]
Egal ob über Arbeitsgruppen oder innerhalb einer Veranstaltung, wenn der Lehrende das freigegeben hat, wäre es gut, wenn der Studierende auch eigene Videos in Opencast hochladen könnten.

**Comment by CGreweling** [comment]
Wäre schön eine "weitere" Konfiguration rechts zu haben. Studierende können Videos Hochladen/Aufnehmen

**Comment by tgloeggl** [comment]
Gibt es eine Rolle, die alle LTI-Nutzer aus Stud.IP gemeinsam haben?

**Comment by tgloeggl** [comment]
Wir mit #316 behoben sein über den Umweg einer Studiengruppe.
