### ISSUE TITLE
Chunk-Upload mit LTI Upload austauschen

### ISSUE THREAD

**Issue by rrolf** [elan-ev/studip-opencast-plugin#233]
Der Chunk-Upload ist leider nicht zuverlässig und langsam. 

Mit Opencast 8.3 könnte man über die LTI Authentifizierung Upload direkt zu Opencast hinzuzufügen.

**Comment by CGreweling** [comment]
Momentan werden Alle Uploads von Studio angenommen und in einem Studio Temp Ordner zwischengespeichert. Und dann an einen Chunk-upload Service von Opencast weitergegeben.
Das ist sehr langsam, ca. 3-10mal so langsam wie ein direct upload.
Der in "Curl"; zu opencast so aussehen könnte:
```
curl -f -i  -H 'X-Requested-Auth: Digest' \
    http://localhost:8080/ingest/addMediaPackage -F creator='John Doe' -F title='Test Recording' \
    -F 'flavor=presentation/source' -F 'BODY=@test-recording.mp4' 
```
Eine Authentifierung ist durch lti gegeben und somit für den ingest nicht extra nötig.

Evtl. gibt es da schon etwas im Plugin. nur bitte nicht den Rest Enndpoint /upload ("https://oc-admin.virtuos.uos.de/upload") nutzen. Das ist der chunk upload.

**Comment by luniki** [comment]
Alles klar, das sollte ungefähr so funktionieren wie in OC Studio. Schau ich mir an.
