### ISSUE TITLE
Leser sehen Opencast Episodenübersicht aber werden in Opencast nicht angemeldet

### ISSUE THREAD

**Issue by Rillke** [elan-ev/studip-opencast-plugin#240]
In Stud.IP gibt es die Rollen LeserInnen, Studierende, TutorInnen usw.

Als LeserIn sieht sieht man den Tab Opencast, alle Episoden und kann die Videos anklicken. Angemeldet als Learner ist man allerdings nicht in Opencast. Deshalb erhalten Leser*Innen eine entsprechende [Fehlermeldung](https://blog.studip.uni-halle.de/2020/opencast-hilfe-ich-sehe-manchmal-kein-video/). 

Erwartetes Verhalten:
LeserInnen können den Tab Opencast sehen, erhalten dort aber einen Hinweis, dass nur Studierende die Videos ansehen können und ggf. der Dozierende helfen kann.

**Comment by luniki** [comment]
Ich habe bei meinen CoreGroup-Kollegen und -Kolleginnen nachgefragt: Es gibt zwar die Rolle Leser in Stud.IP, in wie weit diese aber tatsächlich noch in modernen Stud.IPs verwendbar ist, sei fraglich.

Aus diesem Grund empfehle ich, dieses Issue zu schließen. Was sagt @tgloeggl dazu?

**Comment by Rillke** [comment]
@luniki Heißt das, ich sollte mal bei unserem Stud.IP Support nachfragen, weshalb die Rolle noch angeboten wird? Was heißt "modernes Stud.IP" konkret?

**Comment by luniki** [comment]
Wird diese Rolle an eurer Hochschule systemweit und/oder veranstaltungsbezogen vergeben? Viele Stud.IP-Installationen verwenden dieses alte Feature nicht mehr, sodass es immer häufiger vorkommt, dass Plugin-Autoren sich dieser Rolle nicht bewußt sind. Sie ist sicherlich vorhanden, aber wird an vielen Stellen nicht genügend beachtet.

Ein modernes Stud.IP wäre sicherlich eines ab Version v4.0. Warum die Anführungszeichen?

Die CoreGroup ist die Gruppe der Maintainer von Stud.IP.

**Comment by Rillke** [comment]
> veranstaltungsbezogen

Kann man das irgendwo abschalten?

**Comment by luniki** [comment]
Nein, das kann man nicht. Um welche Hochschule handelt es sich denn bei euch? Hast du Zugriff auf die seminar_user? Habt ihr viele status="user"?

**Comment by Rillke** [comment]
> welche Hochschule

Halle-Wittenberg

```sql
SELECT count(*) FROM studip.seminar_user where status = 'user';
```
```
count(*)
'20157'
```

Meine StudIP Administration sagt, dass sie den Status am liebsten ganz los wäre, weil das nur Support-Aufwand macht ...

**Comment by luniki** [comment]
Ich werde den Link zu den Videos entfernen und einen geeigneten Text anzeigen.

**Comment by luniki** [comment]
Ich hab das jetzt wie von  @Rillke vorgeschlagen umgesetzt.

**Comment by Rillke** [comment]
Danke.
