### ISSUE TITLE
anderer Workflow für Studio als für Upload

### ISSUE THREAD

**Issue by JFD23** [elan-ev/studip-opencast-plugin#245]
Wir haben Fehler gehabt mit den  `timelinepreviews`- und `waveform`-service wenn der `schedule-and-upload`-Workflow gewählt war, der bei uns z.zt. für Uploads gewählt ist. Mit dem `Studio Upload` Workflow kam es beim Erstellen von Videos via "Video aufnehmen" zu keinen Fehlern. 

Daher wäre mein Vorschlag entweder den Studio Upload WF im Plugin festschreiben oder per Config konfigurierbar zu machen. @JulianKniephoff hatte noch die Idee: 

> wenn das Plugin gar keinen WF an Studio übergibt, denn dann greift der, der dort als Standard konfiguriert ist. Damit hat man die beiden Szenarien, von denen wir hier reden, wieder unabhängig; was man dann allerdings nicht mehr unabhängig einstellen kann ist, welcher WF beim Upload in Studio durch Stud.IP vs. "direkt" benutzt wird. (Es sei denn natürlich man übergibt wieder URL-Parameter.)

**Comment by lkiesow** [comment]
Keinen übergeben ist sinnvoll. Denn cdamit ist es konfigurierbar.
