### ISSUE TITLE
Doppelte Verknüpfung scheint Aufzeichnungen verschwinden zu lassen.

### ISSUE THREAD

**Issue by luniki** [elan-ev/studip-opencast-plugin#258]
@rrolf berichtet:

> Ich hab ein spannendes Phänomen: 
> Ein Lehrender hat einen Kurs den er zweimal hält (Dienstags und Mittwochs)
> Er hatte gestern darum gebeten, das Opencast die selben Videos in beiden Kursen hat. Also habe ich die Serie mit dem zweiten Kurs verknüpft. Und das bis dahin einzige Video wurde mir angezeigt. 
> 
> Kurze Zeit später waren die Videos weg!
> 
> Aus sicht von Opencast sind die Publiziert und als Admin kann ich die auch abspielen. 
> 
> In Opencast sehe ich die kurz wieder, wenn ich republish Metadata mache. Aber nach einigen Minuten sind die dann doch wieder verschwunden.

**Comment by luniki** [comment]
Ich hab das beschriebene Phänomen versucht nachzustellen, hatte aber kein Glück dieses zu reproduzieren.

@CGreweling sagt aber, dass er Bescheid wisse. Vielleicht kann er die Details hier ablegen?

**Comment by Rillke** [comment]
Jedesmal, wenn jemand den Opencast-Reiter besucht, versucht das Stud.IP Plugin das ACL Template, welches den Benutzern des besuchten Kurses Zugriff auf die Episoden/Series gibt, anzuwenden. Wenn man eine Series mit 2 Kursen verknüpft kann man im Opencast Datenverzeichnis sehr schön sehen, wie die Snapshots ins Unendliche wachsen.

**Comment by luniki** [comment]
Die Ursache ist in #228 beschrieben worden.
