### ISSUE TITLE
LTI-Upload nur ab Opencast v8.3

### ISSUE THREAD

**Issue by luniki** [elan-ev/studip-opencast-plugin#260]
Nach der Integration des LTI-Uploads ist nun der normale Upload in Opencast-Instanzen v8.2 oder kleiner nicht mehr möglich.

Soll das so? Was machen wir jetzt damit?

**Comment by tgloeggl** [comment]
Hmm, wenn wir es "ordentlich" machen wollen, sollten wir abhängig von der Opencast-Version den bisherigen Upload anbieten, oder?
Alternativ können wir natürlich auch sagen: Setzt die neue Pluginversion nur ein, wenn euer Opencast aktuell genug ist - würde ich momentan auch akzeptieren, da alle die OC-Versionen nachziehen als gäbe es kein morgen.

**Comment by luniki** [comment]
Gut, das musst du als PO entscheiden.

**Comment by rrolf** [comment]
ich fände ältere Plugin-Version für ältere Systeme vollkommen okay

**Comment by Rillke** [comment]
> ich fände ältere Plugin-Version für ältere Systeme vollkommen okay

Ja, das ist okay. Verbesserungen kann ich mir Cherry-Picken und irgendwann kommt 8.x auch zu uns. #246 wäre aber interessant. Möchte den Admin nicht weltweit freigeben, aber mit einem Ingest habe ich weniger große Bauchschmerzen.
