### ISSUE TITLE
"Opencast-Test"system funktioniert nicht mit CORS-Preflights

### ISSUE THREAD

**Issue by luniki** [elan-ev/studip-opencast-plugin#261]
Der nginx-Server muss korrekt konfiguriert sein.

Macht man einen Testaufruf mittels`curl` erhält man nicht die korrekte Antwort. Generell sollte der Preflight-Request so funktionieren:

![image](https://user-images.githubusercontent.com/2993/79950777-dbb0e780-8477-11ea-953b-c42dbabbb1ae.png)

Der CORS-Preflight-Request sieht zB so aus:

```
curl -v 'https://<opencast-host>/ingest/addTrack' -X OPTIONS -H 'Access-Control-Request-Method: POST' -H 'Access-Control-Request-Headers: origin' -H 'Origin: http://localhost'
```

Die Antwort muss dann zB einen `Access-Control-Allow-Methods`-Header enthalten.  Stattdessen erhalte ich:

< HTTP/1.1 200 OK
< Server: nginx/1.12.2
< Date: Wed, 22 Apr 2020 07:06:36 GMT
< Content-Type: application/octet-stream
< Content-Length: 0
< Connection: keep-alive

**Comment by Rillke** [comment]
[INSTALL.md](https://github.com/elan-ev/studip-opencast-plugin/blob/master/INSTALL.md#opencast---cors) enthält bereits einen Hinweis darauf. Ich glaube ich ergänze gleich noch ein Beispiel.

**Comment by Rillke** [comment]
Andere Frage, dieses Issue hat nichts mit der hier entwickelten Software zu tun, oder?

**Comment by luniki** [comment]
Nur dahingehend, dass der Upload nicht funktioniert, wenn CORS nicht läuft. Die verlinkte Konfiguration ist IMHO aber nicht sicher. Der Header "Access-Control-Allow-Origin" entspricht dort einer Wildcard. Ich glaube nicht, dass man das möchte.

**Comment by Rillke** [comment]
> Die verlinkte Konfiguration ist IMHO aber nicht sicher. 

Darum habe ich das in #267 anders gelöst.
