### ISSUE TITLE
Studierende sollen Videos hochladen können und Studio nutzen können

### ISSUE THREAD

**Issue by rrolf** [elan-ev/studip-opencast-plugin#266]
In zahlreichen Seminare wollen Lehrende die Referate der Studierenden per Video eingereicht sehen. 

Derzeit können Studierende aber nichts hochladen

**Comment by rrolf** [comment]
Ich denke es wäre am besten wenn die Studierenden das (erstmal) auch nicht selber wieder löschen können.

**Comment by luniki** [comment]
Duplikat von #232 ?
