### ISSUE TITLE
Neu hochgeladene Medien sollten erst einmal unsichtbar sein.

### ISSUE THREAD

**Issue by rrolf** [elan-ev/studip-opencast-plugin#271]
Lehrende würden sich wünschen, dass die mit Studio erstellten (und ab und zu auch manuell hochgeladenen) Videos zunächst einmal unsichtbar sind und der Lehrende gibt die dann Manuell frei.

Die einfachste Lösung dafür wäre die ACL für Serien, ohne die Rechte für die Studierenden zu setzen.

**Comment by nimuelle** [comment]
das geht schon über studip-opencast-plugin, muss man in den einstellung als root freischalten....

**Comment by rrolf** [comment]
Wenn es der root umstellen kann gilt es ja aber doch wahrscheinlich für alle oder keinen? 

Ich würde das gerne für jeden Kurs einstellen können.

**Comment by nimuelle** [comment]
ja, das hat Till so gebaut, dass erstmal alle Lehrende bewusst sagen müssen "veröffentlichen". Das war bei uns in OL eine Datenschutzanforderung.

**Comment by tgloeggl** [comment]
Momentan geht das tatsächlich nur global. Auf VA-Ebene ist das natürlich auch denkbar, allerdings vergrößern sich dann die Problematiken im Umgang von einer Serie in mehreren Veranstaltungen. 

Ich packe es in die Prio-Liste, aber erstmal nach unten

**Comment by rrolf** [comment]
> Momentan geht das tatsächlich nur global. Auf VA-Ebene ist das natürlich auch denkbar, allerdings vergrößern sich dann die Problematiken im Umgang von einer Serie in mehreren Veranstaltungen.

Sehe ich nicht so. Ist ja nach wie vor eine Serie. Und die Einstellungen der Serie (Studis dürfen sehe oder nicht) sind dann in beiden Fällen gleich. Meistens ist ja sogar der Upload aus der zweiten VA deaktiviert.

**Comment by tgloeggl** [comment]
Ist mittlerweile für jeden Kurs separat konfigurierbar
