### ISSUE TITLE
PHP-Warnings

### ISSUE THREAD

**Issue by Davka** [elan-ev/studip-opencast-plugin#272]
` A non-numeric value encountered in public/plugins_packages/elan-ev/OpenCast/classes/OCJob.php on line 71`

`Division by zero in public/plugins_packages/elan-ev/OpenCast/classes/OCJob.php on line 71`

**Comment by luniki** [comment]
In welcher Plugin-Version kommt dieser Fehler?

**Comment by Davka** [comment]
1.2.112

**Comment by tgloeggl** [comment]
Der chunked uploader ist rausgeflogen zusammen mit dieser Klasse, der Fehler ist also so oder so behoben.
