### ISSUE TITLE
Editieren der Metadaten

### ISSUE THREAD

**Issue by rrolf** [elan-ev/studip-opencast-plugin#275]
Wo Lehrende jetzt mehr selber hochladen, passieren zahlreiche Tippfehler, die sie gerne selber korrigieren würden.

**Comment by luniki** [comment]
Bedeutet das zB auch, dass Lehrende den Titel einer Aufzeichnung ändern können sollen?

**Comment by rrolf** [comment]
Das ist ein viel geäußerter Wunsch, da es auch da häufiger als man denkt Tippfehler gibt.

**Comment by luniki** [comment]
Dann gebe ich das an @CGreweling weiter. Die Frage hatten wir häufiger und bisher gab es dazu immer ein "nein"

**Comment by CGreweling** [comment]
Wir könnten dafür auch den schon eingebundenen Editor nutzen. Das müsste man nur mal jemanden unbedarften geben, ob das auch verständlich nutzbar ist.

**Comment by CBockelmann** [comment]
Gibt es hierzu geplante Arbeiten? Mit dem aktuellen Wintersemester wird wieder viel über Videos gemacht und das Editieren von Video-Metadaten ist aus meiner Sicht fundamental für eine bequeme Verwaltung einer großen Anzahl von Videos.

**Comment by Davka** [comment]
Der Wunsch wurde bei uns auch geäußert.

**Comment by CGreweling** [comment]
@CBockelmann @Davka 

Das ist über den Eingebundenen Editor möglich. Editor öffnen -> Metadaten ändern -> Worklfow "republish metadata" (Metadaten aktualisieren) wählen -> "Speichern & Fortfahren"
Es wird an der UOS schon häufig genutzt. 
Das einzige, etwas unschöne daran. Wenn man "Speichern und Fortfahren" geklickt hat, bleibt man auf einer leeren Seite.
Das wurde aber als nicht so störend empfunden.

Sobald der neue Videoeditor in Opencast eingbaut ist, wird sich dieses Problem erledigen.  
Daher werde ich das Ticket hier als gelöst schließen.
