### ISSUE TITLE
Ist das Filtern nach dem `atom` Tag für Downloads noch sinnvoll?

### ISSUE THREAD

**Issue by Rillke** [elan-ev/studip-opencast-plugin#281]
In https://github.com/elan-ev/studip-opencast-plugin/blob/2c1a98b7d03e7a27049015acc0925a191f9481b3/models/OCCourseModel.class.php#L258 wird geprüft, ob eine Publikation mit `atom` getaggt ist. Genauso in https://github.com/elan-ev/studip-opencast-plugin/blob/2c1a98b7d03e7a27049015acc0925a191f9481b3/models/OCCourseModel.class.php#L281 wobei sich die Logik für Presenter und Presentation unterscheiden (Warum eigentlich?)

Seit 9b16bd8c5ef kann man in Stud.IP pro Kurs frei wählen, ob Videos herunter geladen werden sollen können oder nicht. Ist da das Prüfen auf das `atom` Tag noch sinnvoll? Warum überhaupt `atom` und nicht `engange-download`?

Bei mir habe ich die Prüfung vollständig rausgeworfen. Ansonsten fragen sich Lehrende, warum man z.B. nur Audio runterladen kann, obwohl der Download erlaubt haben. (Die Videos haben im WF bei uns keinen `atom` Tag erhalten). 

Es wäre nicht ganz durchsichtig, was man als Lehrender tun muss, um alle Tracks laden zu können.

**Comment by Rillke** [comment]
in #285 geht es auch um tags

**Comment by tgloeggl** [comment]
Siehe 0e99c03928de32a7d5ddfa3432d16f941d15027e
Es wird nun auch auf `engage-download` geprüft. Allerdings steht immer noch zur Diskussion, da Tag-Abfrage komplett zu entfernen, das wird aber in #285 geklärt. :)
