### ISSUE TITLE
Neuer Upload: Entfernen und neu hinzufügen funktioniert nicht

### ISSUE THREAD

**Issue by rrolf** [elan-ev/studip-opencast-plugin#287]
Wenn ich im neuen Dual-Stream Upload einen Datei hinzugefügt und dann entfernt habe ist nach dem erneuten hinzufügen die Datei verschwunden.

**Comment by tgloeggl** [comment]
Konnte ich nicht reproduzieren. Welcher Browser und welches Betriebssystem?

**Comment by rrolf** [comment]
Chrome. MacOS und Linux

Kein Problem bei Firefox (gerade gecheckt)

**Comment by tgloeggl** [comment]
Problem dürfte folgende Ursache haben:
https://stackoverflow.com/questions/6623310/input-file-onchange-event-not-being-fired-in-chrome
