### ISSUE TITLE
Opencast Studio in StudIP "Access denied"

### ISSUE THREAD

**Issue by ghost** [elan-ev/studip-opencast-plugin#289]
Ich habe den Opencast Server installiert und das PlugIn konfiguriert. Alles nach dieser Anleitung: https://github.com/elan-ev/studip-opencast-plugin/blob/master/INSTALL.md

Der Upload von Videos über das StudIP Plugin funktioniert problemlos. Aber die Video Aufnahme funktioniert nicht. Ich erhalte im Browser dann immer die Ausschrift "Access denied". 
Ich vermute, dass die Rechte von den von StudIP importierten Nutzern nicht korrekt gesetzt werden, da diese alle "ROLE_ANONYMOUS, ROLE_OAUTH_USER, ROLE_USER" erhalten. 
In welcher Konfigurationsdatei kann ich einstellen, dass die Nutzer die ROLE_STUDIO erhalten? 
Und welcher Konfigurationsparameter ist dafür zuständig? 
Muss noch etwas beachtet werden damit die StudIP Integration ordnungsgemäß funktioniert? 
Ich würde mich über eine schnelle Hilfe freuen.

**Comment by tgloeggl** [comment]
Vermutlich ist die gesuchte Einstellung (siehe [INSTALL.md](https://github.com/elan-ev/studip-opencast-plugin/blob/master/INSTALL.md)):


 3. Edit `etc/org.opencastproject.security.lti.LtiLaunchAuthenticationHandler.cfg` enable:

```
lti.create_jpa_user_reference=true
lti.custom_role_name=Instructor
lti.custom_roles=ROLE_STUDIO,ROLE_ADMIN_UI,ROLE_UI_EVENTS_DETAILS_COMMENTS_CREATE,ROLE_UI_EVENTS_DETAILS_COMMENTS_DELETE,ROLE_UI_EVENTS_DETAILS_COMMENTS_EDIT,ROLE_UI_EVENTS_DETAILS_COMMENTS_REPLY,ROLE_UI_EVENTS_DETAILS_COMMENTS_RESOLVE,ROLE_UI_EVENTS_DETAILS_COMMENTS_VIEW,ROLE_UI_EVENTS_DETAILS_MEDIA_VIEW,ROLE_UI_EVENTS_DETAILS_METADATA_EDIT,ROLE_UI_EVENTS_DETAILS_METADATA_VIEW,ROLE_UI_EVENTS_DETAILS_VIEW,ROLE_UI_EVENTS_EDITOR_EDIT,ROLE_UI_EVENTS_EDITOR_VIEW,ROLE_CAPTURE_AGENT
```
