### ISSUE TITLE
Upload und Studio Funktion für Rolle autor freigeben

### ISSUE THREAD

**Issue by JFD23** [elan-ev/studip-opencast-plugin#290]
Enhancement Vorschlag: 
Nicht nur unser Sprachenzentrum möchte in diesen Zeiten Präsentationen als Prüfungsleistung per Opencast Studio aufzeichnen lassen. 

Wäre es denkbar, den Dozenten die Option anzubieten: Studierenden Upload und Studio erlauben?

Ich werde mir jetzt mit der Hochstufung zu Tutoren behelfen...

**Comment by tgloeggl** [comment]
Gibt es eine Rolle, die alle LTI-Nutzer aus Stud.IP gemeinsame haben?
