### ISSUE TITLE
.unknown Dateien beim Medienupload verbieten

### ISSUE THREAD

**Issue by tgloeggl** [elan-ev/studip-opencast-plugin#295]

**Comment by Rillke** [comment]
Die `.unknown` Dateien entstehen erst in Opencast wenn es nicht versteht, welches Video-Format die Datei besitzt. Wenn Nutzende eine `test.pptx hochladen`, landet ein `test.unknown` in den Opencast assets.

**Comment by CGreweling** [comment]
Daher nur Videos erlauben und alles andere verbieten.
.mkv,.avi,.mp4,,mpeg,.webm,.mov

**Comment by tgloeggl** [comment]
- [ ] Dateiendungen beim LTI-Upload überprüfen/berücksichtigen
- [ ] Information über erlaubte Dateiendungen beim Upload ergänzen

**Comment by tgloeggl** [comment]
https://github.com/elan-ev/studip-opencast-plugin/commit/ff0988e11661f7186ef919128ecb718293f06b29
