### ISSUE TITLE
The 'custom_tool' parameter was invalid: 'null'. Reverting to default: '/ltitools'

### ISSUE THREAD

**Issue by ghost** [elan-ev/studip-opencast-plugin#301]
Hallo, 
die Verbindung zwischen StudIP und dem Opencast Server läuft. 
Ich erhallte immer die Fehlermeldung im Logfile, wenn ich versuche eine Datei in StudIP über der Opencast Plugin hochzuladen:
```
The 'custom_tool' parameter was invalid: 'null'. Reverting to default: '/ltitools'
No services of type 'org.opencastproject.ingestdownload' found, waiting ...
```

Kann mir bitte jemand helfen? 
Bin inzwischen ratlos. Leider habe ich auch in der Doku und Googlesuchen keine hilfreichen Infos gefunden.

**Comment by tgloeggl** [comment]
Der custom_tool-Parameter ist hierbei nicht das Problem. Höchstwahrscheinlich liegt das Problem an fehlenden Rollen für LTI in Opencast und/oder an CORS-Headern, siehe [INSTALL.md](https://github.com/elan-ev/studip-opencast-plugin/blob/master/INSTALL.md)
