### ISSUE TITLE
Allow using Series and Episodes in multiple LMS, i.e. do not delete existing rules not set by Stud.IP

### ISSUE THREAD

**Issue by Rillke** [elan-ev/studip-opencast-plugin#303]
This is a follow-up of #228.

When attaching an Opencast Series to a Stud.IP course, this plugin removes existing ACLs (and sets their own). The same happens when the Plugin finds that ACLs do not equal its expected value, e.g. during visibility changes. This makes it impossible to share a series between another LMS and Stud.IP.

We would love to use Series and Episodes in other LMS as well without even having to tell Stud.IP about their usage. The plugin could just add/manage the ACLs required for viewing in Stud.IP and leave those of other LMS untouched.

**Comment by tgloeggl** [comment]
No longer an issue in V2 or V3! The ACLs are not touched, only the ones belonging to STUDIP. Further more, in future OC version the need to touch ACLs might completely vanish.
