### ISSUE TITLE
"Denglisch" in Opencast

### ISSUE THREAD

**Issue by tleilax** [elan-ev/studip-opencast-plugin#304]
Wir haben bei uns folgende Rückmeldung erhalten:

> Bei der englischen Version von Opencast sind ihr eine ganze Reihe deutsche Meldungen oder "Parameter" aufgefallen, die eingeblendet werden.

- <img width="1145" alt="cw01" src="https://user-images.githubusercontent.com/130213/82199262-c192e980-98fd-11ea-809f-62ce00b98f95.png">
- <img width="1034" alt="cw02" src="https://user-images.githubusercontent.com/130213/82199279-c6579d80-98fd-11ea-9756-68400bff90f8.png">
- <img width="1247" alt="cw03" src="https://user-images.githubusercontent.com/130213/82199281-c6f03400-98fd-11ea-840d-561d502ea6ed.png">
- <img width="1402" alt="cw04" src="https://user-images.githubusercontent.com/130213/82199286-c8b9f780-98fd-11ea-8102-4769660c0fbb.png">

**Comment by tgloeggl** [comment]
https://github.com/elan-ev/studip-opencast-plugin/commit/8e1303684a3c2f3440ba40065865b17c68192bfc

**Comment by tgloeggl** [comment]
https://github.com/elan-ev/studip-opencast-plugin/commit/ebeb51b8e68e9b9442e84a268c10e324f4082c32

**Comment by tgloeggl** [comment]
Es fehlen noch Übersetzungen in der application.js

**Comment by tgloeggl** [comment]
Übersetzungen in V3 sind nun durchgängig und werden aktuell gehalten.
