### ISSUE TITLE
OC Plugin in Studiengruppen

### ISSUE THREAD

**Issue by tgloeggl** [elan-ev/studip-opencast-plugin#316]
- [x] Testen: Klappt das problemlos in Studiengruppen?
- [x] "Studiengruppe: " vor den Serientitel bei den Studiengruppen
- [x] Link um direkt Studiengruppe zu erstellen mit allen VA Teilnehmenden als Berechtigte
- [x] Einsprungpunkt zur Studiengruppe (falls vorhanden) vom Plugin aus
- [x] In Studiengruppen soll es nicht möglich sein, weitere Studiengruppen per Knopfdruck zu erstellen, der Link darf dort nicht auftauchen
- [x] Wird die Option deaktiviert, sollte die Uploadmöglichkeit in der Studiengruppe ebenfalls deaktiviert werden
- [x] Wird die Option reaktiviert, sollte die vorhandene Studiengruppe weiter verwendet werden
- [x] Bei aktivierter Option sollte es die Möglichkeit geben, die Teilnehmerliste der Studiengruppe zu aktualisieren, sofern sich diese von der VA unterscheidet.

**Comment by luniki** [comment]
### Link um direkt Studiengruppe zu erstellen mit allen VA Teilnehmenden als Berechtigte

Wo soll dieser Link platziert werden?

**Comment by luniki** [comment]
### Einsprungpunkt zur Studiengruppe (falls vorhanden) vom Plugin aus
Wo wird dieser Einsprungpunkt platziert?

**Comment by tgloeggl** [comment]
siehe auch #232

**Comment by tgloeggl** [comment]
Um bestimmte Dinge, wie das unabsichtliche Abschalten des Opencast-Plugins in der Studiengruppe durch Studierende zu verhindern, haben in der erstellten Studiengruppe nun alle die gleichen Rechte wie in der zugeordneten Veranstaltung.

In dieser speziellen Studiengruppe bekommen Autoren im LTI ebenfalls die Rolle 'Instructor'
