### ISSUE TITLE
Downloads standardmäßig verbieten

### ISSUE THREAD

**Issue by Davka** [elan-ev/studip-opencast-plugin#324]
Aktuell ist es so, dass die Videos standardmäßig heruntergeladen werden können.

Besser wäre es, wenn man dieses standardmäßig verbieten würde und Lehrende es explizit aktivieren müssen.

**Comment by nimuelle** [comment]
Ja, das wurde sich bei uns auch des öfteren gewünscht...

**Comment by Davka** [comment]
Das lässt sich auch so einfach ändern. 

Im Stud.IP auf Admin -> System -> Konfiguration unten die Ansicht auf "Veranstaltungskonfigurationen" stellen und dort den Wert bei "OPENCAST_ALLOW_MEDIADOWNLOAD_PER_COURSE" auf no setzen.
