### ISSUE TITLE
verschiedene Angaben zur studipMaxVersion

### ISSUE THREAD

**Issue by JFD23** [elan-ev/studip-opencast-plugin#325]
plugin.manifest = 4.4
Readme Github = 4.5
Beschreibung Plugin Marktplatz = 4.6

Ich habe es durch händiges Anpassen der StudipMaxVersion auf einem Stud.IP 4.5 zum Laufen bekommen. Kann aber noch nicht sagen, ob alles so läuft wie es soll. Siehe nächstes Issue.

**Comment by luniki** [comment]
Das gleichen wir mal besser an.

**Comment by luniki** [comment]
Fixed in bbd2088
