### ISSUE TITLE
Wenn eine Raumbuchug gelöscht wird, wird die geplante Aufzeichnung nicht gelöscht

### ISSUE THREAD

**Issue by CGreweling** [elan-ev/studip-opencast-plugin#327]

**Comment by tgloeggl** [comment]
Einmal verifizieren, ob das immer noch auftritt und bei Bedarf beheben.

**Comment by tgloeggl** [comment]
Fixed in https://github.com/elan-ev/studip-opencast-plugin/commit/acc6448c3e2c938b8b34b8dbc179e1c3edefd38e
