### ISSUE TITLE
Annotation tool link einfügen

### ISSUE THREAD

**Issue by CGreweling** [elan-ev/studip-opencast-plugin#328]
Das Annotation-tool lässt sich jetzt recht leicht mit Opencast installieren.
Ein Link aus dem plugin heraus wäre wünschenswert.
Beispiel:
https://staging-oc-presentation.virtuos.uni-osnabrueck.de/annotation-tool/index.html?id=d8c8f878-4f58-4ced-83e2-01f994136dcc

Das ist ein publish internal Link in Opencast. Vermutlich bekommnt man den aus der External API

**Comment by tgloeggl** [comment]
Man bekommt den Link, wenn man über api/events sich ebenfalls die Publikationen geben lässt. Dort gibt es dann eine Listen von Publikationskanälen, die haben jeweils ein `channel`-Attribut, dort muss `annotation-tool` drinstehen. Auf der selben Eben gibt es dann auch das Attribute `url`, dies ist dann die korrekte URL zum Annotation-Tool!
