### ISSUE TITLE
Studio "Zurück-Link" übergeben (und evtl. nicht mehr `target='_blank'`?)

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/studip-opencast-plugin#329]
Moin!

Ich hab vor ein paar Wochen in Studio die Möglichkeit eingebaut, einen Zurück-Link zu übergeben (https://github.com/elan-ev/opencast-studio/pull/674). Studio zeigt dann nach der Aufnahme (und nachdem Hoch- oder Runtergeladen wurde) einen zusätzlichen Button "Beenden und zurück" an. Das verhindert, dass Nutzer in einer UI-Sackgasse landen.

Es wäre super, wenn das Stud.IP Opencast Plugin die neue Funktion nutzen könnte. Zurzeit öffnet sich der Link zu Studio ja in einem neuen Tab (vermutlich gerade weil bisher diese UI Sackgasse bestand). Es müssten einfach nur zwei GET parameter an den Link angehängt werden:

- `return.target`: die URL-encoded URL, zu der der "zurück" button verlinken soll
- `return.label`: eine kurze Beschreibung, wohin der Nutzer zurückkehrt. Kann auch nicht angegeben werden. Der Button in Studio wäre wie folgt beschriftet:
  - Mit `return.label=Stud.IP`:  "Beenden und zurück (Stud.IP)" (Englisch: "Exit and go back to Stud.IP")
  - Ohne Label: "Beenden und zurück zur vorherigen Seite" (Englisch: "Exit and go back to previous page")

Wenn ihr Sprach-Informationen habt, könnt ihr natürlich auch das Label "Stud.IP Kurs" (bzw. "Stud.IP course") nutzen. Oder sowas.

Beispiel:

```
https://opencast/studio/
   ?upload.seriesId=c6e9b5ab-a9eb-4e6b-9854-01b6886e0587
   &return.label=Stud.IP
   &return.target=https%3A%2F%2Fstudip.example.de%2Fplugins.php%2Fopencast%2Fcourse%2Findex%2Ffalse%3Fcid%3D51b5d0f9b9866b781fecfc2f8335193e
```

Studio in Opencast 8 unterstützt diese Funktion noch nicht. Allerdings passiert bei älteren Studio Versionen nichts, wenn man die GET parameter trotzdem angibt. (Es wird eine Warnung in der Browser Konsole ausgegeben, aber das bekommen Nutzer ja nicht mit.) Also kann man die GET Parameter jetzt schon einbauen.

**Comment by luniki** [comment]
Ich kann davon nur abraten, dieses Feature auf diese Weise umzusetzen. Das ist ein klassisches Beispiel für ein "Unvalidated Redirect" (oder auch "Open Redirect"):

https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html

Gefahren und Problem sind dort ganz gut beschrieben. Ansonsten finden sich unproblematsch etliche weitere Artikel zum Thema

**Comment by LukasKalbertodt** [comment]
Oh mist. Die Problematik war mir nicht bewusst. Vielen Dank für den Hinweis. Wir werden das nochmal besprechen und mögliche Optionen durchgehen, aber vermutlich wird das in Studio noch vor dem Opencast 9 Release gefixt.

**Comment by LukasKalbertodt** [comment]
Wir haben gerade mal überlegt und denken, dass eine simple Domain-Whitelist (die man für Studio auf der Serverseite konfiguriert) gut funktionieren sollte. Hat einige Vorteile, wie z.B. dass die LMS in denen schon `return.target` und so benutzt wird, nicht nochmal geändert werden müssen. Ich habe ein Extra Issue dafür erstellt: https://github.com/elan-ev/opencast-studio/issues/720

**Comment by LukasKalbertodt** [comment]
Ist in Studio gefixt. Für dieses Stud.IP Plugin ändert sich nichts, also mein oberstes Kommentar ist immer noch aktuell und beschreibt, was das Stud.IP Plugin machen müsste.

**Comment by tgloeggl** [comment]
https://github.com/elan-ev/studip-opencast-plugin/commit/eabd1d35f201a6e6fbb08eaa629fbe425ef97665
