### ISSUE TITLE
Optionales Einbinden vom Annotation Tool

### ISSUE THREAD

**Issue by rrolf** [elan-ev/studip-opencast-plugin#333]
1.  Das Annotation Tool kann auch über einen Workflow-Parameter aktiviert werden. 

1. Custom ACL Actions sind in den Rechten notwendig um das Annotation Tool nutzen zu können. 

1. Das Annotation Tool sollte bei den Aufzeichnungen aufrufbar sein, wenn es verfügbar ist.

**Comment by tgloeggl** [comment]
refs #328
