### ISSUE TITLE
Spelling/Translation errors (German to English)

### ISSUE THREAD

**Issue by peculiarPrince** [elan-ev/studip-opencast-plugin#335]
1. Awkward phrasing when Teacher/Tutor disallows participants to download opencast recordings:
![image](https://user-images.githubusercontent.com/38320410/93061434-d9903500-f673-11ea-94a1-1772e460ad18.png)
Suggest: change "are not allowed anymore" to "are no longer allowed

2. Misspelled "recording" in first button to upload media to opencast in Stud.IP:
![image](https://user-images.githubusercontent.com/38320410/93061544-ffb5d500-f673-11ea-9254-fda8d5b21906.png)

3. The word "sichtbar" was not translated from German to English in the message bar when making the navigation tab visible again (after having made it invisible to participants):
![image](https://user-images.githubusercontent.com/38320410/93061685-312ea080-f674-11ea-8d00-fa2b7088b846.png)

**Comment by tgloeggl** [comment]
Fixed in https://github.com/elan-ev/studip-opencast-plugin/commit/64b3368df13ca58c304f884ef388a900354aabd3
