### ISSUE TITLE
Tutors do not see that an upload is being processed

### ISSUE THREAD

**Issue by peculiarPrince** [elan-ev/studip-opencast-plugin#337]
The in-progress processing bar does not appear for tutors, even when they upload their own recording.
Tutor view:
![image](https://user-images.githubusercontent.com/38320410/93063735-fa0dbe80-f676-11ea-9712-3d25b94dc866.png)

Dozent view at the same time:
![image](https://user-images.githubusercontent.com/38320410/93063748-fda14580-f676-11ea-8f02-9266f7b9af68.png)

**Comment by tgloeggl** [comment]
fixed in https://github.com/elan-ev/studip-opencast-plugin/commit/a4a3257f60224485735e1e9fee1277048be82754
