### ISSUE TITLE
Opencast-Reiter nicht ausblenden, wenn keine Serie verknüpft ist

### ISSUE THREAD

**Issue by tgloeggl** [elan-ev/studip-opencast-plugin#344]
Wird das OC-Plugin beispielsweise als Übersichtsseite für eine VA-Kategorie festgelegt, so hat das fatale Folgen, wenn dort keine Serie verknüpft ist.
Schöner wäre, eine MessageBox anzuzeigen die darüber aufklärt, dass es für diese VA noch keine (sichtbaren) Videos gibt.

**Comment by ssrahn** [comment]
#348
