### ISSUE TITLE
Sichtbarkeit der Aufnahme bei Upload einstellen

### ISSUE THREAD

**Issue by JFD23** [elan-ev/studip-opencast-plugin#351]
DozentInnen müssen derzeit warten, bis Aufnahme verarbeitet wurde, bevor Sie entscheiden können, wer die Aufnahme sehen kann. Daher wäre es vorteilhaft, wenn sie vor dem Upload entscheiden könnten, ob die Aufnahme für alle, für TN oder nur sie selbst sichtbar sein soll.

**Comment by tgloeggl** [comment]
Das ist nun geregelt oder wird noch geregelt mit Playlistensichtbarkeit und der global einstellbaren Standardsichtbarkeit in V3
