### ISSUE TITLE
Fehlgeschlagene Aufzeichnungen werden nicht mehr angezeigt

### ISSUE THREAD

**Issue by felix-itz** [elan-ev/studip-opencast-plugin#352]
Warum nochmal wurde 7a366eb41596355 durchgeführt?

**Comment by tgloeggl** [comment]
Da diese fehlgeschlagen Workflows niemals verschwinden und dadurch die UI stören wurden sie entfernt. 
Für solche Monitoringaufgaben ist die Opencast Admin UI der richtige Weg.

**Comment by Rillke** [comment]
Die meisten Lehrenden wissen noch nichts von der Admin UI. Gelegentlich werden kaputte Videos hochgeladen und die Lehrenden versuchen es dann mehrmals, weil sie aus ihrer Sicht einfach verschwinden.

**Comment by felix-itz** [comment]
Ein Lehrender schrieb:

> Für mich wäre vor allen Dingen eine Fehlermeldung hilfreich gewesen mit dem Hinweis, dass hochformatige Videos nicht verarbeitet werden können. Für mich sah es so aus, als seien die Videos einfach grundlos verschwunden.
