### ISSUE TITLE
Support für Untertitel

### ISSUE THREAD

**Issue by chdudek** [elan-ev/studip-opencast-plugin#355]
Opencast und der Paella Plyer unterstützen die Anzeige von Untertiteln, z.B. im [WebVTT](https://www.w3.org/TR/webvtt1/) Format. Das Plugin sollte es ermöglichen mehrere Untertitel zu einem Video hochzuladen.

**Comment by tgloeggl** [comment]
# Vorbereitende Arbeiten
- [ ] Wie fügt man Untertitel in Opencast via API hinzu?
- [ ] Lassen sich diese mittels dem Editor bearbeiten?
- [ ] Kann man Untertitel auch wieder löschen?
- [ ] Werden diese angezeigt, wie verhält es sich mit unterschiedlichen Sprachen?

**Comment by ssrahn** [comment]
Wurde schon getestet, ob die Untertitel tatsächlich im Player angezeigt werden? In meinem Testsystem wird mir im Player kein Icon für Untertitel angezeigt.

Falls das funktioniert kann das Issue geschlossen werden.

**Comment by tgloeggl** [comment]
Ok, es fehlt noch ein Punkt (deshalb tauchen die Untertitel auch nicht bei dir auf @ssrahn ):
- [ ] Nach dem hochladen von Untertiteln aus Stud.IP muss man noch den "Publish" Workflow starten (bzw. was auch immer dafür eingestellt wurde in der globalen Konfiguration)

**Comment by tgloeggl** [comment]
Meine Idee wäre nun, einen konfigurierbaren Workflow für das publizieren der Untertitel zu verwenden. 
Es gäbe, wenn ich das richtig verstehe, auch die Möglichkeit, einen Workflow zu parametrisieren, um die Untertitel zu publizieren/aktualisieren - dafür müsste dann aber die UI noch mehr angepasst werden.

Welche Variante macht mehr Sinn?

**Comment by lkiesow** [comment]
Muss das überhaupt direkt in das Plugin? Ich würde es maximal in den Uploaddialog einfügen. Da kannst du das einfach als weiteren Track hinzufügen.

Später kannst du Untertitel eh über den Opencast Editor hinzufügen und bearbeiten, wenn das aktiviert ist.

**Comment by ssrahn** [comment]
Ich hab in #958 die Workflow-Selection in den Uploaddialog eingebaut, allerdings funktioniert das noch richtig bei mir. Ich vermute es liegt daran, da die captions über das Plugin generell nicht richtig hinzugefügt werden.

Momentan werden sie über den Endpunkt "POST /{eventId}/track" hinzugefügt, wobei im flavour "captions/source+\<lang\>" die Sprache angegeben wird. Beim anstoßen eines Workflows (ich hab fast getestet) entfernt er die Datei dann aus den Assets.
Hier https://github.com/opencast/opencast/issues/4407 hab ich gesehen, dass die Sprache und andere Informationen über Tags mitgegeben werden sollte - Das könnte jetzt an der OC Version liegen, die in meinem Testsystem installiert ist, sollte man sich aber nochmal ggf. angucken.
