### ISSUE TITLE
Einführen von Unterkategorien

### ISSUE THREAD

**Issue by CBockelmann** [elan-ev/studip-opencast-plugin#357]
Der derzeitige Stand des Opencast-Plugins im Stud.IP der Uni Bremen erlaubt es eine Serie zu einer Veranstaltung anzulegen, in welcher dann alle Videos landen, die man hochlädt.

Es wäre toll, wenn man stattdessen mehrere Serien oder Unterkategorien definieren kann, um so Videos zu gruppieren. Ich habe meine Inhalte in kleinere (verdaulichere) Happen zerlegt, so dass über das Semester eine große Menge an Dateien/Einträgen auf der Opencastseite gezeigt werden. Da man diese weder sortieren noch durchsuchen kann, wird das schnell sehr unübersichtlich.

**Comment by tgloeggl** [comment]
Das sollte auf jeden Fall beim überarbeiten des Plugins berücksichtigt werden, ist aber momentan nicht schnell umsetzbar.

**Comment by tgloeggl** [comment]
#505, #497
Ist als UserStory und die Refaktorisierung des Plugins mit eingeflossen
