### ISSUE TITLE
Anzeigen von Statistiken

### ISSUE THREAD

**Issue by CBockelmann** [elan-ev/studip-opencast-plugin#358]
Derzeit ist das Opencastplugin im Stud.IP der Bremer Uni sehr karg. Man kann eine Serie anlegen, Videos hochladen und deren Metadaten eingeben. Danach hat man eine (scheinbar) unsortierte Liste von Videos, die man nicht editieren oder sortieren kann.

Man kann zudem auch nicht sehen, ob bereits jemand auf ein Video zugegriffen hat. Es wäre aber für Dozenten wünschenwert, den Fortschritt der Studierenden in einer Videoreihe zumindest grob einschätzen zu können. Eine einfache Statistik wie "X mal gesehen" wäre da schon sehr hilfreich.

**Comment by tgloeggl** [comment]
Ich frage einmal beim Opencast-Team nach, was es da in Sachen Statistiken gibt.

**Comment by tgloeggl** [comment]
Das ist in V3 nun besser: Es gibt eine Anzeige darüber, wie oft ein Video angeklickt wurde. Außerdem sind zahlreiche Sortiermöglichkeiten hinzugekommen, die die Anforderungen aus diesem Ticket nun abdecken sollten. :)
