### ISSUE TITLE
Tutoren können Sichtbarkeit nicht ändern.

### ISSUE THREAD

**Issue by CGreweling** [elan-ev/studip-opencast-plugin#360]
Fehlermeldung: 
``` Die Sichtbarkeit kann momentan nicht geändert werden! Opencast arbeitet momentan an diesem Video. ```
Anscheinend wird im Plugin explizit nach einem Dozenten account gefragt.

Tutoren sollten die Sichtbarkeit ändern dürfen.

**Comment by nimuelle** [comment]
Das würde ich anders sehen. Der Lehrende ist für das Video verantwortlich, wenn der das gar nicht will, dass ein Tutor das veröffentlicht?
Bei uns wurde explizit darauf geachtet, dass nur der Lehrende / Besitzer der Aufzeichnung das ändern darf.

**Comment by mgieseki** [comment]
Bei uns ist es genau anders herum. Die Tutoren sollen die Sichtbarkeit ausdrücklich ändern dürfen, da viele Lehrenden die sukzessive Freischaltung vorab hochgeladener Videos an ihre Hilfskräfte delegieren. In OS müsste die Änderung also zeitnah zur Verfügung stehen. Ggf. brauchen wir dann noch eine Option zur Festlegung der minimalen Rechtestufe.

**Comment by nimuelle** [comment]
mit einer "Option zur Festlegung die Rechtestufe" könnte ich gut leben ;-)

**Comment by felix-itz** [comment]
Dozent*innen, die Tutoren als solche in Veranstaltungen eintragen, müssen damit leben können, dass Tutoren alles dürfen, was sie selbst können, außer andere Tutoren zu benennen.

**Comment by tgloeggl** [comment]
Also machen wir einen Müllerschen Schalter dazu. :smile:

**Comment by tgloeggl** [comment]
- [ ] Global Einstellung, in der zwischen der Rechtestufe "dozent" und "tutor" ausgewählt werden kann, ab welcher man Sichtbarkeiten ändern darf. Default ist "dozent"
- [ ] Alle Abfragen die auf "dozent" prüfen anpassen und zu "tutor" ändern.

**Comment by tgloeggl** [comment]
https://github.com/elan-ev/studip-opencast-plugin/commit/17dc3ced1b29af9a14ae86679f9062e799017ea6
