### ISSUE TITLE
Standardsichtbarkeit für neue Videos Einstellbar machen.

### ISSUE THREAD

**Issue by CGreweling** [elan-ev/studip-opencast-plugin#361]
Es wäre schön, wenn der Dozent selbst die Standardsichbarkeit für seine Veranstaltung setzen könnte.
@tgloeggl das müssten wir evtl. noch diskutieren.

**Comment by tgloeggl** [comment]
Das sollte relativ problemlos gehen. Global gibt es dafür schon einen Schalter, Man müsste lediglich (wie bei den Workflows) das lokal überschreiben können.
