### ISSUE TITLE
"Entfernen" führt nur retract aus, sollte aber komplett löschen.

### ISSUE THREAD

**Issue by CGreweling** [elan-ev/studip-opencast-plugin#362]

**Comment by tgloeggl** [comment]
Im Opencast-Terminus muss also statt workflow_definition_identifier = retract was gemacht werden?

**Comment by felix-itz** [comment]
Die Methode [`DELETE /{eventId}` der Admin-ng](https://stable.opencast.org/docs.html?path=/admin-ng/event#deleteevent-7) macht beides: Retract+Delete

**Comment by tgloeggl** [comment]
> Die Methode [`DELETE /{eventId}` der Admin-ng](https://stable.opencast.org/docs.html?path=/admin-ng/event#deleteevent-7) macht beides: Retract+Delete

Ja, das ist richtig - ich wollte eigentlich vermeiden, diese "magischen" admin-ng-Routen zu verwenden, wer weiß schon, wie stabil die sind über die Versionen hinweg oder ob sich da nicht einfach ein Verhalten ändert. (Das gehört eigentlich die external API).
Aber da man sonst wieder Vodoo mit abwarten von Workflows machen muss, läuft es wohl darauf hinaus, dass wir doch deisen Endpoint nehmen...

**Comment by tgloeggl** [comment]
- [ ] In constants.php admin-ng bei $SERVICES hinzufügen
- [ ] Neue Klasse AdminNgClient.php in classes/OCRestClient/
- [ ] Löschaufruf auf neue Klasse umbauen

**Comment by tgloeggl** [comment]
fixed in https://github.com/elan-ev/studip-opencast-plugin/commit/5cb4e8dd03ca79094cfe200d7b23c99b906ef269
