### ISSUE TITLE
Admins sehen keine Serien/Episoden im Auswahldialog zum Einbinden einer Episode in den Quelltext

### ISSUE THREAD

**Issue by felix-itz** [elan-ev/studip-opencast-plugin#364]
Beschreibung: Admins sehen keine Serien/Episoden im Auswahldialog zum Einbinden einer Episode in den Quelltext

Schritte zur Reproduktion:
1. Stud.IP mit Einrichungs-Admin haben
2. Videos in einer Veranstaltung der Einrichtung über Opencast Plugin zur Verfügung stellen
3. Video in Informationsseite oder "Themen" oder Forum versuchen einzubinden
![Screenshot from 2020-11-11 14-26-59](https://user-images.githubusercontent.com/69673133/98817151-ff467a00-2429-11eb-9890-cbc97c6d98ce.png)

Ergebnis: Als Lehrender funktioniert's, als Admin sieht man keine Serien.

Grund:

`OCSeriesModel::getSeriesForUser()`:

```sql
if ($GLOBALS['perm']->have_perm('root', $user_id)) {
 // ...
} else {
 // ...
  FROM seminar_user AS su
}
```
Admins sind aber nie seminar_user.

**Comment by tgloeggl** [comment]
Vermutlich reicht es dann, die Abfrage von 'root' auf 'admin' zu ändern.

**Comment by tgloeggl** [comment]
https://github.com/elan-ev/studip-opencast-plugin/commit/7016e2100e77d34f40be455235e86f89e0f50128
