### ISSUE TITLE
Dateien mit langen Dateinamen

### ISSUE THREAD

**Issue by Davka** [elan-ev/studip-opencast-plugin#372]
Dateien mit langen Dateinamen (> 250 Zeichen) lassen sich nicht hochladen.

Lädt man eine Datei mit 250 Zeichen hoch, fügt Opencast an Ende noch eine UUID hinzu. Dies führt zu einer Überlänge und zum Abbruch einer Workflow, sodass Medien nicht verarbeitet werden. Das sieht der Nutzer aber nicht.

**Comment by tgloeggl** [comment]
https://github.com/elan-ev/studip-opencast-plugin/commit/c1e23fa9997f65da4faa3d01aed78249c0d21d73

**Comment by felix-itz** [comment]
Der Fix ist durch meinen PR #379, der die gewählten Dateien sofort prüft leider wieder rausgeflogen. Das war keine Absicht, aber vermutlich hat es beim Merge geknirscht. @ssrahn Sendest du einen neuen PR?

**Comment by ssrahn** [comment]
Klar!
#388
