### ISSUE TITLE
Zu viele LTI Rollen

### ISSUE THREAD

**Issue by CGreweling** [elan-ev/studip-opencast-plugin#374]
Zu viele LTI Rollen

Nutzer die aus StudIP kommen behalten alle Rollen die sie mal hatten. Auch wenn diese nicht mehr in den Kursen eingeschrieben sind.

**Comment by felix-itz** [comment]
Die Rollenzuordnung findet aber in Opencast statt, oder? Und die Tabellen kann man ja regelmäßig leeren, sofern man Studierende dort überhaupt persistiert. Um Studierende von der Persistenz auszunehmen, hatte ich glaube ich beim elan e.V. bedingt einen Auftrag ausgelöst.

**Comment by felix-itz** [comment]
https://github.com/opencast/opencast/pull/2103 läuft bei uns. Weiß aber gerade nicht die Sitzungsdauer für die Studis. Wäre ja blöd, wenn während der Video-Annotation z.B. die Sitzung abläuft.

**Comment by tgloeggl** [comment]
Ist dieses Problem dann mit den vermerkten Anpassungen in Stud.IP behoben?

**Comment by tgloeggl** [comment]
Ich schließe das Ticket jetzt mal, scheint auf Seite behoben zu sein.
