### ISSUE TITLE
Mediendownload MP4 - Fehler beim Atom Tag

### ISSUE THREAD

**Issue by JFD23** [elan-ev/studip-opencast-plugin#382]
Medien, die über die Admin-UI hochgeladen werden, bekommen bei uns nun korrekt den Atom Tag zugewiesen. 
Medien, die über Stud.IP-Plugin hochgeladen werden, nicht. Diese Medien kann man dann nur als RTMPS "herunterladen", was aber niemand verwenden kann oder nur Cracks ;-)

Um die MP4 Download Funktion zu erhalten, die für uns wichtig ist, bitte ich um Behebung des Bugs. @JulianKniephoff vermutet einen Fehler in der "Trackauswahl" in [dieser Zeile in OCCourseModel.class.php:](https://github.com/elan-ev/studip-opencast-plugin/blob/master/models/OCCourseModel.class.php#L269)

**Comment by JulianKniephoff** [comment]
Also tatsächlich bekommen bei euch auch die über Stud.IP hochgeladenen Medien die richtigen Tags. (So zumindest meine Theorie. :sweat_smile:)

Aber in der Tat scheint mir die Klammerung in der besagten Zeile, und in einer ähnlichen Zeile ein paar Zeilen tiefer, nicht zu stimmen. Das `||`, was die beiden MIME-Type-Checks verbindet, bindet schwächer als das nachfolgende `&&`. Ich bin jetzt, ehrlich gesagt, nicht die gesamte Wahrheitstabelle durchgegangen, aber intuitiv könnte das das Problem erklären. Und unabhängig, ob es der Ursprung für das Problem hier ist, ist es trotzdem ein Bug, denke ich. :thinking:

**Comment by JFD23** [comment]
Ich habe den "Bug" lokal gefixt nur in der besagten Zeile. Nun geht bei uns der MP4 Download von Videos, die über das Plugin hochgeladen werden.

**Comment by JulianKniephoff** [comment]
Ich war mal so frei. :slightly_smiling_face:
