### ISSUE TITLE
LTI-Anmeldung prüfen

### ISSUE THREAD

**Issue by felix-itz** [elan-ev/studip-opencast-plugin#404]
Wenn die LTI-Anmeldung fehl schlägt, bekommt der Benutzer davon gar nichts mit. Man kann sogar hochladen ohne je eine Fehlermeldung zu sehen. Einziger Anhaltspunkt: Es taucht kein Video in der Episodenliste auf :)

Reproduzieren: Falschen Consumer Key oder Secret hinterlegen und versuchen hochzuladen oder anzusehen.

Erwartung: Fehlermeldung irgendwo vor dem Hochladen oder dem Versuch ein Video anzusehen.

> Leider hat etwas mit der Anmeldung an Opencast nicht geklappt. Bitte wende dich an [email] falls das Problem dauerhaft auftritt.

**Comment by tgloeggl** [comment]
- [ ] In der VA überprüfen, ob die LTI-Anmeldung geklappt hat (evtl. sogar ein kleiner optischer Hinweis?), auf jeden Fall Fehlermeldung, falls das nicht geklappt hat
- [ ] Beim abspeichern der Konfiguration im Adminbereich die LTI-Daten auch einmal prüfen

**Comment by tgloeggl** [comment]
Fehlermeldung für den Nutzung: "Es konnte keine Verbindung zum LTI in Opencast hergestellt werden. Laden sie die Seite neu. Falls das nicht hilft, wenden sich an eine/n Systemadministrator/in"
