### ISSUE TITLE
Hochladen für Studierende erfordert Freischaltung des Opencast Inhaltselements unter Admin -> Standort -> Veranstaltungskategorien -> Studiengruppen

### ISSUE THREAD

**Issue by felix-itz** [elan-ev/studip-opencast-plugin#406]
Beschreibung & Reproduktion: Wenn das Opencast Inhaltselement unter Admin -> Standort -> Veranstaltungskategorien -> Studiengruppen **nicht** freigeschaltet ist und der Upload für Studierende erlaubt wird, und man dann dem Link `Zur Studiengruppe` folgt, erhält man einen Fehler in der UI, keine Opencast Videos und einen Stacktrace in den Logs.

Tatsächliches Verhalten:
![image](https://user-images.githubusercontent.com/69673133/107068687-3afe9f00-67e1-11eb-8d7c-c901746dabf4.png)

```
NOTICE: PHP message: InvalidArgumentException: navigation item 'course/opencast/overview' not found in /var/www/studip/lib/navigation/Navigation.php:126
Stack trace:
#0 /var/www/studip/lib/navigation/Navigation.php(61): Navigation::getItem('course/opencast...')
#1 /var/www/studip/public/plugins_packages/elan-ev/OpenCast/controllers/course.php(161): Navigation::activateItem('course/opencast...')
#2 /var/www/studip/vendor/trails/trails.php(557): CourseController->index_action()
#3 /var/www/studip/app/controllers/studip_controller.php(127): Trails_Controller->perform('index')
#4 /var/www/studip/vendor/trails/trails.php(154): StudipController->perform('index')
#5 /var/www/studip/vendor/trails/trails.php(121): Trails_Dispatcher->map_uri_to_response('course/index')
#6 /var/www/studip/lib/plugins/core/StudIPPlugin.class.php(131): Trails_Dispatcher->dispatch('course/index')
#7 /var/www/studip/public/plugins.php(54): StudIPPlugin->perform('course/index')
#8 {main}
```

Erwartet:
Vielleicht dokumentiert man, dass Opencast in Studiengruppen aktiviert sein muss oder man bekommt es irgendwie hin, dass es im Fall der Erzeugung durch eine Veranstaltung trotzdem gezeigt wird?

Workaround:
Opencast Plugin muss mindestens "wählbar" für Studiengruppen sein:
![image](https://user-images.githubusercontent.com/69673133/107068308-bf9ced80-67e0-11eb-877d-41eecdbe345d.png)

**Comment by tgloeggl** [comment]
Lösungsvorschlag:
* Neue Konfigurationsoption bei den Admineinstellungen: "Dürfen Lehrende den Upload durch Studierende einschalten?"
* Erst wenn diese Option aktiviert ist, taucht der entsprechende Eintrag im Plugin in der VA auf
* Bei eingeschalteter Option wird bei den Studiengruppen "Opencast" auf "wählbar" gesetzt
* Infotext-Icon bei der Option: "Aktivierien sie diese Option, so ist es Lehrenden gestattet den Upload von Opencastvideos durch Studierende einzuschalten. Dabei wird eine zur Veranstaltung gehörende Studiengruppe erstellt, in welcher Studierende entsprechende Rechte haben um Videos mit Opencast Studio aufzuzeichnen und/oder hochzuladen.
ACHTUNG: Wird diese Option aktiviert, so wird für ALLE Studiengruppen das Einschalten des Opencastplugins erlaubt!"

**Comment by tgloeggl** [comment]
https://github.com/elan-ev/studip-opencast-plugin/commit/d41d022ee635c9f94dd537665efe916d1d0be111

**Comment by tgloeggl** [comment]
- [ ] Meldung am Anfang der Seite anzeigen
- [ ] Meldung als Fehler anzeigen
- [ ] Meldung wird immer angezeigt für Rechtestufe tutor oder höher
- [ ] "Hochladen durch Studierende erlauben" nicht einschaltbar, solange der Fehler da ist
- [ ] Bei Autoren wird der Zutrittslink nicht angezeigt, selbst wenn das Hochladen erlaubt ist, es aber diese Fehlkonfiguration gibt
