### ISSUE TITLE
Opencast in Studiengruppen nicht nutzbar

### ISSUE THREAD

**Issue by Davka** [elan-ev/studip-opencast-plugin#420]
Irgendwann wurde eingeführt, das intern für Veranstaltungen Studiengruppen angelegt werden, damit Teilnehmer ihre Videos hochladen können.

Das führt nun dazu, dass händisch angelegte Studiengruppen mit Opencast nicht nutzbar sind. Auch vorher angelegte Studiengruppen

**Comment by tgloeggl** [comment]
* [ ] Globaler Konfigschalter, der es verhindert, das Opencast-Plugin in Studiengruppen einzuschalten. Default ist ab sofort, dass das geht.
* [ ] Beim Betreten einer Upload-Studiengruppe aus der VA heraus, wird dafür gesorgt, dass das OC Plugin auf jedenFall eingeschaltet ist.

**Comment by Davka** [comment]
Das Problem ist nach wievor nicht gefixt.

Ich habe im System alte Studiengruppen, in denen das Plugin aktiviert war und nun nicht mehr nutzbar ist, denn


```
$controller->isStudyGroup() && $controller->isStudentUploadForStudyGroupActivated()
```
liefert immer ein false
