### ISSUE TITLE
Medien hochladen kaputt?!

### ISSUE THREAD

**Issue by dofeldsc** [elan-ev/studip-opencast-plugin#422]
Wir haben folgende Anfrage über die Support-Mailingliste erhalten:
"Allerdings hatte ich beim Hochladen von Medien Probleme:
er zeigte an, dass das Video hochgeladen würde, das dauerte auch einige Zeit
das habe ich gestern Nachmittag gemacht - irgendwann verschwand die Meldung und jetzt - einen Tag später ist das Video immer noch nicht aufgetaucht. Das fühlt sich gerade an wie ein Mühlschlucker - rein und weg.
Wo muss ich suchen?"

Ich habe es auf [Stud.IP Ammerland](https://ammerland.elan-ev.de/) in einer Testveranstaltung ausprobiert und konnte das Problem rekonstruieren.
Ich habe folgendes gemacht:

- In der Testveranstaltung den Reiter "Opencast" ausgewählt
- Unter "Aktionen" die Option "Medien hochladen" ausgewählt
- Im Dialog notwendige Titel etc. eingegeben
- unter "Aufzeichnung des/der Vortragende*n hinzufügen" ein kurzes Testvideo ausgewählt ("Aufzeichnung der Folien hinzufügen" verfällt sich auch so)
- Durch "Medien hochladen" die Auswahl bestätigen und Upload starten
- Dann erscheint ein kurzer Dialog mit einem Fortschrittsbalken für den Upload (Fortschritt voll -> Dialog weg, bis dahin alles super)
- Dann erscheint "Die Datei wurde erfolgreich hochgeladen. Je nach Größe der Datei und Auslastung des Opencast-Servers kann es einige Zeit dauern, bis die Aufzeichnung in der Liste sichtbar wird."
- Video ist nicht zu sehen. F5 und ich sehe das Video mit dem Status "Video wird verarbeitet.."
- nach kurzer Zeit ist das Video wieder weg und nicht aufzufinden

Es gab schon folgendes Ticket zu dem Problem: [Ticket el4](https://gitlab.elan-ev.de/studip/el4/-/issues/1#note_33394)

**Comment by CGreweling** [comment]
Das eigentliche Problem ist, dass der falsche Workflow gesetzt ist, und dieser gerade nachträglich nicht mehr systemweit geänderrt werden kann.
Mit dem hier hinterlegten wf kommt ein publish zu engage zu stande, daher taucht es auch nicht in studip auf.
#423
