### ISSUE TITLE
Opencast Resourcen -> Standard Workflow -> Alle anderen Workflows überschreiben  funktioniert nicht.

### ISSUE THREAD

**Issue by CGreweling** [elan-ev/studip-opencast-plugin#423]
Wenn man ``` Alle anderen Workflows überschreiben  ``` auswählt uns ausführt kommt ein fehler und es ist kein Standardworkflow mehr gesetzt.

**Comment by tgloeggl** [comment]
Ist bereits behoben und sollte nun auch in UOS korrekt funktionieren
