### ISSUE TITLE
Der Cronjob "Opencast - "Scheduled-Events-Refresh"" wurde deaktiviert, 

### ISSUE THREAD

**Issue by nimuelle** [elan-ev/studip-opencast-plugin#424]
Der Cronjob "Opencast - "Scheduled-Events-Refresh"" wurde deaktiviert, da bei der Ausführung ein Fehler aufgetreten ist.

Typ: InvalidArgumentException
Nachricht: CourseDate::room_assignment not found.
Code: 0
Stack trace:
  #$ lib/models/SimpleORMap.class.php(1363)
  #0 lib/models/SimpleORMap.class.php(1511): SimpleORMap->getValue('room_assignment')
  #1 public/plugins_packages/elan-ev/OpenCast/cronjobs/refresh_scheduled_events.php(59): SimpleORMap->__get('room_assignment')
  #2 lib/models/CronjobTask.class.php(112): RefreshScheduledEvents->execute('1', Array)
  #3 lib/models/CronjobSchedule.class.php(212): CronjobTask->engage('1', Array)
  #4 lib/classes/CronjobScheduler.class.php(339): CronjobSchedule->execute()
  #5 cli/cronjob-worker.php(34): CronjobScheduler->run()
  #6 {main}

**Comment by nimuelle** [comment]
Kommt ab Stud.IP 4.6 , weil Raumverwaltung umgestellt wurde.

**Comment by tgloeggl** [comment]
Das ist mittlerweile behoben
