### ISSUE TITLE
"Only" first 2000 series available when connecting series to Stud.IP course

### ISSUE THREAD

**Issue by Rillke** [elan-ev/studip-opencast-plugin#439]
When attempting to connect a series to a Stud.IP course, only the first 2000 returned by `/search/series.json` are displayed.
![image](https://user-images.githubusercontent.com/2311611/114009056-1b2c3b80-9863-11eb-90ba-509303ed0068.png)

This is because the search service somehow only returns 2000 series
![image](https://user-images.githubusercontent.com/2311611/114009498-7c540f00-9863-11eb-83fb-f213c149df1d.png)

and the [RestClient used](https://github.com/elan-ev/studip-opencast-plugin/blob/master/classes/OCRestClient/SearchClient.php#L81
) does not support continuation.

Expected behavior:
When connecting series as a Stud.IP root, I can find all series available in Opencast.

**Comment by tgloeggl** [comment]
- [ ] Als schnelle Lösung: Limit höher setzen, sofern Opencast das zulässt
- [ ] Perspektivisch gar nicht mehr alle Serien abrufen für root, sondern stattdessen eine Suche anbieten.

**Comment by Rillke** [comment]
Select2 kann auch AJAX-Anfragen: https://select2.org/data-sources/ajax - leider kann man nicht den Nutzer direkt per CORS beim Presentation anfragen lassen, da der Stud.IP Root kein Opencast Admin ist und alle Serien sehen kann ...

**Comment by tgloeggl** [comment]
Das direkte Problem ist erstmal etwas entschärft, die Verbesserung der Funktionalität habe ich in einem neuen Ticket hinterlegt, siehe #479

**Comment by Rillke** [comment]
![image](https://user-images.githubusercontent.com/2311611/145008074-3f5049e3-9916-4465-b718-772131a4eb7a.png)

Leider nicht entschärft.
