### ISSUE TITLE
Has your series_cache table entries? 

### ISSUE THREAD

**Issue by Rillke** [elan-ev/studip-opencast-plugin#441]
I found that our `oc_series_cache` has no rows. Cronjob `Opencast - "Serien-Refresh"` is active. Plugin version 1.26. Has your series_cache table entries?

**Comment by tgloeggl** [comment]
No, our table does not have any entries. Caching in a special table has been deprecated for a while now in the plugin, i will just remove the residual code now. Thx for the cue! :)
