### ISSUE TITLE
Admins können Hochladen und Planen, müssen aber keinen Nutzungsbedingungen zustimmen

### ISSUE THREAD

**Issue by Rillke** [elan-ev/studip-opencast-plugin#448]
Stud.IP Admins können hochladen und planen, müssen aber keinen Nutzungsbedingungen zustimmen. Das ist im Zusammenhang mit dem frei wählbaren Autoren-Feld für unsere Mediziner ein Problem, denn dort läuft es so:

1. Dozent gibt seine Video-Dateien ans Sekretariat
2. Sekretariat (Admins) lädt es für den Dozenten und unter seinem Namen (Autor) in die Veranstaltung
3. Studierende versuchen die Video zu sehen, sehen aber, dass zuerst ein Dozent den Terms of Service zustimmen soll.
4. Dozent ist verwundert, er hat doch alles ans Sekretariat delegiert
5. Sekretariat ist verwundert, es gab doch keine Terms of Service zum Akzeptieren

Sobald ein Dozent der LV die ToS akzeptiert ist es ja für die Studis sichtbar, aber das muss man den Dozenten erstmal verraten.

**Comment by tgloeggl** [comment]
Ok, das wiederspricht grade ein wenig deinen anderen Änderungen, als du den Admins auch den Link zum wiederrufen der TOS weggenommen hast. :smile: 

Eigentlich gibt es für diese Fälle ("Ich tue etwas im Namen eines Lehrenden") doch die Dozierendenvertretung, oder täusche ich mich da? 

Ansonsten sehe ich allerdings kein Problem, auch Admin-Accounts die TOS abnicken zu lassen. Wer da nichts mit anfangen kann hat eh nichts beim OC-Reiter zu suchen

**Comment by Rillke** [comment]
>  Ok, das wiederspricht grade ein wenig deinen anderen Änderungen, als du den Admins auch den Link zum widerrufen der TOS weggenommen hast. 😄

Na, das war ein logischer Bug. Er konnte ja nichts widerrufen, was er gar nicht eingehen konnte. Dieses Issue hier könnte schon strittig sein und das will ich nicht durch die Hintertür lösen, sondern anderen Nutzenden/Hochschulen die Möglichkeit geben zu kommentieren.
