### ISSUE TITLE
Datenschutzrichtlinien vs Nutzungsvereinbarung Opencast

### ISSUE THREAD

**Issue by Rillke** [elan-ev/studip-opencast-plugin#453]
Intern spricht das Plugin von ToS (Terms of Service), in der UI steht dann aber Datenschutzrichtlinien oder ähnliches. Unsere sehen etwa so aus:

> Im Falle der Nutzung der Funktion „Aufzeichnungen planen“ im Opencast-Plugin bzw. der in Ihrem Auftrag erfolgenden Einbindung existierender oder neu hinzukommender Veranstaltungsmitschnitte bestätigen Sie, dass Sie folgende Punkte zur Kenntnis genommen und akzeptiert haben:
> Sie sind dafür verantwortlich, sicherzustellen, dass durch die Veranstaltung und die darin verwendeten Materialien keine Rechte Dritter verletzt werden. Dies betrifft insbesondere (aber nicht ausschließlich) den Einsatz urheberrechtlich geschützter Materialien. 
> Sie informieren die TeilnehmerInnen der Veranstaltung darüber, dass die Veranstaltungsreihe bzw. der Veranstaltungstermin aufgezeichnet und veröffentlicht wird und weisen sie auf ihre Rechte bezüglich des Schutzes ihrer Daten hin.
> Sie sind dafür verantwortlich, im Vorfeld der Veranstaltung die schriftliche Einwilligung anderer Personen einzuholen (z. B. Gastdozenten oder TeilnehmerInnen der Veranstaltung), die in den Aufnahmen zu sehen sind. Die Einwilligungserklärung ist von Ihnen bis zur endgültigen Löschung der Aufzeichnung aufzubewahren. 
> Studierende sollen i. d. R. (insbesondere im Rahmen von Lehrveranstaltungen) nicht aufgezeichnet werden. Kann ausnahmsweise eine Aufzeichnung erfolgen, muss sichergestellt sein, dass die Einwilligung freiwillig erfolgt und eine etwaige Verweigerung keine negativen Auswirkungen auf den weiteren Verlauf des Studiums hat (z. B. bei der Bewertung von Studienleistungen).
> [Die Maintainer] führen die notwendige technische Verarbeitung der Daten durch und bemühen sich um einen reibungslosen Ablauf. Für die tatsächliche Durchführung und die Qualität der Aufzeichnungen, den Zeitpunkt der Veröffentlichung sowie die ständige fehlerfreie Abrufbarkeit der Videos kann keine Garantie übernommen werden.

Ist es tatsächlich Absicht, dass ihr da nur auf den Datenschutz abzielt? Ließe sich das ggf. konfigurierbar machen, wenn wir keine Einigung finden, damit ich das zukünftig nicht mehr portieren muss?

Mein Vorschlag wäre "Nutzungsvereinbarung" als Oberbegriff. Datenschutzrichtlinien fallen ja dann auch darunter.

**Comment by tgloeggl** [comment]
Wir können es gerne einfach "Nutzungsvereinbarung" nennen, sehe ich kein Problem dabei.
