### ISSUE TITLE
LTI user mapping

### ISSUE THREAD

**Issue by Rillke** [elan-ev/studip-opencast-plugin#454]
Wie übersetzt ihr eure Stud.IP Benutzer ins Opencast? Die Stud.IP Benutzer ID ist lang und nicht angenehm zu lesen. Der Instaz-GUID ist ggf. unschön lang.

Benutze ich den Standard, bekomme ich etwas wie `lti:studipmlu:89233834934843938493489348234983` als Benutzernamen in Opencast. Dieser Benutzername erscheint dann auch z.B. im Annotation Tool und bei den Workflows und keiner weiß, wer das sein soll.

Ich habe `'tool_consumer_instance_guid' => 'lms',` gesetzt, um mit ILIAS einen gleichen Instanz-GUID zu haben und

```php
        $this->addVariable('User.id', $uid);
        $this->addLaunchParameter('user_id', $uid);
```

wobei `$uid` auf die E-Mailadresse des Benutzers gesetzt wird, sofern diese verfügbar ist. Dann kommt etwas lesbares wie `lti:lms:foo.bar@einrichtung.example.com` heraus.

**Comment by tgloeggl** [comment]
Schaue ich mir an, eventuell ist das schon behoben. Falls, finde ich das auf jeden Fall eine sehr gute Idee.

**Comment by tgloeggl** [comment]
Nach längerer Besprechung im Team sind wir zu der Übereinkunft gekommen, dass man sich damit potentiell weitere Probleme reinholt:
* Datenschutz: Dürfen Mail-Adressen von anderen Nutzern einsehbar sein?
  * Es müssten alle Spezialfälle berücksichtigt werden, wie ich mache mich unsichtbar auf der Teilnehmendenliste etc.
* Eine Umstellung der ID führt initial zu einer Verdopplung der Nutzerkennungen in Opencast, da müsste man dann nacharbeiten
* An einigen Standorten habe mehrere Accounts dieselbe Mail-Adresse, das führt dann zu Problemen, wenn Nutzer mit verschiedenen Sessions im Stud.IP unterwegs sind.

Der Aufwand, all diese Fälle zu berücksichtigen ist uns (momentan?) zu hoch, weswegen wir das nicht umsetzen können.

**Comment by Rillke** [comment]
@tgloeggl Danke fürs Diskutieren. Vielleicht lässt sich das Problem der **schwer nachvollziehbaren Job-Auslöser** in Opencast und der **unlesbaren Benutzernamen im Annotation Tool** ja irgendwie anders lösen. Spätestens wenn das andere Unis stört, wird's vermutlich behoben. Also warte ich einfach und trinke mit Mai Tee.

> Datenschutz: Dürfen Mail-Adressen von anderen Nutzern einsehbar sein? 

Solange ich als user aufgeklärt werde, vermutlich "Ja". Es muss ja eine Zusammenarbeit möglich sein.

> Eine Umstellung der ID führt initial zu einer Verdopplung der Nutzerkennungen in Opencast, da müsste man dann nacharbeiten

Ja, das stimmt. Man müsste aber vermutlich ohnehin fortlaufend oc reference user löschen, weil Herunterbeförderungen von Tutoren zu Studierende und Kursaustritte von Lehrenden und Admins nicht an OC weiter gegeben werden.

> An einigen Standorten habe mehrere Accounts dieselbe Mail-Adresse

Da war die Überlegung, dass wer die gleiche E-Mailadresse hat auch die gleichen Berechtigungen hat.

> das führt dann zu Problemen, wenn Nutzer mit verschiedenen Sessions im Stud.IP unterwegs sind.

Dann werden 2 Stud.IP Benutzer per LTI als der selbe OC Nutzer angemeldet. Hmm, sehe da erstmal kein Problem, aber das ist ja auch nur die hallesche Sparbrille.

**Comment by Rillke** [comment]
Wie es der Zufall so will: https://groups.google.com/a/opencast.org/g/users/c/WZPQIkCyRrg/m/MyCwV8EvAwAJ

> is it possible to use the mail address as username in opencast?

wäre auch eine Lösung. Mal sehen, was die Opencast Experten dazu schreiben.
