### ISSUE TITLE
Eingebettete Videos: Dozent kann mehr auswählen als Studis sehen dürfen

### ISSUE THREAD

**Issue by Rillke** [elan-ev/studip-opencast-plugin#459]
Beim Einbetten stehen einem Dozenten mehr Videos als Studis sehen dürfen zur Auswahl, wenn man Dozenten in Opencast persistiert. Das stiftet regelmäßig Verwirrung. Zum einen sind nicht alle Studis Teil aller LVs des Dozenten, zum anderen sind Studi-Anmeldungen in Opencast bei uns nicht (mehr) persistent gespeichert; sie haben daher häufiger nur Zugriff auf die während der Sitzung besuchten LV Videos.

Wir können Studi-Anmeldungen nicht mehr persistieren, weil das Opencast Admin-Interface selbst nach serverseitiger Filterung der Nutzer sich sehr träge verhält.

Dozenten sollen nur Videos der LV auswählen dürfen, in der er sich gerade befindet. (quasi eine abgeschwächte From von #163)

**Comment by tgloeggl** [comment]
Ok, könnte man versuchen. 
- [ ]  Nur komplett freie Videos und außerdem (sofern man sich überhaupt in einer VA befindet) Videos aus dieser VA listen.

**Comment by Rillke** [comment]
> BTW, wie wird das bei euch genutzt? Wenn der WYSIWYG-Editor eingeschaltet ist, kommt man ja eh nicht an den Dialog dran.

Der WYSIWYG-Editor ist administrativ ausgeschaltet. Weiß nicht warum; ich administriere das Stud.IP bei uns nicht. Zur Nutzung: Ich weiß von 3 Dozenten, dass sie es nutzen, weil sie jedes Semester mit Problemen rund um die Einbindung schreiben :)

Außerdem wollten einige Dozenten die Videos zu Veranstaltungsterminen bzw. Themen gruppieren (in ILIAS geht das ja mit dem PageComponent-Object von Studer-Raimann) also habe ich ihnen [eine Anleitung geschrieben](https://blog.studip.uni-halle.de/2020/opencast-videos-stud-ip-veranstaltungsterminen-zuordnen/).

Ist ja die einzige Möglichkeit, Videos in einen sinnvollen Kontext einzubetten.

**Comment by Rillke** [comment]
Art der Nutzung: Neben dem Gruppieren und Einbinden in Text-Kontext: Es auch genutzt, um aus einer Info-Seite eine Begrüßungsseite mit Video-Botschaft zu machen, und das gefällt mir in diesen Zeiten auch ausgesprochen gut.

**Comment by tgloeggl** [comment]
Es werden nun nur Veranstaltungen gelistet, in denen Videos sind:
* auf die die/der Nutzer/in Zugriff hat und weltweit sichtbar sind
* die im aktuellen Kontext (falls man innerhalb eine VA ist) sichtbar sind

Dadurch sollte sichergestellt sein, dass nur Videos gelistet werden, die ein Nutzer im verwendeten Kontext auch sehen kann.
