### ISSUE TITLE
Paginierung für Episoden zur Performanceoptimierung

### ISSUE THREAD

**Issue by tgloeggl** [elan-ev/studip-opencast-plugin#460]
- [ ] 10 Videos pro Seite
- [ ] Es muss unbedingt bereits im Backend paginiert werden, auch schon bei den Aufrufen Richtung Opencast
- [ ] Es muss sichergestellt sein, dass trotzdem alle Dinge wie LTI, Rollenberechtigungen, etc. weiterhin funktionieren
- [ ] Untersuchen, was genau am Meisten bremst (wie sieht das mit dem setzen der Rollenberechtigungen aus?)

**Comment by felix-itz** [comment]
Ein Lehrender bei uns schrieb:

> Nach dem Hochladen (aus dem Uninetz von wenige MB großen Dateien)
> vergehen bei jeder Datei ca. 25 bis 30 Sekunden, in den gar nichts
> passiert. Ich meine nicht das Konvertieren, sondern die Zeit, die ich
> warten muss, um das nächste Video in die Queue stopfen zu können.
> Gefühlt hat die Wartezeit im Laufe des Semesters zugenommen.

Vermutlich liegt es an der Zeit, die die Videoübersicht zum Laden braucht.

**Comment by Rillke** [comment]
Es gibt auch das Ticket #312

**Comment by tgloeggl** [comment]
Siehe  #563 es wird jetzt paginiert
