### ISSUE TITLE
Episoden lassen sich nicht löschen

### ISSUE THREAD

**Issue by Davka** [elan-ev/studip-opencast-plugin#461]
Auch wenn man die Rechte zum Löschen hat, erscheint nach dem Klick auf Entfernen

```
Die Episode konnte nicht zum Entfernen markiert werden.
```

**Comment by Rillke** [comment]
Welche Version habt ihr denn?

**Comment by Davka** [comment]
Stud.IP Version 4.6
Plugin Version 1.26

Ich hab einen Fork, der nun identisch mit dem hier ist und baue das Plugin selbst.

**Comment by Rillke** [comment]
Das Löschen funktioniert bei uns. Darf dein für Stud.IP in Opencast angelgeter Nutzer 1. über die AdminUI löschen und 2. ist die Route `DELETE /admin-ng/{eventId}` für diesen Nutzer in der [/etc/security/mh_default_org.xml](https://github.com/opencast/opencast/blob/develop/etc/security/mh_default_org.xml) freigegeben?

Müsste die Zeile `<sec:intercept-url pattern="/admin-ng/event/*" method="DELETE" access="...` sein.

**Comment by Davka** [comment]
```
<sec:intercept-url pattern="/admin-ng/event/*" method="DELETE" access="ROLE_ADMIN, ROLE_UI_EVENTS_DELETE" />
```

Der Stud.IP Nutzer hat die Rolle `ROLE_ADMIN`

**Comment by Rillke** [comment]
In der [Doku steht](https://github.com/elan-ev/studip-opencast-plugin/blob/master/INSTALL.md), dass der Stud.IP Nutzer auch die Rolle `ROLE_ADMIN_UI` haben soll. Unser Nutzer hat auch beide Rollen.

**Comment by Davka** [comment]
```
ROLE_ADMIN, ROLE_ADMIN_UI, ROLE_OAUTH_USER, ROLE_SUDO
```

Diese Rollen hat der Nutzer bei uns

**Comment by Davka** [comment]
Das Problem ist gelöst. In Stud.IP fehlten die jeweiligen Endpoints. 

Ich hab die OC-Einstellungen einfach durch nochmaliges Speichern aktualisiert.

**Comment by Rillke** [comment]
Stimmt, da war noch etwas. Sollte das Plugin vielleicht regelmäßig die Liste der gecachten Opencast Endpoints aktualisieren?
