### ISSUE TITLE
"Medien hochladen" sollte abgesetzt von den anderen Aktionen und möglichst groß sein

### ISSUE THREAD

**Issue by Rillke** [elan-ev/studip-opencast-plugin#472]
Hallo, ein Lehrender bei uns schrieb:

> die Ergonomie des Menü "Aktionen" bei StudIP-Opencast ist aus meiner
> Sicht nicht gut. Gerade auf einem Tablet ist der mit Abstand wichtigste
> Knopf "Medien hochladen" mit Touch äußerst schwer zu treffen. Deshalb
> sollte "Medien hochladen" abgesetzt von den anderen Aktionen und
> möglichst groß sein. Gefährliche Operation solle nicht nahe bei "Medien
> hochladen" sein.

Bei uns hat ein Designer ziemlich viel angepasst. Sieht es bei euch auch so aus, dass das Hochladen sehr dicht an "Verknüpfung aufheben" steht?
![image](https://user-images.githubusercontent.com/2311611/115873492-48701080-a443-11eb-9487-df91d6948fc6.png)

Anyway, ich denke, es wäre hilfreich, wenn die Hinzufügeoptionen (hochladen, aufnehmen) besser von den Admin-Aktionen getrennt wären.

**Comment by tgloeggl** [comment]
Da stimme ich zu, das Aktionsmenü braucht eine Überarbeitung.

**Comment by Rillke** [comment]
Gefällt mir. Danke :)

![image](https://user-images.githubusercontent.com/2311611/128996914-44f23779-0c49-4322-8435-bfd4d596a329.png)
