### ISSUE TITLE
button to delete videos

### ISSUE THREAD

**Issue by fkotte** [elan-ev/studip-opencast-plugin#48]
implementation of a button to delete videos via external api.

**Comment by luniki** [comment]
Ich hab mir die Dokumentation der External API angeschaut. Dort finde ich keinen Endpoint, der mir das erlauben würde. Kann mir jemand einen Hinweis auf die richtige Doku geben?

**Comment by luniki** [comment]
siehe fehlgeschlagener upload

**Comment by CGreweling** [comment]
@luniki wenn du den löschen button aus medienupload hast. hier reinschreiben, dann schaue ich mir den opencast teil an

**Comment by luniki** [comment]
Einmal hier:

https://github.com/elan-ev/studip-opencast-plugin/blob/b45d5c5f0ae621677f08e6f5115f400b6f015e32/classes/OCRestClient/WorkflowClient.php#L70

**Comment by luniki** [comment]
Das scheint aber ja nur einen Workflow zu entfernen. Wie bekommt man denn eine fertige Episode? Und löscht die dann?

**Comment by luniki** [comment]
Also muss vorher `retract`ed werden und danach gelöscht.

Das erste ist vermutlich ein `POST/api/workflows` mit:

- `event_identifier`: Das ist vermutlich die ID des Events, das ich löschen möchte.
- `workflow_definition_identifier`: Ist das dann also der String `retract`?

Muss jetzt gewartet werden, bis der Workflow fertig ist?

Danach wird ein `DELETE /api/events/{id}` abgesetzt?
