### ISSUE TITLE
#feature request: eigene Videos eigenen Veranstaltungen zuordnen.

### ISSUE THREAD

**Issue by fkotte** [elan-ev/studip-opencast-plugin#49]
usage of the external api to select specific series(lecture) for specific videos within the studip-opencast-plugin.

(german)
Nutzen der External API um Videos einer bestimmten "userid" (creator) für
den zugehörigen Nutzer in Stud.IP sichtbar und eigenen Veranstaltungen (Serien) zuordenbar zu machen.

**Comment by tgloeggl** [comment]
Möglich in V3
