### ISSUE TITLE
Als ein Lehrender möchte ich gerne Videos gruppieren und sortieren können, damit Lernende die Videos einfach einer Sitzung zuordnen können und in der richtigen Reihenfolge schauen

### ISSUE THREAD

**Issue by rrolf** [elan-ev/studip-opencast-plugin#497]
Erfüllt wenn:
- In der Studierenden Ansicht die Videos einem Thema zugeordnet werden können und die Themen und Videos in der vom Lehrenden gewünschten Reihenfolge zu sehen sind.

**Comment by tgloeggl** [comment]
Ist nun mittels der Playlisten möglich.
