### ISSUE TITLE
[UserStories] Als ein Lehrender sowie Studierender würde ich gerne den Fortschritt meines neu hochgeladenen Videos sehen, damit ich den Überblick über meine Aufzeichnungen behalte.

### ISSUE THREAD

**Issue by svensnd** [elan-ev/studip-opencast-plugin#501]

**Comment by peculiarPrince** [comment]
Als Studierende finde ich dies besonders wichtig, damit ich weiß wann ich mit einer Aufzeichnung rechnen kann, und somit mein Wochenplan dementsprechend besser planen kann!

**Comment by tgloeggl** [comment]
Als Lehrender ist das nun möglich, auf 10 Minuten genau. Eine genauere Anzeige würde wieder zu vile Abhängigkeit von der Performance des Opencast-Servers haben. Der grobe Fortschritt ist aber einsehbar.
