### ISSUE TITLE
[UserStories] Als ein Lehrender würde ich gerne eine Beschreibung für den Button "Cutting Tool" haben, damit ich weiß, dass dort neben dem Schnitt auch das ändern der Metadaten vorgenommen werden kann..

### ISSUE THREAD

**Issue by svensnd** [elan-ev/studip-opencast-plugin#503]
Da sollte dann auch, solange es im Editor noch nicht anders gehandhabt wird, eine Erklärung hin, dass "Nur Metadaten aktualisieren" gewählt werden soll.

**Comment by tgloeggl** [comment]
Besser ist es, die. die Metadaten direkt in Stud.IP editierbar zu haben und das als undokumentiertes Zusatzfeature zu behalten.
So können z.B. die Metadaten auch nur in Stud.IP lokal modifiziert werden, bei Episoden die in mehreren Kursen hängen ist das potentiell notwendig.
