### ISSUE TITLE
Als Lehrender würde ich gerne die Metadaten möglichst einfach und schnell ändern können, damit die korrekt sind und Studierende die passenden Aufzeichnungen schnell finden

### ISSUE THREAD

**Issue by rrolf** [elan-ev/studip-opencast-plugin#504]
- Lehrende finden intuitiv die Stelle an der sie Metadaten ändern können. 
- Das ändern der Metadaten ist immer möglich, oder es wird einem eine gute Begründung angezeigt, wieso es nicht geht
- Die Änderungen werden möglichst schnell an alle Stellen übernommen. 
- Man muss nicht noch irgendwelche verborgenen Aktionen ausführen um die Änderungen auch an allen Stellen zu übernehmen
- Ich bestätige eindeutig, dass ich die Änderungen speichern will. 
- Optional: Die Änderungen können auch Rückgängig gemacht werden.

**Comment by tgloeggl** [comment]
Geht nun in V3.
