### ISSUE TITLE
Als Studierende würde ich gerne die Länge eines Videos angezeigt bekommen, damit ich weiß wie viel Zeit ich dafür brauchen werde

### ISSUE THREAD

**Issue by peculiarPrince** [elan-ev/studip-opencast-plugin#509]
- Als Metadata gelistet, zusammen mit `Aufzeichnungsdatum`, `Autor`, und `Beschreibung` anzeigen
- Alternativ: Als Teil des Thumbnails zeigen

**Comment by Rillke** [comment]
Kam bei uns gerade auch als Anfrage rein.
