### ISSUE TITLE
XSS Sicherheitslücken

### ISSUE THREAD

**Issue by ssrahn** [elan-ev/studip-opencast-plugin#511]
- Rich-Text-Editor
    - zB im Forum beim Verfassen von Einträgen
    - Über "OpenCast-Video" Knopf lässt sich Video hinzufügen
    - Dialog ist XSS anfällig
    - Beim Namen der Aufzeichnung und der Serie
- clear_series_action in admin/controller
    - Serien-Titel werden ungefiltert ausgegeben
- remove_episode_action
    - Aufzeichnungen anderer Veranstaltung können womöglich auch gelöscht werden
    - Berechtigung wird nur für Serie und nicht für Aufzeichnung geprüft
- "Aufzeichnung planen"
    - Gibt bei "Titel" das im Ablaufplan hinterlegte Thema ungefiltert aus
- "Medien hochladen"
    - Gibt den eigenen Namen ungefiltert aus
    - steht im value-Attribut eines inputs, das man mit ">" erst mal verlassen muss und dann kann man ein Skript platzieren
- Möglicherweise werden Workflownamen und Capture-Agent-Namen ungefiltert ausgegeben

**Comment by ssrahn** [comment]
- [ ] Rich-Text-Editor
- [x] clear_series_action in admin/controller
    - Wird nicht genutzt, hab ich entfernt
- [x] remove_episode_action
    - Konnte ich nicht reproduzieren
- [x] "Aufzeichnung planen"
- [x] "Medien hochladen"
    -  Der Name wird in einem Textfeld gefiltert angezeigt. Da konnte ich kein XSS anwenden
- [x] Möglicherweise werden Workflownamen und Capture-Agent-Namen ungefiltert ausgegeben
- [ ] views nach weiteren Problemstellen durchsucht

**Comment by tgloeggl** [comment]
Im embed-Dialog könnte es noch Lücken geben
