### ISSUE TITLE
Ignorieren von ssl-errors

### ISSUE THREAD

**Issue by ssrahn** [elan-ev/studip-opencast-plugin#512]
https://github.com/elan-ev/studip-opencast-plugin/blob/7d7ee45756749732314b44b0be01dda8a3015328/controllers/course.php#L65 
"set the stream context to ignore ssl erros -> get_headers will not work otherwise"
- [ ] "erros" Rechtschreibfehler
- [ ] Prüfen, ob das Notwendig ist und ob man dadurch eine HTTPS-Verbindung zwischen dem Opencast und Stud.IP entschlüsseln könnte

**Comment by tgloeggl** [comment]
Wird nun in der OC-PHP-Library behandelt.
