### ISSUE TITLE
GraphQL - Schnittstellen Entwicklung

### ISSUE THREAD

**Issue by CGreweling** [elan-ev/studip-opencast-plugin#513]

**Comment by CGreweling** [comment]
Ein Video über Graphql von Julian:
https://tube.tugraz.at/paella/ui/watch.html?id=18dc54b4-3c8c-4959-85ec-f271d13edeaf

Ein Beispiel Shema von Lukas:
https://github.com/LukasKalbertodt/oc-graphql-dummy/blob/master/src/main/resources/schema.graphqls

Opencast Dummy implementation:
https://github.com/LukasKalbertodt/oc-graphql-dummy/blob/master/src/main/java/org/opencast/graphql/dummy/Event.java

 https://oc-graphql-dummy.herokuapp.com/

**Comment by tgloeggl** [comment]
Wir beginnen mit einem Baustein, der Episodenliste, und bauen das exemplarisch auf beiden Seiten dafür.

**Comment by CGreweling** [comment]
@tgloeggl ich könnte ja eine angepasste Version von Lukas Dummy-Code erstellen und irgendwo deplyoen. Dann könntet Ihr schonmal etwas testen. Die Frage ist nur wohin?
