### ISSUE TITLE
UserStories

### ISSUE THREAD

**Issue by ssrahn** [elan-ev/studip-opencast-plugin#515]
- [ ] #496 
- [x] #497 
    - Das wird schon durch Coursware umgesetzt oder? Macht es Sinn das noch über das Plugin umzusetzen?
- [ ] #498
- [x] #499 
    - Hier müsste es möglich sein, eine Aufzeichnung mehreren Course (LSM Kurs) zuzuordnen
- [x] #500 
    - Ist es OpenCast Seitig möglich nur Ton hochzuladen?
- [x] #501 
    - Kann OC dafür einen Status übermitteln? Oder wie könnte man das umsetzen?
- [x] #503 
    - Da sollten wir im Plugin drauf achten
- [x] #504 
    - Metadaten der Aufzeichnung nachträglich änderbar machen. Da würde sich ein Button anbieten, der zu einem Update-Formular leitet
- [x] #505 
    - Da müsste man dem Dozenten die Möglichkeit geben, eine "Quelle" anzugeben (zB aus LiveStream oder Meeting)
- [x] #506 
    - Sortierung durch Autoren hinzufügen
- [ ] #507 
    - Die Meetings laufen über BBB oder? Da wird es schwierig den Chat aufzuzeichnen. Wäre das bei Livestreams möglich?
- [x] #508 
    - Suchfunktion
- [x] #509 
    - Länge des Videos über Metadaten ausgeben lassen
- [x] #510 
    - Verlinkung der Folien zu StudIP Daten - über das Plugin

**Comment by tgloeggl** [comment]
Dieses Sammelticket ist nicht mehr notwendig.
