### ISSUE TITLE
LTI Consumersecret auf der Einstellungsseite im Klartext angezeigt

### ISSUE THREAD

**Issue by Rillke** [elan-ev/studip-opencast-plugin#521]
Das LTI Consumersecret auf der Einstellungsseite im Klartext angezeigt. Beim Erstellen von Screencasts und Screenshots ist das problematisch und man muss nacharbeiten. Auch, wenn man in einem crowded place Stud.IP administriert, ist das ungünstig.

<img width="746" alt="Screenshot 2021-08-27 at 11 50 00" src="https://user-images.githubusercontent.com/2311611/131108596-3a711441-cf04-4dd5-b498-63b8344c63c1.png">

Erwartetes Verhalten: Passwörter und Secrets (z.B. der API Key) werden in den Details durch Platzhalter dargestellt (Bonus: und können bei Bedarf eingeblendet werden).

<img width="375" alt="Screenshot 2021-08-27 at 11 46 45" src="https://user-images.githubusercontent.com/2311611/131108177-525e9844-5650-4e86-bf3f-8290df22f5ae.png">

**Comment by tgloeggl** [comment]
War grade eh an der Stelle dran und hab das mal direkt erledigt.
