### ISSUE TITLE
ROLE_CAPTURE_AGENT erlaubt allen Lehrenden das Verändern von Events, auf die sie Leserechte haben z.B. mit dem Editor

### ISSUE THREAD

**Issue by Rillke** [elan-ev/studip-opencast-plugin#538]
`ROLE_CAPTURE_AGENT` [wie unter Punkt 3 der Installationsanleitung gefordert](https://github.com/elan-ev/studip-opencast-plugin/blob/master/INSTALL.md#configure-opencast) erlaubt allen Lehrenden das Verändern von Videos, auf die sie Leserechte haben z.B. mit dem Editor.

Schritte zur Reproduktion
---------------------------------

* Melde dich als Admin auf https://legacy.opencast.org/admin-ng/index.html an
* Erstelle einen Nutzer mit den Rollen `ROLE_ADMIN_UI, ROLE_CAPTURE_AGENT, ROLE_UI_EVENTS_EDITOR_EDIT, ROLE_UI_EVENTS_EDITOR_VIEW, ROLE_UI_EVENTS_VIEW`
* Gib dem Nutzer Leserechte auf ein Video (Episode/Event)
* Melde dich als der neue Benutzer an
* Klicke auf das Scheren-Symbol des Videos mit Lesezugriff
* Schneide das Video, Speichere oder Starte einen Workflow

**Ergebnis**: Speichern erfolgreich, bzw. Workflow startet.

Erwartetes Verhalten
---------------------------------

Instructors können ausschließlich Videos schneiden, auf die sie Schreibrechte haben.

Wann das Verhalten leicht problematisch ist (a user's story)
------------------------------------------------------------------

When the instructor finishes editing/cutting their videos (Editor linked from Stud.IP) they are shown the events table for their convenience. We could probably remove `ROLE_UI_EVENTS_VIEW` from their permissions but we somehow depend on them to find an overview of their uploaded videos for management purposes. The first thing is, a scissors symbol is shown on all events, even those, they do not have write access to. [Okay, a UI glitch that appears with or without them having `ROLE_CAPTURE_AGENT`](https://github.com/opencast/opencast/issues/3122). If they click on the scissors, the editor opens and they can set cutting marks and so on. If they have the `ROLE_CAPTURE_AGENT` role, they can also save the changes and start a workflow.

**Warum es kein Opencast-Problem ist und ggf. in der Plugin-Doku behoben werden sollte**
------------------------------------------------------------------------------------------------------------------------------------

> IIRC then ROLE_CAPTURE_AGENT is special and specifically allows users to write to already existing events. This is the role automatically attached to users used by capture agents. They need this special priviledge to ingest to events which another user has created. Otherwise, Opencast would prevent that… which would be weird for capture agents

> In general, it's not a good idea to re-use this role for regular users

> Something like `ROLE_STUDIO` (if you want to fall back to default roles) would probably be better suited

Author: Lars Kiesow

@tgloeggl Für welchen Endpunkt-Zugriff braucht der Instructor die Rolle  `ROLE_CAPTURE_AGENT`?

**Comment by tgloeggl** [comment]
Wir sollten die Rollen dann besser einmal alle auf den Prüfstand stellen, die Liste der Rollen hatte ich vom Opencast-Team mittgeteilt bekommen und übernommen. 
`ROLE_CAPTURE_AGENT` brauchen wir womöglich gar nicht.

**Comment by CGreweling** [comment]
ROLE_CAPTURE_AGENT hatte ich mal hinzugefügt, damit Studip-Nutzer Videos zu OC hochladen können.
Ob das aktuell noch gebraucht wird, müsste man ausprobieren.
Bei ROLE_ADMIN_UI bin ich mir gerade nicht mehr so sicher, man kann das aber in der /security/mh_default.xml recht gut nachlesen.
