### ISSUE TITLE
Courseware Block Layout

### ISSUE THREAD

**Issue by rlucke** [elan-ev/studip-opencast-plugin#545]
Damit Courseware-Medienblöcke von Nutzenden leichter zu erfassen sind, sollten diese Blöcke einen Titel anbieten. Daher wäre es gut wenn der OC-Block optional einen Titel anzeigen könnte. Per Default könnte der Video-Titel gesetzt werden.

Außerdem sollte das iFrame einen border haben, da sonst Vorschaubilder von Videos mit hohen Weißanteilen an den Rändern optisch ihren Bezug auf der Seite verlieren. Der Border sollte `thin solid #d0d7e3` sein.

**Comment by tgloeggl** [comment]
539d65859e6ee3baac0206d3f29d382b9242a35f
