### ISSUE TITLE
Das Plugin lädt nicht alle Episoden

### ISSUE THREAD

**Issue by Davka** [elan-ev/studip-opencast-plugin#552]
Zwar ist das auf Serverseite ein Problem,  aber vielleicht kann man es im Plugin abfangen.

Das im Plugin gesetzte Limit in `SearchClient->getEpisodes(..)` wird nicht beachtet, sodass nur ein Bruchteil der verfügbaren Episoden zurückgeliefert werden. Das Problem tritt mit OC10 und OC11 auf.

**Comment by tgloeggl** [comment]
Dieses Problem sollte mit der neuesten Version erledigt sein, da wird paginiert und dadurch das Episodenlimit eingehalten
