### ISSUE TITLE
Konfigurierbare Liste erlaubter Dateitypen

### ISSUE THREAD

**Issue by Rillke** [elan-ev/studip-opencast-plugin#558]
Nachdem einige Profs herausgefunden haben, dass man in den mp4 Container auch nur-Audio stecken kann und das irgendwie (mit vielem Anstoßen aber dennoch) durch unser Opencast gelaufen ist und dann im Player lustige Fehler verursacht, haben wir uns entschlossen, offiziell auch Audio-Only Inhalte zu akzeptieren - und Opencast erstellt einfach einen Waveform Videostream dazu (dann gibt es im Player auch keine Probleme mehr).

Wäre eine Admin-konfigurierbare Liste von Datei- /MIME-Typen sinnvoll, da ja jede Opencast-Instanz hinsichtlich Workflows anders konfiguriert sein kann?

Hätte jemand Interesse daran, dieses Feature zu entwickeln?

**Comment by tgloeggl** [comment]
#500

**Comment by dennis531** [comment]
Konzept:
- Zuweisung von unterstützten Dateitypen zu jeder Workflow in einer
- Angabe der Dateitypen als Semikolon-getrennte Auflistung von Datei-Endungen in einem Textfeld. Das muss ja nur bedingt nutzerfreundlich sein, da Admin-Einstellungen.
- Aktuell unterstützte Dateitypen als Standard (.mkv, .avi, .mp4, .mpeg, .webm, .mov, .ogv, .ogg, .flv, .f4v, .wmv, .asf, .mpg, .mpeg, .ts, .3gp, .3g2)

**Comment by dennis531** [comment]
UI-Mockup in OC settings:

![Image](https://github.com/elan-ev/studip-opencast-plugin/assets/44410838/6bbddd29-9728-43b2-9779-bfacf1fbb2d7)

Alternatives:
- New seperate dialog/page for workflow configurations

- Select (upload) workflow in dropdown to see and edit settings of this workflow:

![Image](https://github.com/elan-ev/studip-opencast-plugin/assets/44410838/127d087a-9aea-4154-810c-481fee860a89)

**Comment by kai-wng-uos** [comment]
Aktuell ist es im Testsystem soweit ich sehe nicht möglich, Audio-Only hochzuladen. Planen wir das bei uns zu implementieren? Würde ich grundsätzlich für ne gute Idee halten.
