### ISSUE TITLE
Für XML illegale (unsichbare) Zeichen vermeiden

### ISSUE THREAD

**Issue by rrolf** [elan-ev/studip-opencast-plugin#575]
Ohne eine aufschlussreiche Fehlermeldung war es leider nicht möglich einen Serie zu erstellen, da in der Kursbeschreibung ein "vertical tab" (Unicode 0xb) eingebunden war, was aber auch nicht ersichtlich ist. 

Die Schnittstelle sollte keine Zeichen akzeptieren / nutzen die nicht in XML verwendet werden dürfen.

**Comment by rrolf** [comment]
Dokument mit Problematischem Text ist im Matrix Channel.

**Comment by Rillke** [comment]
> Dokument mit Problematischem Text ist im Matrix Channel.

@rrolf gibt es einen Matrix-Channel?

Gibt es einen
