### ISSUE TITLE
Reguläre Events mit Hochladedaten in der Zukunft werden als Live Stream angezeigt und können nicht angesehen werden

### ISSUE THREAD

**Issue by Rillke** [elan-ev/studip-opencast-plugin#579]
![image](https://user-images.githubusercontent.com/2311611/161046857-bfe67a00-0b0c-4581-a297-fcd487c36718.png)

Reguläre Videos mit Hochladedaten in der Zukunft werden als Live Stream angezeigt und können nicht angesehen werden.

Ist das ein Bug, ein Feature (vergl. Premiere Feature von YouTube) oder ein Konfigurations-Issue bei uns?

**Comment by tgloeggl** [comment]
Das ist ein "Feature", in V3 muss das besser gehandhabt werden.
