### ISSUE TITLE
Series im OC-Plugin verknüpfen

### ISSUE THREAD

**Issue by ferishili** [elan-ev/studip-opencast-plugin#583]
When importing/integrating another series into a course:

- [x]  Lecturers should be able to link series from other courses!
- [x] The series selection dialog is not wide enough to show the semester identifiers.
- [x] The feature must include the acl changes to both series and events, in order for users to get access to the videos in both courses.
- [ ] It also needs to have a removing mechanism to delete the acls from opencast when the series connection is deleted!
- [x] Make sure the series integration works for CW as well!
- [x] CW Series dropdown search text does not work!
- [x] CW Series from the current LV is not offered for selection -> (NR) (REASON: there should be at least one visible episode inside the series!)
- [x] CW Copy from another block will endup will error in player!
- [x] Admin should be able to decide whether the new linked series can have Upload feature

**Comment by Superjamp** [comment]
You mean for multiconnected series, right?  
At tubs we are showing the User there connected seminar->series with edit permissions.
The issue with this, that we don't know the perms if the user has delete the old connection.

**Comment by Superjamp** [comment]
wrong button :)

**Comment by ferishili** [comment]
> You mean for multiconnected series, right? At tubs we are showing the User there connected seminar->series with edit permissions. The problem with this is that we don't know the permissions if the user has deleted the old connection.

Not really, lecturers should be able to get a list of their previously created series in a dropdown to select from!

**Comment by ferishili** [comment]
What do you mean?

**Comment by Superjamp** [comment]
Ok, but isn't that what I (locally at tubs) already do? (connected seminar->series with user edit permissions)

**Comment by ferishili** [comment]
My patch would be hotfix and I am not aware of your work at tubs!

**Comment by Superjamp** [comment]
Okay, I definitly dont think that this needs to be a hotfix. 😅  
Just wondering how you are going to implement that, because I'm using the sql query shown.  
With the disadvantage of requiring already connected series.

**Comment by ferishili** [comment]
I will let you know when the PR for this issue is submitted and we can discuss it later on!
