### ISSUE TITLE
Doppelt geplante Episoden, wenn Lehrende den Planungsknopf (schnell hintereinander) mehrfach drücken

### ISSUE THREAD

**Issue by Rillke** [elan-ev/studip-opencast-plugin#587]
Wegen https://github.com/opencast/opencast/issues/3636 und keiner vorgeschalteten Duplikatsverhinderung oder -vermeidung im Stud.IP Opencast Plugin ist das mehrfache Planen von Aufzeichnungen möglich.

![MultipleScheduledEvents](https://user-images.githubusercontent.com/2311611/162432422-271e6e48-149e-45f8-9855-a576f0caa983.png)

**Comment by Rillke** [comment]
Etwas einfaches wie

```js
jQuery('<div>').text('Ihre Anfrage wird bearbeitet. Bitte haben Sie einen kleinen Moment Geduld.').dialog({ closeOnEscape: false, modal: true, title: 'In Arbeit' }).parent().find('.ui-dialog-titlebar').hide();
```

![image](https://user-images.githubusercontent.com/2311611/162440711-e8a4ea72-0b12-4c0f-a245-6f5163ef67db.png)

tut es vielleicht schon, indem es weitere Interaktion unterbindet?

**Comment by Superjamp** [comment]
Zudem, was man aus Nutzersicht angezeit bekommt, könnte man mit dem StudipCacheFactory einen lock setzen.
Sollte dann auch gegen andere Nutzer etwas bringen.

**Comment by Rillke** [comment]
> könnte man mit dem StudipCacheFactory einen lock setzen

Was würdest du als Ablaufzeit/ Expiry vorschlagen?

**Comment by Superjamp** [comment]
Ich hätte den lock am Ende der Funktion, soweit möglich, direkt wieder entfernt.  
Schedule habe ich bei uns entfernt, also auch nie benutzt.  
default <= 5min?
Aber das braucht man in PHP nicht auch noch, es war nur ein Vorschlag bzw. Idee.

**Comment by Rillke** [comment]
Das Problem haben wir immer noch, allerdings nun durch das Feld "Aktion wählen" das ich nicht mit bedacht hatte.
