### ISSUE TITLE
Scheduling mit Opencast 4 funktioniert nicht

### ISSUE THREAD

**Issue by CGreweling** [elan-ev/studip-opencast-plugin#59]
Es gab Änderungen an der Scheduling API.
Beispiele:
3.x:
https://github.com/opencast/helper-scripts/tree/master/schedule-now-3x
4.x:
https://github.com/opencast/helper-scripts/tree/master/schedule-now-4x
Jetzt ist es nötig über /ingest ein mediapackage zu erstellen und diese dann über ingest/schedule zu schedulen

**Comment by tgloeggl** [comment]
https://github.com/elan-ev/studip-opencast-plugin/commit/dd04b93fa288993ae333119d75658a0e76812824

**Comment by tgloeggl** [comment]
Für Version 4 funktioniert das scheduling nun wieder. Es muss jetzt nur noch eine Weiche für Opencast 3.x rein.

**Comment by tgloeggl** [comment]
Die noch vorhandenen Probleme sind in eigene Tickets ausgelagert
