### ISSUE TITLE
Können die Zugriffsrechte (ACL templates) in Opencast jetzt gelöscht werden?

### ISSUE THREAD

**Issue by Rillke** [elan-ev/studip-opencast-plugin#592]
[044_drop_oc_access_control](/migrations/044_drop_oc_access_control.php) wurde mit "Use acl-endpoints directly without the templating mechanism" eingeführt. Kann ich als Opencast Administrator die vom Stud.IP Plugin angelegten und nun übrig gebliebenen ACL Templates gefahrlos löschen?

(Ca. 11'000 davon kommen vom Stud.IP Opencast Plugin. Das Löschen würde ich schon mit einem kleinen JS Schnipsel oder Bash-Script automatisieren.)

<img width="1126" alt="Screenshot 2022-04-10 at 01 04 38" src="https://user-images.githubusercontent.com/2311611/162594430-05fbbca4-d427-4436-a018-207086469070.png">

**Comment by Superjamp** [comment]
Von @tgloeggl hatte ich auch gehört, dass wir da mal was aufräumen können.
Er wollte das bei sich auch einmal entsprechend Löschen.

**Comment by tgloeggl** [comment]
Diese Templates könnenl gefahrlos gelöscht werden.

**Comment by Rillke** [comment]
@tgloeggl Habe die überflüssigen Templates während der Reindexierung von Opencast im Rahmen eines Updates gelöscht.

```sql
DELETE FROM opencast.oc_acl_managed_acl
WHERE `name` LIKE 'course%'
   OR `name` LIKE 'combined%';
```

Achtung: Nicht einfach so im laufenden Betrieb ausführen!

Weiteres in der [OC User Gruppe](https://groups.google.com/a/opencast.org/g/users/c/FZdqFsaVgGA/m/qvgPwWL5AgAJ).
