### ISSUE TITLE
Externe API?

### ISSUE THREAD

**Issue by tareksander** [elan-ev/studip-opencast-plugin#595]
Gibt es eine API, mit der man die Videos der Kurse abrufen kann? Ich entwickle eine [Android App](https://github.com/tareksander/Stud.IP-App) für Stud.IP und würde gerne das Opencast-Plugin unterstützen.

**Comment by Superjamp** [comment]
In der aktuellen Version eher nicht.  
Wir arbeiten derzeit an der nächsten Major-Version des Plugins (etwa zum nächsten Wintersemester), möglicherweise könnten wir es dort einbauen.
Wir wollen in der neuen Version, die wir noch skizzieren, eine Menge Änderungen vornehmen, die auch die Implementierung einer API-Schnittstelle erleichtern werden.

**Comment by tgloeggl** [comment]
Ein kleiner Ausblick auf die API in der neuen Version:

https://raw.githubusercontent.com/elan-ev/studip-opencast-plugin/vuetify/docs/studip_opencast_routes.html

**Comment by tareksander** [comment]
Der Link geht jetzt ins Leere, ich habe die Dokumentation jetzt unter `docs/studip_opencast_routes.html` gefunden, aber die scheint nicht in der aktuellen GitHub Pages Seite verfügbar zu sein. Die `studip_opencast_routes.yml` daneben ist aber auch gut lesbar, es ist also nicht wirklich schlimm, ich wollte nur mal darauf aufmerksam machen, dass die Dokumentation für die API nicht leicht (also als Internetseite) zu finden ist.
