### ISSUE TITLE
Infotext Serie Verknüpfen - Warten auf Video Verarbeitung erscheint zu spät

### ISSUE THREAD

**Issue by asudau** [elan-ev/studip-opencast-plugin#599]
Der Infotext dass eine Serie Verknüpft wurde und man auf die Verarbeitunge von x Videos noch etwas warten muss erscheint leider erst  NACHDEM die Serie fertig verknüpft wurde, also bzw. nachdem man fertig gewartet hat.

**Comment by Superjamp** [comment]
OpenCast arbeitet danach immer noch an den Workflows, um u.a. die Berechtigungen an den Presenter weiterzugeben.  
In der neuen Version wollen wir solche Missverständnisse mit den ACLs komplett beseitigen.

**Comment by tgloeggl** [comment]
Ok, das müsste man dann technisch etwas anders lösen und das tatsächliche Verknüpfen nicht direkt nacht Klick auf "Übernehmen" vornehmen sondern erst nachdem die Hauptseite neu geladen wurde. Ist aber wahrscheinlich eh egal, weil sich in V3 dieses Problem nicht mehr ergibt.

**Comment by tgloeggl** [comment]
Das wird für die aktuelle Plugin Version nicht mehr behoben.
