### ISSUE TITLE
problem with courses using config_id 2 in testsystem

### ISSUE THREAD

**Issue by Jano1** [elan-ev/studip-opencast-plugin#60]
The endpoints could not be loaded in the uos-testsystem from mh-admin (thrown exception seems to indicate a missing services.json file (Jetty 404 error)). This leads to a missing curl handle which leads to errors on most pages.

Can easily be reproduced when creating a non working config  with id 2 and a course which needs the missing endpoints from config 2.

**Comment by tgloeggl** [comment]
https://github.com/elan-ev/studip-opencast-plugin/commit/675ef34bcfbec5c60ba903681492902ce8a200ea

**Comment by tgloeggl** [comment]
https://github.com/elan-ev/studip-opencast-plugin/commit/baece82aa60c5ea1c4b7330677a9987edd09c44f
