### ISSUE TITLE
Systembenachrichtigung „Neue Sequenzen hochgeladen“ konfigurerbar machen

### ISSUE THREAD

**Issue by CGreweling** [elan-ev/studip-opencast-plugin#617]
Es sollte die individuelle Ausschaltung der Systembenachrichtigung „Neue Sequenzen hochgeladen“ an die Teilnehmenden ermöglicht werden. Das wird dann relevant, wenn Sequenzen „auf Vorrat“ aufgenommen werden und zunächst unsichtbar bleiben: Es kommt zu Verwirrung bei Studierenden, die trotz Benachrichtigung nichts vorfinden.

Das ist eine Anforderung von den Studierenden der UOS wurde merhfach gewünscht.

**Comment by tgloeggl** [comment]
Das Problem lässt sich wahrscheinlich auch dadurch lösen, dass nur Benachrichtigungen verschickt werden, wenn auch die Episode selbst sichtbar geschaltet ist (die Standardsichtbarkeit wird dabei berücksichtigt).
