### ISSUE TITLE
Wo kommt Version 2.6 her?

### ISSUE THREAD

**Issue by Rillke** [elan-ev/studip-opencast-plugin#634]
Unser Stud.IP schlägt uns vor `OpenCast: Version 2.6 installieren` aber der Eintrag in der `plugin.manifest` im aktuellen Master-Zweig ist `version=2.5.6`.

Fehlt da eine Code-Veröffentlichung oder kommt die 2.6 aus einem anderen Zweig?

**Comment by tgloeggl** [comment]
Merkwürdig. Ist da bei GitHub irgendwas schiefgegangen? Ich habe es jedenfalls eben grade gezogen, es fehlt lediglich folgendes Commit, welches nur der Versioninfo ändert: 
https://github.com/elan-ev/studip-opencast-plugin/commit/af7902d8582cd05fde8bfb2506aa926d7269bfa7
