### ISSUE TITLE
Suche nach Serien funktioniert nur eingeschränkt

### ISSUE THREAD

**Issue by Rillke** [elan-ev/studip-opencast-plugin#635]
Die neue Seriensuche hat mehrere Probleme:

1. Die Ergebnisliste scheint weder nach Relevanz noch nach Alphabet sortiert zu sein
2. Mit jedem Tastenschlag wird eine Anfrage (XHR) losgeschickt, aber laufende Anfragen werden nicht abgebrochen
3. Sobald man mal im unteren Feld war, hat man etwas ausgewählt und wenn man dann "Enter" im oberen Feld drückt, wird die Verknüpfung mit der ausgewählten Serie gestartet, statt die Suchvorschläge zu aktualisieren

![Screenshot 2022-10-11 at 19 06 49](https://user-images.githubusercontent.com/2311611/195155836-459ef49d-08e8-45c1-981d-05ff1ad945e8.png)

**Comment by Rillke** [comment]
Bitte klar Begriffe aus dem Serientitel bevorzugen. Dass "Improtheater Musik" vielleicht irgendwo eine Tutorienveranstaltung in den Metadaten hat, ist beim Verknüpfen eher nebensächlich.

**Comment by tgloeggl** [comment]
c5c81af2acad341f8b8c2ca0492a80c59b552f9e
