### ISSUE TITLE
Feature-Request: Reiter unsichtbar schalten bevor eine Serie angelegt oder verknüpft wurde

### ISSUE THREAD

**Issue by Rillke** [elan-ev/studip-opencast-plugin#636]
Der Reiter Opencast kann von Lehrenden unsichtbar geschaltet werden.

<img width="156" alt="Screenshot 2022-10-11 at 19 33 36" src="https://user-images.githubusercontent.com/2311611/195160589-2c52cbc8-bedf-4114-a7fa-f94bf42d5b2c.png">

Das geht aber erst, wenn man schon eine Serie angelegt oder verknüpft hat.

Beim Verknüpfen besteht das Problem, dass die Studis zeitweise Zugriff auf die Videos erhalten, obwohl man das ggf. gar nicht möchte. Außerdem dauert das verknüpfen ewig und ich weiß gerade nicht was genau alles passiert, wenn Studis auf den Reiter zugreifen, während der Verknüpfungsprozess läuft.

**Comment by tgloeggl** [comment]
Stud.IP in aktuellen Versionen erlaubt es, die Sichtbarkeit von allen Reiter einzustellen, unabhängig vom Inhalt des Reiters. Damit ist das nun machbar und somit erledigt. :)
