### ISSUE TITLE
Geplante Events sollen gelöscht werden wenn Verknüpfung aufgehoben wird. (SOPV2)

### ISSUE THREAD

**Issue by CGreweling** [elan-ev/studip-opencast-plugin#640]
Siehe Titel.
Problem:
Serie wird angelegt, Aufzeichnungen werden geplant.
Verknüpfung wird aufgehoben und eine neue erstellt oder eine Vorhandene verknüpft.
Die geplanten Aufzeichnungen landen in der 1. Serie, neu Aufzeichnungen können nicht geplant werden.

**Comment by tgloeggl** [comment]
0508390ad8981abab8869557c425e2dc7825ae12
