### ISSUE TITLE
Linksharing

### ISSUE THREAD

**Issue by tgloeggl** [elan-ev/studip-opencast-plugin#643]
To allow users to share links to single videos (events), the following workflow is proposed:
- The shared link is a link to SOP V3 in Stud.IP
- The link contains a uuid of some kind, which is generated by SOP V3 and kept track of in the database
- this uuid is used as user name for the LTI Call, with `share:` in front of it
- When the link is opened, the user will be redirected to the video after an LTI call to OC

In the background, the following will happen:
- LTI call to OC
- OC call too Stud.IP SOP V3 (only if cache is empty or older than x minutes, currently 3)
- SOP V3 returns list of permissions / roles, in this case the only permission for this link, the read perms for the shared event

This process will ensure the following constraints:
- Multiple, revokable link shares for single events / videos without the need to change ACLs in OC
- Due to having only one permission per link, there will be no caching issues and permissions will be granted instantaneous.
- If a permission is revoked, there will be no way for owners of the link to still access the video, because the event in Opencast will never be world visible.

**Comment by ferishili** [comment]
Closed as completed and merged into master via https://github.com/elan-ev/studip-opencast-plugin/pull/656
