### ISSUE TITLE
List of courses to connect to does not find all courses with oc plugin enabled

### ISSUE THREAD

**Issue by tgloeggl** [elan-ev/studip-opencast-plugin#658]
Cause unknown, needs to be checked

**Comment by ferishili** [comment]
According to my assessment, it works as expected:
- Root gets all courses with activated SOP plugin!
- Admins also get all course with activated SOP plugin with in depth search.
- Dozents also get those courses that are enrolled in and have SOP activated.

**Comment by ssrahn** [comment]
Is this still a problem? Seems like @ferishili checked it and it worked!
