### ISSUE TITLE
Embedd Player durch Vorschaubild + Link ersetzen

### ISSUE THREAD

**Issue by CGreweling** [elan-ev/studip-opencast-plugin#66]
Der Embedd-Player wird leider als iritierend wargenommen. Da hier nur ein VideoStream dargestellt werden kann.
Wie vorher, den Embedd Player durch ein Vorschaubild ersetzen mit einem Wiedergabesymbol darauf. Bei klick gelangt man zum "erweiterten Player". Dann kann auch der Button "erweiterter Player" weg.

**Comment by tgloeggl** [comment]
Im gleichen Zuge wird die Zweispaltigkeit aufgegeben und dafür eine einfache Liste, die alle Informationen enthält, verwendet, evtl. mit etwas vergrößertem Vorschaubild

**Comment by tgloeggl** [comment]
Ist erledigt
