### ISSUE TITLE
Icon unter "Meine Veranstaltungen"

### ISSUE THREAD

**Issue by tgloeggl** [elan-ev/studip-opencast-plugin#668]
- [ ] Funktionalität prüfen
- [ ] Anzahl neuer Videos anzeigen (da fehlt vermutlich noch einiges im Backend, um das zu bewerkstelligen)

**Comment by Sturek** [comment]
Scheint zu funktionieren. Allerdings ergibt sich hier das Problem, dass Die Nutzenden nicht wissen können in welcher Playlist die Video neu dazu gekommen sind. Dadurch ist dieser Hinweis nur bedingt nützlich, wenn in einem Kurs viele Playlisten sind ist er gar nicht hilfreich.
