### ISSUE TITLE
Missing Series - Uploads sent no series-id

### ISSUE THREAD

**Issue by tgloeggl** [elan-ev/studip-opencast-plugin#678]
The plugin silently ignores if no series could be created. If no series can be created, this should be captured somehow. Maybe a warning message and disabled upload links to make sure nothing bad happens.

**Comment by kai-wng-uos** [comment]
As far as I understood, series are replaced by playlists in the new Plugin. Does that make this issue irrelevant, or has this to do with the OC side of things?

**Comment by ssrahn** [comment]
The second one: OC still uses series, and in the backend, we need to make sure to create a new series for each course and user. However, this is not always possible, such as in case of a connection failure to the OC Server. With #858 I implemented warning messages and hide upload functionality in such a case.
