### ISSUE TITLE
Migration von V2 nach V3

### ISSUE THREAD

**Issue by tgloeggl** [elan-ev/studip-opencast-plugin#697]
- [x] Konfiguration korrekt übernehmen
- Sicherstellen, das alle Inhalte korrekt übertragen werden
    - [x] Coursewareblöcke
    - [x] Videos und Berechtigungen
    - [x] Geplante Aufzeichnungen
- Vor- und Nachmigrationsskript um Ausfallzeiten zu minimieren
    - [x] Vormigration: Neue, vereinfachte ACLs setzen
    - ~~Nachmigration: Alte ACLs entfernen~~

**Comment by alinastolzenburg** [comment]
Ggf. abhängig von "Switch to OC Playlist"?!
