### ISSUE TITLE
Plugin fails to handle TLS 1.3

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/studip-opencast-plugin#704]
Trying to add an Opencast server using TLS 1.3 for transport encryption, the set-up fails with an unhelpful exception stating that the data filled out in the form is incorrect. But the data was correct. The plugin was just unable to handle TLS 1.3. Allowing older TLS fixes the problem.

But:

- The plugin should support TLS 1.3 (which is already 5 years old by now)
- The plugin should print an actual helpful error message. A generic one would have been better as this misleading one.

![Screenshot from 2023-06-05 11-45-42](https://github.com/elan-ev/studip-opencast-plugin/assets/1008395/e2508e92-aec9-4120-8ab9-471af45a9ce3)

**Comment by tgloeggl** [comment]
This seems to be not directly an issue of the plugin but rathermore the underlying php used for the distro Stud.IP is running on ( cf https://stackoverflow.com/questions/71399877/tls-1-3-via-guzzle-where-libcurl-only-supports-1-2 ).
Nonetheless i will have look into it and if possible come up with a meaningful error message, depending on if this problem can be detected from the plugin side of things.

**Comment by tgloeggl** [comment]
@ferishili I am using the Opencast-API for my calls to Opencast. I think, this is something the has to be handled there (i.e. i am calling `opencastApi->services->getServiceJSON()`).

But i will take a first look into it myself, then we can discuss this furthermore.

**Comment by ferishili** [comment]
Hi @tgloeggl
The latest release of oc-php-lib has the latest changes, make sure you have updated to v1.4

**Comment by tgloeggl** [comment]
Solution for this will be passing the error to the front end user instead of failing silently, the error message will look something like:
`cURL error 35: error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://opencast.me/sysinfo/bundles/version?prefix=opencast`
