### ISSUE TITLE
Explain what the default editor workflow is for

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/studip-opencast-plugin#706]
The plugin asks admins to select a default editor workflow with no explanation what this is used for. Opencast's editor lets select users which workflow to run, and the plugin should not have any influence over this. What effect does this selection have? Does it have any effect at all?

![Screenshot from 2023-06-05 11-56-47](https://github.com/elan-ev/studip-opencast-plugin/assets/1008395/30e575e7-f7cc-4dbf-a786-9e745627b35f)

**Comment by kai-wng-uos** [comment]
![Image](https://github.com/elan-ev/studip-opencast-plugin/assets/152959695/5913ea0e-80b2-4b8f-8205-a8ac9b9049a3)

there is no more editor tab now.
