### ISSUE TITLE
Numeric ID for Opencast server

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/studip-opencast-plugin#708]
In the global plugin settings, the admin is asked about a numeric identifier of the default Opencast server.
This doesn't really make any sense:

![Screenshot from 2023-06-01 23-04-37](https://github.com/elan-ev/studip-opencast-plugin/assets/1008395/a728ccb1-b1f3-4a38-9cdf-c52de483de75)

**Comment by tgloeggl** [comment]
- [ ] Use dropdown of servers to choose from instead
- Make sure the default is server is always set, call the appropriate check in the backend to set it when:
    - [ ] a new server has been added 
    - [ ] a server has been deleted
    - [x] the global config is stored
