### ISSUE TITLE
Workflow für Uploads

### ISSUE THREAD

**Issue by tgloeggl** [elan-ev/studip-opencast-plugin#71]
Im Moment man den Workflow für Uploads pro VA setzen.
* Sicherstellen, dass das nur Root kann
* Es sollte einen Standard geben, der auch durchgereicht wird

**Comment by tgloeggl** [comment]
Man soll den Standardworkflow für Uploads in Stud.IP einstellen können

**Comment by Jano1** [comment]
Soweit eingebaut. Legt jetzt einfach einen neuen Eintrag in der Tabelle 'oc_seminar_workflow_configuration' an mit CourseID 'default_workflow'. Wenn ein Kurs nun keinen eigenen WF hat, wird der Standard genommen. Existiert weder Standard noch eigene Einstellung, lässt sich ein Video nicht hochladen (Wird aber sichtbar gemeldet das nichts konfiguriert ist).
