### ISSUE TITLE
No distinction between successfully added servers and ones with problems

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/studip-opencast-plugin#710]
The user interface does not show any known problems with any servers, so that working server setups are indistinguishable from non-working set-ups except for the incorrect version.

- There should be an error if the set-up is incorrect/unfinished
- The version should be shown correctly or not at all

![Screenshot from 2023-06-05 12-39-03](https://github.com/elan-ev/studip-opencast-plugin/assets/1008395/15beda94-bdbc-44c4-bc0c-0a3d0689e311)

**Comment by kai-wng-uos** [comment]
@lkiesow This is what it looks like atm when I try to add a server with a faulty URL. Is this what you had in mind? 

![Image](https://github.com/elan-ev/studip-opencast-plugin/assets/152959695/5775a5e3-261c-4c4b-91a7-2b777f16c6d1)

**Comment by lkiesow** [comment]
In the example above, there are several already added servers and one of them has problems. In your example, you just have one server anyway and it is clear which one is broken. Assuming there would be multiple servers, the error message above wouldn't really help you to identify which server has a problem and which does not, would it?

**Comment by lkiesow** [comment]
But from the description, that seems to be addressed as part of #829 as well.

**Comment by kai-wng-uos** [comment]
Ah, gotcha, that's true. I don't really know how to recreate the example above though, as I have no experience adding (working) servers etc.

**Comment by dennis531** [comment]
The sever card shows an indicator with the tooltip "Verbindungstest fehlgeschlagen" when "some?" configs are incorrect:

![Image](https://github.com/user-attachments/assets/7b68dce3-b659-454d-afb1-8ac0dc45ac8d)

Still the admin interface is very buggy with very confusing and meaningless error messages. I will test it more and create new issues. Therefore, I move this issue to done.
