### ISSUE TITLE
Wording of server delete configuration

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/studip-opencast-plugin#714]
The confirmation dialog for deleting a server starts with a broken sentence:

- “Sind sie **sicher**, dass …”
- I suggest replacing the events being deleted with the events being removed from  Stud.IP. Being deleted sounds like the files are being deleted
  - Also “rausgelöscht” is very casual.

![Screenshot from 2023-06-05 13-07-36](https://github.com/elan-ev/studip-opencast-plugin/assets/1008395/492b8a60-b5fa-47f1-a1c1-d1abf160bbd5)

**Comment by alinastolzenburg** [comment]
@lkiesow das können wir nicht testen. Könntest du das bitte machen :)

**Comment by kai-wng-uos** [comment]
This is the new dialog, looks fine to me.


![Image](https://github.com/elan-ev/studip-opencast-plugin/assets/152959695/a0112899-cccf-4c7f-9538-09f9fb3b48fc)
