### ISSUE TITLE
Inconsistent wording of upload dialog

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/studip-opencast-plugin#717]
Sometimes the plugins talk about “adding”, sometimes about “uploading”. Sometimes about “events”, sometimes about “media”. The plugin should be consistent when it comes to wording for one and the same action.

![Screenshot from 2023-06-01 11-54-33](https://github.com/elan-ev/studip-opencast-plugin/assets/1008395/33d88608-6cf0-476d-bedc-f5c7bf658291)

**Comment by tgloeggl** [comment]
https://github.com/elan-ev/studip-opencast-plugin/commit/0bd97f936dd3072fe3b83f51c5d59916c9a5e404
