### ISSUE TITLE
Explain why the plugin needs user references

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/studip-opencast-plugin#721]
The documentation tells users to set Opencast to create user references for LTI users. I struggle to see why this should be necessary given that the documentation also tells users to activate the Stud.IP user provider in Opencast which should supply these users?

https://github.com/elan-ev/studip-opencast-plugin/blob/701056cddaede8ce3dd327f68beaaf258564d5cb/INSTALL.md?plain=1#L25

**Comment by tgloeggl** [comment]
With the Stud.IP-UserProvider, this should not be necessary anymore. 
-> [ ] Check, if the cutting editor still works when this is turned off.

**Comment by lkiesow** [comment]
Why? What's the problem?

**Comment by tgloeggl** [comment]
```
2023-06-16T08:09:18,759 | WARN  | (IngestRestService:1251) - Unable to ingest mediapackage
java.lang.SecurityException: Current user 'lti:test-5.3:e99badebf23c226f33014246f3cdda4f' can not be loaded
```

**Comment by lkiesow** [comment]
The error message means that Opencast cannot load any user with that identifier. The same would go for access evaluation. In other words: The Stud.IP user provider does not provide the user. But since that is required for the Plugin to work, you have a problem to fix, I guess.

That is likely also why you said that things only work when LTI users get `ROLE_ADMIN` which would make them global system administrators and allow them to bypass most of the access control checks in Opencast. Something you therefor really shouldn't do.
