### ISSUE TITLE
Explain why the plugin needs admin interface roles for users

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/studip-opencast-plugin#722]
The documentation states to make sure LTI users get a bunch of admin interface related roles in Opencast but fails to explain why this is necessary. Users should never be pushed to Opencast's admin interface via LTI, are they? Why do they need these roles?

https://github.com/elan-ev/studip-opencast-plugin/blob/701056cddaede8ce3dd327f68beaaf258564d5cb/INSTALL.md?plain=1#L27

**Comment by tgloeggl** [comment]
see #721, the ROLE_ADMIN_UI is not needed, if Stud.IP-UserProvider is setup / working correctly
