### ISSUE TITLE
Explain what the group `STUDIP` is for

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/studip-opencast-plugin#724]
The documentation tells you to create a group (text says role, but that is just incorrect) “STUDIP” in Opencast but fails to explain what this group is used for:

https://github.com/elan-ev/studip-opencast-plugin/blob/701056cddaede8ce3dd327f68beaaf258564d5cb/INSTALL.md?plain=1#L64-L66

As an empty group, there are no roles associated with it, and it therefor should have no real effect for granting any privileges.

**Comment by tgloeggl** [comment]
If i understand it correclty, there CAN be assigned permissions to this, which then will be assigned to all users received via the Stud.IP user provider.
Provided i am right in my assumption, shall i add some clarification to the installation instructions?

**Comment by tgloeggl** [comment]
Without that group, ingests won't work!!!
