### ISSUE TITLE
Document the user provider once

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/studip-opencast-plugin#726]
The user provider is documented in two places in the installation guide. [There should be only one](https://youtu.be/ooN9xdAgi5w?t=29):

https://github.com/elan-ev/studip-opencast-plugin/blob/701056cddaede8ce3dd327f68beaaf258564d5cb/INSTALL.md?plain=1#L38

and 

https://github.com/elan-ev/studip-opencast-plugin/blob/701056cddaede8ce3dd327f68beaaf258564d5cb/INSTALL.md?plain=1#L222-L224

**Comment by tgloeggl** [comment]
https://www.youtube.com/watch?v=Fo8gqSKAwVU&t=48s
