### ISSUE TITLE
Stick to one name for Opencast tab

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/studip-opencast-plugin#728]
…call it “Opencast” or call it “Videos”, don't call it both:

<img src="https://github.com/elan-ev/studip-opencast-plugin/assets/1008395/58aea3c9-5335-401a-8a19-92275f3fe2a0" width="300" />

**Comment by lkiesow** [comment]
Do you have a person I can talk to at UoG?

**Comment by tgloeggl** [comment]
Of course, but i have an idea which could work for both of you: What about renaming it to "Opencast Videos"?

**Comment by tgloeggl** [comment]
https://github.com/elan-ev/studip-opencast-plugin/commit/ca1b42a8a42b67de54514936f2d72c2a72d48aed
