### ISSUE TITLE
No message after processing is done

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/studip-opencast-plugin#729]
Uploading some media, the plugin lets me know that I will get a notification after the events have been processed:

![Screenshot from 2023-06-05 17-39-24](https://github.com/elan-ev/studip-opencast-plugin/assets/1008395/142c8250-75c1-4ce4-942d-485de2d76802)

The events I uploaded have been processed, but I did not get a notification:

![Screenshot from 2023-06-05 17-45-45](https://github.com/elan-ev/studip-opencast-plugin/assets/1008395/30598334-cf49-4e67-a51c-645f24a32fab)

**Comment by tgloeggl** [comment]
Ist das immer noch so? Vermutlich lag das nur daran, dass der Cronjob nicht eingeschaltet war.
