### ISSUE TITLE
Cannot find users when trying to share a video

### ISSUE THREAD

**Issue by Sturek** [elan-ev/studip-opencast-plugin#739]
![grafik](https://github.com/elan-ev/studip-opencast-plugin/assets/6900803/a47a478d-51d6-4ff0-9a87-817f625e5d62)

The users list is empty and cannot be searched, search is always empty:

![grafik](https://github.com/elan-ev/studip-opencast-plugin/assets/6900803/41e2d3a0-7a4b-49a4-b62f-2a45de54e99e)

Sometimes names are shown for a very brief moment, when there is nothing in the search bar. Usually when deleting characters from the search bar.

**Comment by ssrahn** [comment]
I cannot reproduce this error, for me it works very smooth. Is it still occurring for you?
