### ISSUE TITLE
Opencast Plugin: Courseware Block is not working/usable

### ISSUE THREAD

**Issue by alinastolzenburg** [elan-ev/studip-opencast-plugin#741]
Several problems:    
- When I want to embed a video I get two different error messages (which are quite hard to find) "This video has no publishing URL link" "The video is not available". Both error messages lie. I cannot embed a video      
- the list with the videos does not look clickable --> something like a checkbox or a highlight of the clicked video is missing in its entirety        
- the search field and the filter field for the order of the videos look extremely broken and do not correspond to the StudIP optics (is an order actually preselected?)
- The list of videos contains irrelevant information from the user's point of view (18819062-9f10-4549-acfb-93a32efaf046 - what?)
- The list of videos has the potential to become infinitely long
- when you submit the search, a lot of "bullets" appear for a short moment --> why?
- Less important: The search is not a live search and "triggering" the search only works via the keyboard. Deleting the search term does not reset the search.

![image](https://github.com/elan-ev/studip-opencast-plugin/assets/116811905/689a3dbd-300d-4cfb-8cdd-fd4b2e6f8e1b)

**Comment by alinastolzenburg** [comment]
![image](https://github.com/elan-ev/studip-opencast-plugin/assets/116811905/5cdd35f9-18e4-4c6a-9828-f14a8dd12918)

Aufgerufen wird https://studip-test.uni-osnabrueck.de/plugins.php/opencast/api/lti/launch_data/ff1f06b21ec21538032f361979399cf3

Viele Grüße von Felix

**Comment by alinastolzenburg** [comment]
Deutlich besser!!! Ich habe hier noch ein paar Probleme:
- the list with the videos does not look clickable --> something like a checkbox or a highlight (das wäre mir am liebsten) of the clicked video is missing in its entirety --> Besteht noch
-  füge ich einen OC Block ein lande ich am Ende der Liste --> Das bringt mich aus dem Kontext ich sollte am anfang des Blocks bleiben
- Nice to have: Live Suche nach z.B. 2 Buchstaben
- Nice to have: Die liste mit den Videos ist sehr lang eine Grid Ansicht würde das verbessern (Vorschaubild - was ja sogar klickbar ist Name und Datum nehmen nicht viel Platz weg)

**Comment by kai-wng-uos** [comment]
- [ ] live search
- [ ] video list clickable
- [ ] grid view
- [ ] jumping to the end of the list

I noticed that drag & drop does not work at all. Is this a test system issue?

**Comment by Sturek** [comment]
It would be best, if the videos don't open in an new tab. The videos are already viewable above and switching to a new tab is just confusing. Ideally, there would also be no play button on the thumbnail in this list.

**Comment by kai-wng-uos** [comment]
New problem: When I add the block and select a video, the preview shows me the video thumbnail. Then, when I press save, the block says "Es wurde bisher kein Video ausgewählt". When I close and reopen the block in the "Bearbeiten" view, the video is there. When I switch to the reader's view, its gone again


https://github.com/elan-ev/studip-opencast-plugin/assets/152959695/a288b817-bbe9-4258-82ab-d3ac5fdb53a1

**Comment by ssrahn** [comment]
@kai-wng-uos 
>     * [x]  live search
> 
>     * [ ]  video list looks clickable (highlight or checkbox)
> 
>     * [ ]  grid view
> 
>     * [x]  jumping to the end of the list
> 
> 
> I noticed that drag & drop does not work at all. Is this a test system issue?

I already implemented highlighting of the selected Video, look here:
https://github.com/elan-ev/studip-opencast-plugin/assets/41595254/48017339-83dc-4897-977a-428f363acd8a

What do you mean by drag and drop? Do you mean dragging and dropping the videos in the list to sort them?

**Comment by ssrahn** [comment]
With PR #898 i fixed the bug you mentioned earlier:
> New problem: When I add the block and select a video, the preview shows me the video thumbnail. Then, when I press save, the block says "Es wurde bisher kein Video ausgewählt". When I close and reopen the block in the "Bearbeiten" view, the video is there. When I switch to the reader's view, its gone again
> Aufzeichnung.2024-01-09.113104.mp4

I also fixed this:
> It would be best, if the videos don't open in an new tab. The videos are already viewable above and switching to a new tab is just confusing. Ideally, there would also be no play button on the thumbnail in this list.

If there are no further suggestions or bugs, the issue can be closed

**Comment by Sturek** [comment]
Then let's close this. 👍
