### ISSUE TITLE
Subtitle file upload leads to unknown error

### ISSUE THREAD

**Issue by vermayer** [elan-ev/studip-opencast-plugin#744]
Uploading a subtitle (in this case a .vtt file) results in an unknown error for both German and English subtitles.

<img width="276" alt="Bildschirmfoto 2023-07-14 um 19 31 20" src="https://github.com/elan-ev/studip-opencast-plugin/assets/64207148/c0170184-1f29-45f2-b79e-83cd6ec83c4a">
<img width="399" alt="Bildschirmfoto 2023-07-14 um 19 30 57" src="https://github.com/elan-ev/studip-opencast-plugin/assets/64207148/6c83f649-ea98-44b1-bfa7-0931355bcae7">

Furthermore, there is no information on which subtitle file formats are supported.

**Comment by alinastolzenburg** [comment]
Getestet: Funktioniert!
