### ISSUE TITLE
Labels are not displayed for titles with 250 characters

### ISSUE THREAD

**Issue by vermayer** [elan-ev/studip-opencast-plugin#745]
Location: Videos in „Work Place"
If you have a video with a 250 character title, there is no space left for labels.

Is the line height causing a problem here?

<img width="1124" alt="Bildschirmfoto 2023-07-14 um 20 10 22" src="https://github.com/elan-ev/studip-opencast-plugin/assets/64207148/9df243f7-374d-42cc-b2fe-85d4c8dd54c2">

<img width="587" alt="Bildschirmfoto 2023-07-14 um 20 10 34" src="https://github.com/elan-ev/studip-opencast-plugin/assets/64207148/250296d9-53de-42be-be8d-8f32c789f9c5">

**Comment by alinastolzenburg** [comment]
Tags sind jetzt sichtbar. Die Titel werden allerdings nach x zeichen abgeschnitten und können auch nicht in einem Tooltipp o.ä. nachgelesen werden. Das ist allerdings verschmerzbar.
