### ISSUE TITLE
Add videos to playlists: Info message does not close

### ISSUE THREAD

**Issue by vermayer** [elan-ev/studip-opencast-plugin#746]
Location: Work Place --> "Videos/Opencast" --> "Wiedergabelisten" --> Wiedergabeliste auswählen --> "Videos hinzufügen".
The info message "Bitte wählen Sie die Videos aus, die zur Wiedergabeliste hinzugefügt werden sollen." cannot be closed via x. The message disappears only after reloading the page.
(For comparison: the green success message can be closed via x).

<img width="547" alt="Bildschirmfoto 2023-07-14 um 20 41 12" src="https://github.com/elan-ev/studip-opencast-plugin/assets/64207148/372b5bc5-c423-4106-acbb-69b795bd4aaf">

The console reports the following errors:
<img width="677" alt="Bildschirmfoto 2023-07-14 um 20 42 53" src="https://github.com/elan-ev/studip-opencast-plugin/assets/64207148/319db757-01f8-409e-9860-aca18e4eb1fd">

**Comment by alinastolzenburg** [comment]
getestet gelöst
