### ISSUE TITLE
Contradictory limitation of number of characters in title of playlists

### ISSUE THREAD

**Issue by vermayer** [elan-ev/studip-opencast-plugin#748]
When giving playlists a title, there is no limitation of characters.

Nevertheless, after saving the title, it is cropped to 255 characters.

<img width="298" alt="Bildschirmfoto 2023-07-15 um 14 20 56" src="https://github.com/elan-ev/studip-opencast-plugin/assets/64207148/f1757ada-6b75-4e0e-8a78-3a8208d1c882">

**Comment by alinastolzenburg** [comment]
Getestet tut :)
