### ISSUE TITLE
OC Plugin: Error messages are not helpful

### ISSUE THREAD

**Issue by alinastolzenburg** [elan-ev/studip-opencast-plugin#756]
"An unknown error has occurred" is not helpful

**Comment by alinastolzenburg** [comment]
Wichtig wäre hier: 
- was hat nicht funktioniert 
- was soll ich tun (support/erneut versuchen)

**Comment by ssrahn** [comment]
Die Fehlermeldung wird nach einer Änderung von @tgloeggl komplett ausgeblendet, was dazu führt, dass manche Aktionen ohne jegliche Meldung fehlschagen.

Die Punkte, die ich gefunden habe, sind einmal die LTI authentication und der Upload von Dateien, die wegen einem CORS Error nicht klappen. Ich habe jetzt Fehlermeldungen für diese Fälle eingebaut:

LTI Fehler:
![image](https://github.com/elan-ev/studip-opencast-plugin/assets/41595254/a280e7bf-fa43-40aa-8b7e-9c3210308081)

Daraus resultierende Upload Fehler:
![image](https://github.com/elan-ev/studip-opencast-plugin/assets/41595254/96a54ae1-0fa1-4d11-a76a-1b5e49faf7f2)

Mit ein bisschen Mehraufwand könnte man die Aktionen auch ausblenden, falls sie wegen diesem Fehler nicht funktionieren,
Falls ich den Text noch anpassen sollte, gerne bescheid geben!

Sind sonst noch mehr Fälle bekannt, wo Fehlermeldungen fehlen/sie nicht hilfreich sind?

**Comment by alinastolzenburg** [comment]
Guten Morgen @ssrahn die Fehlermeldungen finde ich so schon maximal hilfreicher. Bei der ersten Meldung bin ich als Nutzer:in vielleicht noch verwirrt. Es könnte nicht funktionieren? Funktioniert es jetzt oder nicht. Deshalb würde ich vorschlagen den zweiten Satz zu streichen und stattdessen etwas wie: "Bitte versuchen Sie es erneut oder wenden Sie sich an den Support." zu schreiben. Was denkst du? 
Da die Fehlermeldung bislang IMMER "unknown error" war kann ich nicht sagen welche Fehlermeldungen hier ggf. noch hinter stecken ich vermute aber dass die Verarbeitung/ der Schnitt des Videos ähnlich wie das Hochladen fehlschlagen könnte?

**Comment by ssrahn** [comment]
> Bei der ersten Meldung bin ich als Nutzer:in vielleicht noch verwirrt. Es könnte nicht funktionieren? Funktioniert es jetzt oder nicht.

Diese Meldung wird initial beim Aufruf des Plugins angezeigt, wenn bei der LTI-Authentifizierung Verbindungsfehler auftreten (In meinem Fall ein CORS Fehler).
Daraus risultierend funktioniert der Medienupload und das Hochladen von Untertiteln auch nicht - deshalb hab ich den Satz mit eingebracht, dass manche Aktionen nicht funktionieren könnten.
Das **könnte** kommt daher, da alle vorhandenen Server geprüft werden. Wird ein fehlerhafter Server nicht genutzt, würde ein Upload dennoch gelingen.

Da hier nicht direkt eine Aktion ausgeführt wurde, würde ich diese Meldung vorschlagen:
"Es ist ein Verbindungsfehler zum Opencast Server aufgetreten. Bitte wenden Sie sich bei auftretenden Problemen an den Support oder versuchen Sie es zu einem späteren Zeitpunkt erneut."

In meinem Fall funktioniert ansonsten alles. Ich schaue aber mal noch, ob ich irgendwas kaputt bekomme ;)

**Comment by g550** [comment]
Die Fehlermeldungen liegen u.a. auch nicht auf Englisch vor (siehe #847)

**Comment by kai-wng-uos** [comment]
Ich bekomme die meldungen teilweise auf Deutsch und teils auf Englisch.


![Image](https://github.com/elan-ev/studip-opencast-plugin/assets/152959695/82649851-49d6-4821-a3e1-1f9c54d3d024)
