### ISSUE TITLE
Tags for Playlists in "work place" do not seem to serve a function

### ISSUE THREAD

**Issue by Sturek** [elan-ev/studip-opencast-plugin#757]
You can add tags do playlists, but they are simply displayed and the list cannot be filtered using the tags.

**Comment by alinastolzenburg** [comment]
Getestet: nicht gelöst

**Comment by dennis531** [comment]
Wäre hier eine Suche mit Filterfunktion wie bei der Videotabelle sinnvoll?

**Comment by dennis531** [comment]
Dieses Issue sollte mit der Playlistfilterfunktion in #848 gelöst sein.

**Comment by kai-wng-uos** [comment]
filtering for tags still doesn't work. You can click "Schlagwort" and the given tag, but it will just display all videos in the playlist.
