### ISSUE TITLE
Notifications during the creation of a shared link only appear in the background

### ISSUE THREAD

**Issue by Sturek** [elan-ev/studip-opencast-plugin#758]
![grafik](https://github.com/elan-ev/studip-opencast-plugin/assets/6900803/37ff3235-29b5-4847-98cb-042179104e48)

This can be confusing, as users are likely to only notice them after closing the "share" dialog.

**Comment by alinastolzenburg** [comment]
<img width="934" alt="image" src="https://github.com/elan-ev/studip-opencast-plugin/assets/116811905/f6f01cd5-7466-496d-91e9-8c9b9b111397">

Das ist so noch nicht gelöst. 
Als Nutzerin möchte ich die gleiche Fehlermeldung nicht 10 mal sowohl im Hintergrund als auch im Dialog haben. Im Hintergrund sollten sie maximal einmal auftauchen - auch dass sie generell mehrfach (unendlich mehrfach) erzeugt werden können empfinde ich als unüblich. Außerdem ist es verwirrend wenn ich den Dialog wieder öffne und die x Fehlermeldungen noch da sind (das ist am gravierendsten).

**Comment by johafri** [comment]
Wenn ich über das Dialogfenster "Video freigeben" einen Share-Link erstelle, erhalte ich im Dialogfenster die Meldung "Der Link wurde in die Zwischenablage kopiert". Diese Meldung ist auch im Hintergrund zu sehen.

Aber:
Wenn ich das Dialog-Fenster schließe und dann bei einem anderen Video "Video freigeben" wähle, erscheint die Meldung  "Der Link wurde in die Zwischenablage kopiert" diesem Dialogfenster - ohne, dass ein Share-Link existiert.

![Image](https://github.com/elan-ev/studip-opencast-plugin/assets/151526180/b90af3d2-f3ff-4b08-974e-747978f055aa)

**Comment by tgloeggl** [comment]
Sollte mit #854 erledigt sein.

**Comment by kai-wng-uos** [comment]
Seems to be working fine.
