### ISSUE TITLE
Upload media: Time and email

### ISSUE THREAD

**Issue by alinastolzenburg** [elan-ev/studip-opencast-plugin#759]
The first video was uploaded at 3:04PM. At 3:29PM I got an email that the video was published. However, I was actually not able to see the video and continue working with it until 3:40PM.
I think the time lag between the mail and until the video is actually available could be confusing for impatient users.
Also, the title of the video is not properly in the mail. Instead the following command "{mediaPackage.title}"

![image](https://github.com/elan-ev/studip-opencast-plugin/assets/116811905/d99e87f2-52e2-4632-9183-10bc651c73c6)

The subject doesn't make clear if the video is public now or needs to be edited first.

![image](https://github.com/elan-ev/studip-opencast-plugin/assets/116811905/b91718e8-18e1-493b-97fe-ed8dcbd99c03)

**Comment by tgloeggl** [comment]
That seems to be a mail from OC directly, nothing Stud.IP can do here

**Comment by kai-wng-uos** [comment]
@lkiesow can we do something about this from the OC side? If not I'll close the issue.

**Comment by dennis531** [comment]
I move this issue to our "Anforderungsmanagment" board.
