### ISSUE TITLE
Hilfe nicht Hilfreich 

### ISSUE THREAD

**Issue by CGreweling** [elan-ev/studip-opencast-plugin#76]
in der Plugin-Helfe (siehe Screenshot) wird „Weiterführende Hilfe“
angeboten (zum Beispiel wollte ich herausfinden wo ich Fehler reporte).
Leider führt der Link zu http://docs.studip.de was absolut nicht
hilfreich ist da das Plugin dort nicht einmal erwähnt wird (0
Suchtreffer nach Opencast). Der Link sollte weg oder es sollte die
Pluginseite verlinkt werden.

Christian:
Die Hilfe sollte meiner Meinung nach an den Virtuos Support verweisen.

**Comment by tgloeggl** [comment]
Habt ihr einen Text, der dort eingefügt werden kann?

**Comment by CGreweling** [comment]
@tgloeggl sowas?:

Bei Fragen oder Fehlern wenden Sie sich bitte an den virtUOS support:
E-Mail: virtuos@uni-osnabrueck.de
Tel. +49 541 969 6666

**Comment by tgloeggl** [comment]
https://github.com/elan-ev/studip-opencast-plugin/commit/9263a2d1c4c2ac999d656c3cfa21c8e759580d12

http://docs.studip.de/help/3.5/de/uos/Opencast/Opencast

Ich habe jetzt einen (sehr kurzen) Hilfetext eingefügt, der nach einem Klick auf "Weiterführende Hilfe" auftaucht. Damit sollte das Problem vorerst behoben sein.
