### ISSUE TITLE
No indication that a video is currently being processed

### ISSUE THREAD

**Issue by g550** [elan-ev/studip-opencast-plugin#760]
In V2 there is a list of videos which are currently being processed. This is missing in V3 such that a user might be confused about whether their upload is being processed or not (ideally, such an indication would also contain an estimate of the remaining time).

**Comment by alinastolzenburg** [comment]
Ich kann eine solche Liste zur Zeit nicht finden würde das Issue also wieder öffnen

**Comment by tgloeggl** [comment]
Es gibt keine separate Liste mehr dafür, stattdessen finden sich die Videos, welche momentan in Bearbeitung sind, in der Liste der Videos im Arbeitsplatz oder in der Kurswiedergabeliste im Kurs. Es kann bis zu 10 Minuten dauern, bis ein neues Video in Bearbeitung dort auftaucht.
Passt das so für euch?

**Comment by alinastolzenburg** [comment]
Ich finde eine separate Liste in der Wiedergabeliste in der ich das Video hinzufügen möchte deutlich sinnvoller. Ich habe die von dir angesprochenen Listen beim Testen leider definitiv nicht finden können. 10 min bis das Video dort auftaucht ist ebenfalls zu lang - in der Zeit erwarte ich bei kurzen Videos ggf. schon die vollständige Verarbeitung gerade wenn ich von Youtube und Co komme.

**Comment by tgloeggl** [comment]
Es gab noch einen Fehler beim Hochladen, der ist nun behoben. Nun klappt es, dass hochgeladene Videos SOFORT auftauchen als "in Bearbeitung" (mit gelbem Zahnradsymbol).

Die separate Liste ließe sich nur schwierig realisieren, dafür müssten wir die UI umgestalten. Werft doch einen Blick drauf, ob ihr mit der aktuellen Lösung jetzt leben könnt.

Bei Studio-Uploads gibt es leider keine Möglichkeit das anders zu realisieren. Durch die Entkopplung von Stud.IP und Opencast, so dass Stud.IP nicht dauernd "hängt" und auf Opencast wartet, dauert es in diesem Fall eben bis zu 10 Minuten, bevor das Video auftaucht, da der Cronjob im Hintergrund das erledigt.

**Comment by johafri** [comment]
Das passt für uns soweit. Nur eine Kleinigkeit: Das Mouse-Over sollte sich nicht nur auf das Zahnrad-Bild, sondern auch über den Titel des Videos erstrecken, damit es auf jeden Fall gefunden wird.
