### ISSUE TITLE
Some actions are only possible in the "work place"

### ISSUE THREAD

**Issue by Sturek** [elan-ev/studip-opencast-plugin#761]
There are some actions that are not possible from within a course. Some of these are still displayed as actions in the course and then open the "work place" in a new tab. This is very confusing.

Examples:

- editing playlists
- adding existing videos to playlists
- adding existing playlists to a course

**Comment by Sturek** [comment]
The last example is actually not possible, right now. It only works by going to the course that the playlist is in and using the transfer function. It is not possible to add a playlist in the work place to a course.

**Comment by alinastolzenburg** [comment]
Als Lehrende möchte ich eine Playlist die ich über und in meinen Kurs geöffnet habe auch in diesem Kurs bearbeiten können (z.B. um ein Video zu entfernen). Derzeit öffnet sich ein neuer Tab in dem ich mich im Arbeitsplatz befinde. Dadurch habe ich einen Kontextwechsel der mich verwirrt. Ich bin unsicher wie ich a) zurück komme und b) weiß ich nicht ob das entfernen des Videos sich nur auf meinen Kurs/Arbeitsplatz auswirkt. In der Mobilansicht wird dieses Problem noch weiter verstärkt weil ich den Kontextwechsel weniger offensichtlich wahrnehme. 
Ich würde mir wünschen dass ich die oben genannten Aktionen in Arbeitsplatz und Veranstaltung durchführen kann.

**Comment by dennis531** [comment]
Ich würde vorschlagen, dass wir die Navigation bei der Bearbeitung einer Kurswiedergabenliste beibehalten. Zudem habe ich ein kleines Mockup in GIMP erstellt, welches meine Idee für die Bearbeitenansicht einer Playlist darstellt:

![opencast-bearbeiten](https://github.com/elan-ev/studip-opencast-plugin/assets/44410838/c2666ff7-94b9-4973-bff9-59620a847a2c)

Folgende Fragen sind bei der Erstellung aufgetreten:
1. Sollen die Aktionen ersetzt oder um die Bearbeiten-Aktionen ergänzt werden?
2. Wäre in der Sidebar eine Auswahl zwischen "auflisten" und "bearbeiten" sinnvoller als ein Button, mit dem hin- und hergewechselt werden kann?
3. An welcher Stelle bzw. in welcher Form sollen die hinzuzufügenden Videos aufgelistet werden?*

Zu 1:
Ich bin eher für "Ergänzen", da alle Aktionen prinzipiell zur Bearbeitung der Wiedergabeliste dienen und das Ausblenden für mich da keinen Sinn ergibt. Allerdings könnten Nutzer:innen die neuen Aktionen wie insbesondere "Videos hinzufügen" schnell übersehen.

Zu 3:
- Das würde ich im Arbeitsplatz lassen, da im Kurs kein Navigationseintrag für Videos vorhanden ist?
- Zusätzlich sollte der Nutzer beim Klick auf hinzufügen, wieder zurück zum Kurs geleitet werden. Zumindest sollte die Videohinzufügenansicht verschwinden.
- Eventuell könnte die Navigation auch unverändert bleiben, also so wie im Mockup, aber mit der Auflistung der Videos.

Das Entfernen der Videos aus einer Playlist sollte nicht allzu schwer umsetzbar sein.

@alinastolzenburg Hast du eventuell weitere Ideen oder Lösungen?

**Comment by alinastolzenburg** [comment]
1. ich wäre auch für ergänzen sonst fehlen die anderen Funktionen schlicht. Ich denke wir sollten aber das "hochladen" weiter oben platzieren da das vermutlich die häufiger genutzte Aktion ist und ich zudem Sorge habe das hinzufügen und hochladen verwechselt werden. Ggf. sollten wir "Video hinzufügen" (was sonst) auch als "zur Playlist hinzufügen" nennen?
2. ich bin nicht sicher ob ich den Punkt richtig verstehe. "Bearbeiten verlassen" verstehe ich als Knopf im Mockup zur Zeit nicht (das gibt es im Arbeitsplatz auf jeden Fall nicht). Vielleicht sollten wir bzgl. diesem Punkt auch einfach nochmal sprechen?
3. ist vielleicht ein Dialog eine Option? Hier könnte man sich am Dateibereich orientieren. Das würde auch Punkt 1 erschlagen. Ich denke an eine "video hinzufügen" aktion. Diese lässt mich dann auswählen ob ich etwas hochladen will oder etwas aus einer anderen Playlist haben will - sodass ich nicht völlig den Kontext wechseln muss?
4. Ist "Verknüpfung aufheben" nicht das gleiche wie löschen?

**Comment by dennis531** [comment]
> 1. ich wäre auch für ergänzen sonst fehlen die anderen Funktionen schlicht. Ich denke wir sollten aber das "hochladen" weiter oben platzieren da das vermutlich die häufiger genutzte Aktion ist und ich zudem Sorge habe das hinzufügen und hochladen verwechselt werden. Ggf. sollten wir "Video hinzufügen" (was sonst) auch als "zur Playlist hinzufügen" nennen?

Die Reihenfolge lässt sich einfach verändern. Die Aktion "hochladen" nach vorne zu stellen, wäre sinnvoll. Bei "Zur Playlist hinzufügen" würde ich mich als Nutzer fragen, welche Videos damit gemeint sind. Ich würde sowas wie "Vorhandene Videos hinzufügen" oder "Videos aus Arbeitsplatz hinzufügen" vorschlagen.

> 2. ich bin nicht sicher ob ich den Punkt richtig verstehe. "Bearbeiten verlassen" verstehe ich als Knopf im Mockup zur Zeit nicht (das gibt es im Arbeitsplatz auf jeden Fall nicht). Vielleicht sollten wir bzgl. diesem Punkt auch einfach nochmal sprechen?

Diesen Button gibt es im Arbeitsplatz nicht, da hier immer die Bearbeitenansicht angezeigt wird, aber mithilfe dieses Buttons könnte der Nutzer wieder zurück zum Kurs gelangen. Eventuell wäre im Arbeitsplatz ein Button oder eine Aktion hilfreich, mir der Nutzer:innen schnell zum Kurs gelangen könnten. 

Zudem könnten wir die Wiedergabenlistenansicht im Kurs ähnlich gestalten. Wir könnten Personen mit Bearbeitungsrechten immer die Bearbeitenaktionen anzeigen und den restlichen Personen diese ausblenden. Damit würden wir uns eine separate Ansicht/Stelle für das Bearbeiten einer Wiedergabeliste sparen. Zudem könnte dann auch die Schaltfläche "Wiedergabeliste bearbeiten" entfernt werden.

> 3. ist vielleicht ein Dialog eine Option? Hier könnte man sich am Dateibereich orientieren. Das würde auch Punkt 1 erschlagen. Ich denke an eine "video hinzufügen" aktion. Diese lässt mich dann auswählen ob ich etwas hochladen will oder etwas aus einer anderen Playlist haben will - sodass ich nicht völlig den Kontext wechseln muss?

Die Idee hatte ich ebenfalls und finde sie gut, aber ich würde nicht unbedingt alle Aktionen in ein Dialog zusammenfassen, da die Inhalte der Aktionen stark unterschiedlich sind und dadurch nicht voneinander getrennt sind. Zudem würde das Dialog zu dynamisch werden, da wir abhängig von der gewählten Option "Hochladen" oder "Video hinzufügen" die Inhalte (Hochladefelder, Videoauflistung) tauschen müssten. Zudem wollen wir keinen Dialog im Dialog haben?

> 4. Ist "Verknüpfung aufheben" nicht das gleiche wie löschen?

Bei Löschen würden die Nutzer:innen eventuell denken, dass das Video vollständig aus dem System entfernt wird. Dafür gibt es die Aktion "Zum Löschen markieren". Ich würde vorschlagen, dass wir es zu "Aus Wiedergabeliste entfernen" umbenennen, um diese Verwechslung zu vermeiden.

**Comment by dennis531** [comment]
Zu 4:
In #820 wird der Button bereits umbenannt zu "Aus Wiedergabeliste entfernen"

**Comment by alinastolzenburg** [comment]
Wir haben uns zusammengesetzt und folgendes beschlossen: 

1. Sollen die Aktionen ersetzt oder um die Bearbeiten-Aktionen ergänzt werden?
- sie werden ergänzt um die Bearbeiten Optionen ergänzt und dabei nach Vorbild des Dateibereichs zusammengefasst --> Video hinzufügen und dann Auswahlmöglichkeit der Quelle (Mein Computer; Arbeitsplatz; Meine Veranstaltungen) 
- Personen mit Leserechten sehen diese "Bearbeiten" Aktionen nicht
- Personen mit Schreibrechten sehen die "Bearbeiten" Aktionen immer

2. Wäre in der Sidebar eine Auswahl zwischen "auflisten" und "bearbeiten" sinnvoller als ein Button, mit dem hin- und hergewechselt werden kann?
- Wir brauchen keinen Knopf mit dem "gewechselt werden kann
- Es gibt die Aktionen Videos hinzufügen und Videos sortieren 

3. An welcher Stelle bzw. in welcher Form sollen die hinzuzufügenden Videos aufgelistet werden?*
- Sie werden im Dialog aufgelistet es gibt die Ansicht ist dabei wie bisher im Arbeitsplatz nur in einem kleineren Dialogfenster, die Suche wird angezeigt und unten im Dialog gibt es Knöpfe mit denen die Videos hinzugefügt werden können oder abgebrochen werden kann (siehe Dialog Dateibereich)

**Comment by tgloeggl** [comment]
Klingt soweit gut, bin gespannt auf die Umsetzung!

**Comment by dennis531** [comment]
> .. Auswahlmöglichkeit der Quelle (Mein Computer; Arbeitsplatz; Meine Veranstaltungen)

Die Auswahlmöglichkeit für Veranstaltungen wäre überflüssig, da Nutzer Videos nach Veranstatlungen filtern können. Was meint ihr dazu?

**Comment by alinastolzenburg** [comment]
@dennis531 entschuldige die späte Antwort: Du hast absolut recht die Auswahl nach der Veranstaltung ist "doppelt". Allerdings dadurch (leider) nicht überflüssig. Unsere Nutzer:innen verstehen das Konzept des Arbeitsplatz nicht zwingend. Was auch daran liegt dass z.B. bei den Dateien nicht alle Dateien im Arbeitsplatz sind. D.h. es wäre sehr hilfreich Lehrenden die den Arbeitsplatz "ignorieren" auch die Veranstaltungslogik beim hinzufügen anzubieten! Außerdem ist die Filtermöglichkeit nach den Veranstaltungen zur zeit nicht wirklich gut sichtbar.
Der Dialog zum Video hinzufügen ist ansonsten sehr sehr gut und übersichtlich! Mit einer Zusätzlichen möglichkeit "aus Veranstaltung" wäre er in meinen Augen perfekt.

**Comment by dennis531** [comment]
> Eine weitere Sache die mir aufgefallen ist: Wenn ich auf "Wiedergabeliste bearbeiten" klicke kann ich in der Veranstaltung nur Schlagwörter hinzufügen - die ich in der Veranstaltung selbst gar nicht sehe. Der Arbeitsplatz bietet andere Möglichkeiten zu bearbeiten (titel der Playlist, Schlagwörter, sortierung) ich finde die ansicht wirklich nicht gut die funktionen hingegen wichtig. @dennis531 fällt dir dazu vielleicht etwas ein?

Im Kurs kann auch der Titel der Playlist verändert werden, solange es nicht die "Kurswiedergabeliste" ist. Die Entscheidung hatte ich bewusst so getroffen, da diese Playlist intern einen anderen Namen besitzt. Der Name ist in diesem Fall der Kursname. Eventuell wäre es sinnvoll, wenn diese Playlisten intern und nach außen den gleichen Namen verwenden. Dann wäre das Ändern des Namen kein Problem mehr.

Zu den Schlagwörtern:
Wir könnten diese Schlagwörter-Einstellung in Veranstaltungen vollständig ausblenden oder wir zeigen die Schlagwörter an geeigneter Stelle an, z.B. wie im Arbeitsbereicht oben mit Titel und Bearbeitenaktion. Letztlich hängt es vom Anwendungsfall ab, ob Dozierende diese Schlagwörter überhaupt in Kursen benötigen.

**Comment by dennis531** [comment]
Konzept für die Auswahlmöglichkeit "Veranstaltungen":
![image](https://github.com/elan-ev/studip-opencast-plugin/assets/44410838/ce3fa49f-b58c-4b27-9756-40541ebaba7c)

![image](https://github.com/elan-ev/studip-opencast-plugin/assets/44410838/bfc0faa4-a437-4b7f-b13a-2c3fa154df29)

![image](https://github.com/elan-ev/studip-opencast-plugin/assets/44410838/5e611109-6259-49de-9574-d0021f7b0abe)

**Comment by kai-wng-uos** [comment]
funktioniert so wie ich das sehe recht gut, finde die Filtermöglichkeiten auch sinnvoll. MMn müssen wir es nicht in zwei dialoge splitten, oder was denken die anderen?

**Comment by dennis531** [comment]
> funktioniert so wie ich das sehe recht gut, finde die Filtermöglichkeiten auch sinnvoll. MMn müssen wir es nicht in zwei dialoge splitten, oder was denken die anderen?

Diese Splittung ist auch im Dateibereich beim Hinzufügen von Dateien vorhanden. Beim Erstellen des Dialogs hatte ich mich an diesem orientert, damit die UX in Stud.IP einheitlich ist.

**Comment by Sturek** [comment]
Was müssten wir hier noch testen? Ist mir leider nicht ganz klar.
