### ISSUE TITLE
Pop-up notifications only disappear when "x" is clicked

### ISSUE THREAD

**Issue by Sturek** [elan-ev/studip-opencast-plugin#768]
Sometimes this results in two identical notifications, sometimes not (in that case there is no confirmation that something happened).

**Comment by alinastolzenburg** [comment]
Gibt es die  Möglichkeit die Aktivität einer Person zu erfassen (Maus bewegt sich/Tastatur etc.) ab dann könnte man einen Timer starten und die Notification verschwindet nach einer gewissen zeit (siehe  Companion in der CW)

**Comment by dennis531** [comment]
Prinzipiell wäre es möglich, aber den Aufwand wäre es nicht wert. Wenn ich es richtig sehe, hat der Companion in CW nur einen Timer, aber keine Erkennung, ob Aktivitäten vorhanden sind. Zudem hätten wir bei einem Timer das Problem, dass Nutzer die Notification nicht sehen, wenn sie sich nicht im oberen Bereich der Seite befinden.

**Comment by kai-wng-uos** [comment]
bei mir verschwindet die ursprüngliche notification, wenn eigentlich die gleiche nochmal kommen müsste. Bsp.: Ich starte einen Upload und bekomme die Nachricht "Video wurde erfolgreich erstellt". Wenn ich ein weiteres Video uploade, bekomme ich die Nachricht nicht nochmal, stattdessen verschwindet die benachrichtigung.

**Comment by dennis531** [comment]
Ich kann dieses Verhalten sowie in meinem Entwicklungssystem als auch in unserem Testsystem nicht replizieren. Wenn ich ein Video hochlade, wird mir die Nachricht nur einmal Mal angezeigt, wenn die Nachricht bereits vorhanden war. Wenn die gleiche Benachrichtigung nicht vorhanden war, wird die Nachricht neu erstellt. Eventuell war im Testsystem noch ein Fehler vorhanden, der bereits behoben ist.

@kai-wng-uos In welchem Kontext (Kurs oder Arbeitsplatz) hast du das Video hochgeladen? Könntest du testen, ob du dieses Problem noch hast?

**Comment by kai-wng-uos** [comment]
> Ich kann dieses Verhalten sowie in meinem Entwicklungssystem als auch in unserem Testsystem nicht replizieren. Wenn ich ein Video hochlade, wird mir die Nachricht nur einmal Mal angezeigt, wenn die Nachricht bereits vorhanden war. Wenn die gleiche Benachrichtigung nicht vorhanden war, wird die Nachricht neu erstellt. Eventuell war im Testsystem noch ein Fehler vorhanden, der bereits behoben ist.
> 
> [@kai-wng-uos](https://github.com/kai-wng-uos) In welchem Kontext (Kurs oder Arbeitsplatz) hast du das Video hochgeladen? Könntest du testen, ob du dieses Problem noch hast?

Das scheint nicht mehr zu passieren. Die Nachricht wird entweder neu generiert, oder die eine Nachricht bleibt bestehen, falls sie schon vorhanden war. das wiederum finde ich allerdings verwirrend, da ich als Nutzer erwarte, für jedes Video, das ich hochlade, eine Benachrichtigung zu bekommen. stattdessen wird die Nachricht nur einmal angezeigt.

**Comment by dennis531** [comment]
In Stud.IP wird beim Erstellen von Kursen und beim Kopieren von Dateien immer nur eine Erfolgsnachricht angezeigt, d.h. die alte Erfolgsmeldung wird entfernt. Ich würde vorschlagen, dass wir dieses Verhalten beibehalten, um es einheitlich zum restlichen Stud.IP zu haben.
