### ISSUE TITLE
The "+" for linking videos to courses and list of links does not work well as an icon

### ISSUE THREAD

**Issue by Sturek** [elan-ev/studip-opencast-plugin#769]
Probably the icon should be a chain or something like that?

**Comment by tgloeggl** [comment]
![Screenshot 2023-09-04 at 12-47-43 Opencast Videos - Stud IP Entwicklungs- und Anwendungsforum](https://github.com/elan-ev/studip-opencast-plugin/assets/6160/20fcb9de-db2d-4751-81fe-a093e3a426b4)

**Comment by tgloeggl** [comment]
So siehts es nun momentan aus. Ist das damit erledigt?

**Comment by alinastolzenburg** [comment]
Für "verknüpfen" gibt es in StudIP in der Courseware schon ein Icon - wenn es das gleiche tut wäre es konsistent das zu verwenden.
