### ISSUE TITLE
No documentation or description of the way that subtitles need to be provided

### ISSUE THREAD

**Issue by Sturek** [elan-ev/studip-opencast-plugin#773]
A link to the documentation or a brief explanation and sample file would be useful.

**Comment by alinastolzenburg** [comment]
![Image](https://github.com/elan-ev/studip-opencast-plugin/assets/116811905/5469fb65-7484-44e8-852a-0d4632e5cf3d)

Ich würde vorschlagen sich sprachlich am Dateibereich zu orientieren --> Untertitel hinzufügen

**Comment by alinastolzenburg** [comment]
Sonstige Beschreibung ist ok!

**Comment by dennis531** [comment]
> Ich würde vorschlagen sich sprachlich am Dateibereich zu orientieren --> Untertitel hinzufügen

"Untertitel hinzufügen" suggeriert mir, dass für eine Sprache beliebig viele Untertitel angegeben werden können, statt wie korrekterweise nur eine einzelne Datei. Bei "Untertiteldatei auswählen" würde ich dieses Verhalten nicht erwarten.

**Comment by kai-wng-uos** [comment]
Wo finde ich das Dialogfenster für die Untertitel. Während des Uploads wurde mir nichts angezeigt.

**Comment by dennis531** [comment]
> Wo finde ich das Dialogfenster für die Untertitel. Während des Uploads wurde mir nichts angezeigt.

![image](https://github.com/elan-ev/studip-opencast-plugin/assets/44410838/df800a94-3425-49d3-bc86-0668c142e598)

Die Aktion wird dir nur dann angezeigt, wenn du Schreibrechte auf das Video besitzt.

**Comment by kai-wng-uos** [comment]
Ah, ich bin blind... Danke!
Würde @dennis531 zustimmen, dass "Untertiteldatei" etwas eindeutiger ist. Und im ersten Schritt heißt der Menüpunkt ja "Untertitel hinzufügen", glaube das geht in Ordnung.

**Comment by kai-wng-uos** [comment]
![Image](https://github.com/elan-ev/studip-opencast-plugin/assets/152959695/5c3c3e28-02d1-4d5c-932b-3bfad3b9cba4)

I think the checkmark icon on the "Datei hinzufügen" button is a little confusing. Especially as the checkmark also appears on the upload button.

**Comment by kai-wng-uos** [comment]
Maybe use the icon from the initial drop down instead?


![Image](https://github.com/elan-ev/studip-opencast-plugin/assets/152959695/67ebc142-0539-4470-bd16-a88408ce9979)

**Comment by dennis531** [comment]
Ich würde das "accessibility" dafür nicht so gerne verwenden.

Vorschläge:

- upload ![Image](https://github.com/elan-ev/studip-opencast-plugin/assets/44410838/b3934804-6c48-4ef0-9c8d-1626bc2874d4)
- file-text ![Image](https://github.com/elan-ev/studip-opencast-plugin/assets/44410838/0a9dcd68-b0b5-40b8-9dac-5d615b8bd39c)
- chat ![Image](https://github.com/elan-ev/studip-opencast-plugin/assets/44410838/5ab45afb-e32f-43dc-a9ba-4fa13d360541)

Ich präferiere `upload`, da sich beim Anklicken der Schaltfläche ein Hochladefenster öffnet.

Eine schöne Übersicht über die Icons befindet sich unter https://develop.studip.de/studip/plugins.php/iconoverview/index.

**Comment by kai-wng-uos** [comment]
> Ich würde das "accessibility" Icon dafür nicht so gerne verwenden.
> 
> Vorschläge:
> 
>     * upload ![Image](https://private-user-images.githubusercontent.com/44410838/297095001-b3934804-6c48-4ef0-9c8d-1626bc2874d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0ODE5NzQsIm5iZiI6MTcwNTQ4MTY3NCwicGF0aCI6Ii80NDQxMDgzOC8yOTcwOTUwMDEtYjM5MzQ4MDQtNmM0OC00ZWYwLTljOGQtMTYyNmJjMjg3NGQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDA4NTQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhNGNhZjA3ODFiOGJiZTJlOTdiYWVkZWZjYWRhMWY0MjI3YzRhZGE5NjE2MmYxNzcxYzAyYjQ4MDNhNTA1YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6spY2FHQUr2L9b_PXOGV8CIqMuchFomfqtwQ8wl0A4k)
> 
>     * file-text ![Image](https://private-user-images.githubusercontent.com/44410838/297096035-0a9dcd68-b0b5-40b8-9dac-5d615b8bd39c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0ODE5NzQsIm5iZiI6MTcwNTQ4MTY3NCwicGF0aCI6Ii80NDQxMDgzOC8yOTcwOTYwMzUtMGE5ZGNkNjgtYjBiNS00MGI4LTlkYWMtNWQ2MTViOGJkMzljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDA4NTQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwZWQyZDAzYWRmYTRlYmQxMzIxOWJmNGQ0ZDhkYmViNTUzYWQxNTYzOTUzYTIzN2Y2ZWE1YTAzNjQxYWJlYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jK8xHgC2n8Sv2ENn7WWLYduRc52MxinpO1nioKdpdcQ)
> 
>     * chat ![Image](https://private-user-images.githubusercontent.com/44410838/297096533-5ab45afb-e32f-43dc-a9ba-4fa13d360541.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0ODE5NzQsIm5iZiI6MTcwNTQ4MTY3NCwicGF0aCI6Ii80NDQxMDgzOC8yOTcwOTY1MzMtNWFiNDVhZmItZTMyZi00M2RjLWE5YmEtNGZhMTNkMzYwNTQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDA4NTQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5MzY0MmQyNDE3ZDYwNzQzZjk3ZjYyNzU5ZTczNTY0Y2E2MWJlMzdmMTVkYThhYWIxNzY2ZmQ3OThlODQxNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uxnnY_JhkXrC4G1k7YRTJxvT-B6gBo9ilsNeZCks-3k)
> 
> 
> Ich präferiere `upload`, da sich beim Anklicken der Schaltfläche ein Hochladefenster öffnet.
> 
> Eine schöne Übersicht über die Icons befindet sich unter https://develop.studip.de/studip/plugins.php/iconoverview/index.

Either upload or file-text will work fine imo.

**Comment by dennis531** [comment]
I see that studip buttons only support a small subset of icons: 'accept', 'cancel', 'edit', 'move-up', 'move-down', 'add', 'download', 'search', 'trash', 'remove'

Would the 'add' icon ![image](https://github.com/elan-ev/studip-opencast-plugin/assets/44410838/21f99bd5-2a62-4962-94dd-bb8b9904b682) be a suitable solution? Or we keep the accept button?
