### ISSUE TITLE
Create a continuously updating test system

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/studip-opencast-plugin#777]
For users, it is hard to test the current state of the plugin. It would be great to be able to always have a public system for the community to run tests.

Best case, we have a test deployment for every pull request like we have with Opencast Editor, Opencast Studio or Tobira. For example, the editor has a [live deployment](https://editor.opencast.org) and a [deployment of every pull request](https://test.editor.opencast.org) with [notifications posted at the pull request](https://github.com/opencast/opencast-editor/pull/1079#issuecomment-1695319739).

As an alternative or additional, we could do a daily resetting test system of the latest state of the branch `master` like we have with [develop.opencast.org](https://develop.opencast.org) in Opencast. That leaves users to always easily test at least the  merged patches.

### Initial Test System

Osnabrück University can provide resources for this (compute, storage).

The setup should be designed to easily replace infrastructure (Ansible, Container, …) so we won't run into problems if we have to replace a machine in the future.

We can expand this later, but for the initial test system:

- We need a Stud.IP installation
  - This should be a recent Stud.IP. Latest release? Git? Not sure what makes the most sense, but we shouldn't need to manually update this.
  - There should be a basic course structure inserted into the fresh install
  - There should be several videos inserted into the installation
  - We need to include Coursware resources
  - We need a set of test users with different roles. Would be nice to document them on the login page like [on the Opencast test servers](https://develop.opencast.org/login.html).
  - We need to connect to an Opencast
- We need an Opencast installation
  - We can probably use [the deployment scripts for the test servers](https://github.com/opencast/opencast-project-infrastructure/tree/master/ansible-demo-machines)
  - We need LTI configured
  - We need the Stud.IP user provider configured
  - We probably cannot incorporate this into Opencast's community test servers, can we?
  - We should track the latest state of Opencast's branch `develop`.

### Extension: Add Room/Capture Agent

> Let's ignore this for now, but keep this in mind for the future

It would be great to test scheduled recordings as well. For that, we should hook up a capture agent to Opencast and pretend that it is recording a specific room.

The work would be to:

- Set up a test capture agent using [pyCA](https://github.com/opencast/pyCA).
- Register capture agent/room with Stud.IP
- Automatically schedule a recording for a short time after the test system has been reset

### Extension: Connect BigBlueButton

> Let's ignore this for now, but keep this in mind for the future

It would also be great to check if the Meetings Plugin/BigBlueButton integration works. For this, we need to connect a BigBlueButton server and configure it to publish media to Opencast:

- Set up a BigBlueButton server
- Configure BigBlueButton Opencast integration
- Install and configure Meetings plugin

---

Does this make sense? Any other suggestions?

**Comment by alinastolzenburg** [comment]
@ssrahn @dennis531 das Testsystem (https://lms-demo-studip.vm2.elan.codes/index.php?again=yes) verfügt gerade nicht mehr über das OC Plugin kann jemand von euch da etwas machen ich glaube Till ist im Urlaub?

**Comment by ssrahn** [comment]
Da scheint es ein Problem bei der Installation gegeben zu haben:
![image](https://github.com/elan-ev/studip-opencast-plugin/assets/41595254/3fb6739b-dc66-45dc-9e81-5b629fedc620)

Allerdings habe ich keine Zugriffsrechte auf die Datenbank und kann es deshalb auch nicht beheben.

**Comment by alinastolzenburg** [comment]
> Da scheint es ein Problem bei der Installation gegeben zu haben: ![image](https://user-images.githubusercontent.com/41595254/277321810-3fb6739b-dc66-45dc-9e81-5b629fedc620.png)
> 
> Allerdings habe ich keine Zugriffsrechte auf die Datenbank und kann es deshalb auch nicht beheben.

ok danke fürs nachschauen. Weißt du wer Zugriffsrechte hat (außer Till)

**Comment by g550** [comment]
Leider funktioniert der Video-Upload im Testsystem immer noch nicht. Ich kann Videos zwar ohne Fehlermeldung hochladen und sehe dann die in #760 erwähnte unmittelbare Anzeige als "in Bearbeitung"; aber nach einer Weile verschwinden die gelben Zahnräder und das Video wird als "nicht verfügbar" angezeigt (Stand: 1h20m nach Upload eines 3-sekündigen Testvideos). @alinastolzenburg bekommt indes direkt beim Versuch des Hochladens eine Fehlermeldung.
