### ISSUE TITLE
Download link should initiate download

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/studip-opencast-plugin#782]
If you click on a media download, you want the browser to initiate a download and not open the video in a new tab. But that's what happens right now. Fixing that should be as easy as adding a [download attribute](https://gomakethings.com/how-to-force-a-file-to-download-instead-of-open-in-the-browser-using-only-html/) to the link like this:

```html
<a download href="…">…</a>
```

![Screenshot from 2023-08-31 14-44-56](https://github.com/elan-ev/studip-opencast-plugin/assets/1008395/05da95d8-7c43-494b-b4be-757597da2013)

We confirmed this problem in version 2.7.2. Not sure about 3.x

**Comment by Sturek** [comment]
For 3.x, I cannot find this feature at all. Does the media download dialog currently exist in v3?

**Comment by dennis531** [comment]
You can open the dialog via the following action:

![Image](https://github.com/elan-ev/studip-opencast-plugin/assets/44410838/e9efa0c1-3368-45bf-8e83-b3a22cccb3f1)

If you use the fast workflow, no download buttons are visible in the dialog. If I understand it correctly, the individual video files are not published in this workflow.

**Comment by kai-wng-uos** [comment]
The media download option is unavailable.


![Image](https://github.com/elan-ev/studip-opencast-plugin/assets/152959695/6d6694c4-2532-43cb-bbb7-bdc20e95ab7e)

**Comment by kai-wng-uos** [comment]
Works fine now. For the videos that are always in the test playlist, the diealog shows no option to download, but I assume this is a test system thing @dennis531 ?
![grafik](https://github.com/elan-ev/studip-opencast-plugin/assets/152959695/8038bbae-d26c-4130-80a4-1721a5144bc3)

**Comment by dennis531** [comment]
I had the same problem. It is caused by the "Fast Testing Workflow" as it doesn't publish the video files. The "Process and schedule on upload" workflow should work fine.

**Comment by dennis531** [comment]
It should be resolved. Please reopen this issue if it is not.
