### ISSUE TITLE
Switch to Opencast playlists

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/studip-opencast-plugin#784]
Opencast will get playlists. Instead of implementing a separate solution, Stud.IP should use the playlists from Opencast which will also be usable in Tobira and other LMS. ELAN is contracted to create the concept. Will be linked here once it is done.

**Comment by dennis531** [comment]
Opencast Playlist Concept: https://hedgedoc.uni-osnabrueck.de/s/ioAY5NC-q#
