### ISSUE TITLE
Übersicht in Wiedergabeliste und Liste selbst zeigt unterschiedliche Anzahl an Videos

### ISSUE THREAD

**Issue by alinastolzenburg** [elan-ev/studip-opencast-plugin#789]
Wenn ich ein Video einer Wiedergabeliste mehrfach hinzufüge passiert das: 

![Image](https://github.com/elan-ev/studip-opencast-plugin/assets/116811905/9416c5b9-f789-4d7e-a816-92bef88c3c45)

![Image](https://github.com/elan-ev/studip-opencast-plugin/assets/116811905/3eb2adae-0751-4780-a8be-fa29bd25d276)

**Comment by tgloeggl** [comment]
- [ ] Videos bereits auf der Wiedergabeliste werden ausgegraut beim hinzufügen
- [ ] Es wird auch tecnhnisch nicht erneute hinzugefügt (sonst passt die Zählung nicht mehr)

**Comment by tgloeggl** [comment]
Es fehlt noch das ausgrauen der Videos

**Comment by tgloeggl** [comment]
Ausgrauen lassen wir weg - Was nützt einem eine lange Liste an ausgegrauten Videos.
- [ ] Filtern der Playlistvideos im Backend
