### ISSUE TITLE
Linking videos dialog (Verknüpfungen): selected playlists should be saved immediately

### ISSUE THREAD

**Issue by Sturek** [elan-ev/studip-opencast-plugin#790]
Having to click "save" after already adding the playlists to the list is not obvious and an unnecessary second step.

**Comment by alinastolzenburg** [comment]
Das ist noch immer wie beschrieben. Wünschenswert wäre es wenn ich den kurs auswähle und diesen einfach "anklicke" und nicht mehr zusätzlich auf "kurs hinzufügen" klicken muss. Dann müsste man nurnoch unten mit "übertragen" bestätigen

**Comment by kai-wng-uos** [comment]
It is now enough just to click on the playlist to add or the delete icon to remove a video from a playlist.
