### ISSUE TITLE
Video linking workflow is inconsistent

### ISSUE THREAD

**Issue by Sturek** [elan-ev/studip-opencast-plugin#794]
Linking videos to playlists via the three-dots menu dialog is inconsistent. I can only select playlists in the current course (or the work place, if I try to link the video from there), but not other courses (or outside the work place, which would be particularly useful). However, I see all links to other playlists, no matter where they are and I can also delete them.

Ideally, this would work similarly to the workflow for "Fragebögen". Thus, I would be able to select a course and a playlist from that course and the list of links also shows which course a playlist is in.

**Comment by Sturek** [comment]
#792 Further adds to the inconsistency and to the confusion.

**Comment by alinastolzenburg** [comment]
Ich teste das wenn 797 gelöst ist

**Comment by Sturek** [comment]
It is now possible to add a video to a playlist in a course from the work place. However, the drop-down only lists the playlist names. This is not useful, as only the first playlist that is created when the plug-in is activated in a course, is named after the course (and sometimes it is only named "Kurswiedergabeliste"?). 

![Image](https://github.com/elan-ev/studip-opencast-plugin/assets/6900803/2a7327d1-76df-4c00-a71e-f720783a506b)

It is impossible to distinguish playlists with the same name, but in different courses. It should be indicated where the playlist is located.

Adding a video to a playlist in another course is not possible from within a course. This is still inconsistent. The dialog looks the same as it does in the work place and playlists that are already linked still appear at the top, even if they are in a different course (again, with no indication where they are located).

**Comment by dennis531** [comment]
TODOs:
- [ ] Add tooltip indicator with information about the linked courses to list of linked playlists
- [ ] Add two dropdows to select the playlist to be linked: 
  1. location: my work place (first option), my courses names
  2. playlist (of course or my work place)

**Comment by Sturek** [comment]
Also related to #792

**Comment by dennis531** [comment]
In #893 the tooltip idea is replaced by `Veranstaltung` and `Semester` columns.
