### ISSUE TITLE
Die Aktion "Verknüpfung aufheben" ist dauerhaft sichtbar

### ISSUE THREAD

**Issue by alinastolzenburg** [elan-ev/studip-opencast-plugin#795]
Das ist inkonsistent in allen anderen Bereichen des Arbeitsplatz sind die Aktionen entweder links oder im Aktionsmenü.  
Die Aktion sollte "Aus Wiedergabeliste entfernen" heißen. Es ergibt keinen Sinn dass die Aktion dauerhaft sichtbar ist. Ggf. noch "wollen Sie wirklich..."

![Image](https://github.com/elan-ev/studip-opencast-plugin/assets/116811905/f307583a-8ba5-4f08-9010-0255987e6019)

**Comment by alinastolzenburg** [comment]
bsp. Dateibereich

**Comment by tgloeggl** [comment]
- [ ] Bulk-Aktionen nach unten
- [ ] Drei Punkte Menü mit allen Bulk-Aktionen als Einzelaktion
- [ ] Videos in Tabelle packen (siehe #753

**Comment by dennis531** [comment]
Wollen wir die tabellarische Auflistung der Videos an allen Stellen haben. Also in der Bearbeitenansicht einer Playlist sowie in der Videoauflistung im Arbeitsbereich.

**Comment by alinastolzenburg** [comment]
Ich denke es wäre sinnvoll es konsistent zu machen.

**Comment by alinastolzenburg** [comment]
Die Ansicht hier sieht super aus!! Wenn ich ein Video allerdings nun aus einer Playlist entferne ist es allerdings überall weg es taucht nicht einmal unter "gelöschte Videos" auf. Das ist sicherlich nicht das erwartete verhalten. Hierfür mache ich ein neues issue auf :)
