### ISSUE TITLE
There is no way to add a specific playlist to a course

### ISSUE THREAD

**Issue by Sturek** [elan-ev/studip-opencast-plugin#797]
Example user story: I teach several coursese in Biology. Each course has a different topic, but all courses require lab work by the students. My videos that give an introduction to basic safety in the lab and explain how to use certain tools and machines are all in one playlist. This playlist should be available in all courses, but all other playlists and videos are different. Thus, I would like to prepare the lab work playlist in my work place and add it to all relevant courses from there (or from the respective course). This way, the playlist also stays up-to-date in all courses, as I make changes in the work place.

Currently, it is only possible to copy *all* videos and playlists from one course to another. No other way to transfer playlists exists. This is too limiting. It would be great, if the playlists worked like the videos do and the work place is just a library of all playlists and these can be added to courses.

**Comment by Sturek** [comment]
Related to #792 and #794 .

**Comment by alinastolzenburg** [comment]
<img width="944" alt="image" src="https://github.com/elan-ev/studip-opencast-plugin/assets/116811905/74a05339-8691-40b6-ab76-0de5b876bcae">

Als dozentin sieht es so aus. Hier fehlt das Dreipunktmenü was es als Root gibt.

**Comment by dennis531** [comment]
Wie wäre ein Dialogfenster, wie beim Hinzufügen von Videos:
![image](https://github.com/elan-ev/studip-opencast-plugin/assets/44410838/7f576621-ff4b-4e41-a2e2-06018bc03ef9)
Das Fenster würde sich beim Klick auf "Wiedergabeliste hinzufügen" öffnen. Wir müssten dann noch sehen, welche Icons wir für die Aktionen verwenden möchten.

**Comment by dennis531** [comment]
Ich frage mich gerade noch, ob wir diese Unterteilung überhaupt benötigen, da wir einfache Konfigurationen haben. Somit könnten wir die Aktionen auf ein Dialog zusammenfassen. Folgende Einstellungen könnten wir anbieten:

- Playlist (Dropdown):
    - Optionen: "Neue Playlist"; "Kurs-Playlist-1"; "Kurs-Playlist-2", ...
    - Die Optionen listen alle vorhandenen Playlisten des Users auf + die Möglichkeit eine neue Playlist zu erstellen (default)
-  Titel (Textfeld)
    - Bedingung: "Neue Playlist" ausgewählt

**Comment by alinastolzenburg** [comment]
Also ich finde die Dialoglösung aus dem Mockup oben sehr schön (ähnelt auch CW und Dateibereich sehr gut). Das alternative Dropdown wäre auch möglich hier befürchte ich aber eine größere Komplexität. Außerdem bräuchte es dann eine zusätzliche Suche weil manche lehrende wirklich sehr sehr viele Veranstaltungen haben

**Comment by dennis531** [comment]
Ergebnisse der Besprechung:
- Hinzufügen von Playlisten, wie im Mockup dargestellt (analog zu den Videos hinzufügen)
- Vorhandene Playlisten kopieren statt referenzieren, damit sich Änderungen nicht auf bestehende Kurse auswirken
-  Aufbau der Playlistenauswahl
    - Einfache Textsuche nach Veranstaltungs- und Playlistenname
    - Paginierung wäre sinvoll
    - Gruppierung nach Semestern wüschenswert, analog zur Teilnehmendenliste im Kurs (Rollen)

**Comment by dennis531** [comment]
Das Kopieren würde ich erstmal auslassen wollen, da es mir so vorkommt, dass es sich zu stark von den vorhandenen Konzepten unterscheidet.

**Comment by dennis531** [comment]
@tgloeggl Wollen wir generell eine Suche mit Filtern bei Playlisten anbieten? Das würde dann insbesondere die Auflistung der Playlisten im Arbeitsbereich betreffen.

**Comment by tgloeggl** [comment]
> @tgloeggl Wollen wir generell eine Suche mit Filtern bei Playlisten anbieten? Das würde dann insbesondere die Auflistung der Playlisten im Arbeitsbereich betreffen.

Ja, finde ich gut!

**Comment by kai-wng-uos** [comment]
I think the add playlist feature is fine without the playlists being copied. Maybe we could add a window that informs the user when they are about to alter a playlist. Something like "Hinweis: Sie sind dabei, Inhalte einer Wiedergabeliste zu ändern. Diese Änderungen werden sich auf alle Kurse, in denen die Wiedergabeliste verknüpft ist, auswirken." That way we would still make users aware of the connection, without unnecissarily copying playlists.

Grouping by Semester seems like a useful feature to me.

**Comment by kai-wng-uos** [comment]
Also, am I the only one for whom the "Verknüpfte Kurse" button in the menu doesn't work from the workplace?


![Image](https://github.com/elan-ev/studip-opencast-plugin/assets/152959695/faccd6a1-0b52-419b-a376-f1f5ea5ece0a)

It just closes the menu and nothing happens.

**Comment by alinastolzenburg** [comment]
> sich auf alle Kurse, in denen die Wiedergabeliste verknüpft ist, auswirken." That way we would still make users aware

Das sehe ich anders! Aus Lehrendenperspektive bedeutet das dass wenn ich eine Playlist als Grundlage nutzen möchte (z.B. im arbeitsplatz) dass das einfach nicht möglich ist, weil diese immer verknüpft ist. Oder ich habe eine Playlist im semsester vorher die ich als Grundlage verwenden will. Dann wissen die Studis aus dem vorherigen Semester wie ich die Videos verändere? Da ist so schwerwiegend (plus wir können bislang nirgends verknüpfen - das habe wir in der CW mit absicht deaktiviert) dass ein einzelner Dialog zur Info nicht reichen wird. Lars meinte dass wir eine Lösung finden können bei der nur die Metadaten kopiert werden oder sowas - egal wie ich möchte mich sehr gegen das verknüpfen aussprechen.

**Comment by kai-wng-uos** [comment]
@alinastolzenburg ok ergibt Sinn. Würden dann im Arbeitsplatz auch alle Iterationen der "Grundplaylist" angezeigt? Ich könnte mir vorstellen, dass das dann relativ schnell unübersichtlich wird, gerade wenn Lehrende eine Playlist als Grundlage für verschiedene Kurse nutzen. Oder soll im Arbeitsplatz quasi nur die zugrundeliegende Playlist angezeigt werden?

**Comment by kai-wng-uos** [comment]
At the moment, the playlists are still being linked, meaning that if you delete a video from the course version of the playlist, the video is also deleted from the workplace version. I'll reopen this, as the consensus was that we want a different way to copy/transfer playlists to courses.

**Comment by dennis531** [comment]
Ich schließe dieses Issue, da wir mit #886 ein Issue fürs Kopieren haben. Gerne öffnen, wenn noch offene Punkte vorhanden sind, die ich übersehen habe. Gerne auch separate Issues erstellen, da dieses Isse sehr unübersichtlich geworden ist.
