### ISSUE TITLE
Keine Erfolgsmeldung beim hinzufügen von Videos zu einer Playlist wenn der Workflow im Arbeitsplatz gestartet wird

### ISSUE THREAD

**Issue by alinastolzenburg** [elan-ev/studip-opencast-plugin#798]
Wenn ich eine Playlist aus dem Arbeitsplatz bearbeite bekomme ich diese grüne Meldung nicht. 

![Image](https://github.com/elan-ev/studip-opencast-plugin/assets/116811905/5e290ae4-d539-4782-9d86-87895d4d414b)

**Comment by dennis531** [comment]
> Wenn ich über den Arbeitsplatz ein Video hinzufüge, bekomme ich nun die grüne Meldung "Die Wiedergabelisten-Verknüpfungen des Videos wurden aktualisiert". Diese Meldung ist nicht so leicht verständlich wie "Die Videos wurden der Playlist hinzugefügt".

Das Problem tritt bei mir nicht auf. Mehrere Ursachen wären möglich:
- Alter Stand auf dem Testsystem
- Der Cache im Browser hat noch den alten Stand
- Ich habe es übersehen :)

Im Code gibt es ein paar ungenutzte Artefakte, die die alte Nachricht enthalten. Diese wurden aktualisiert.

**Comment by kai-wng-uos** [comment]
Bei mir ist die Fehlermeldung ebenfalls "Die Videos wurden der Wiedergabeliste hinzugefügt."
