### ISSUE TITLE
Link to "§60 UrhG Zusammenfassung" does not exists anymore

### ISSUE THREAD

**Issue by tgloeggl** [elan-ev/studip-opencast-plugin#799]
In [migrations/047_add_upload_legal_info_conf.php](https://github.com/elan-ev/studip-opencast-plugin/blob/master/migrations/047_add_upload_legal_info_conf.php) is a link that does not exists anymore:
- Which link to use instead?
- Remove link completely?

**Comment by tgloeggl** [comment]
https://github.com/elan-ev/studip-opencast-plugin/commit/37962785daf901600f8a781ea767d32010eac2e5

**Comment by alinastolzenburg** [comment]
@tgloeggl wir wären hier dafür den Link lieber ganz rauszunehmen. Dann wäre die Info a) kürzer und kann b) nicht mehr so schnell veralten. Da es sich um einen § handelt kann man das einfach nachschauen. Im Dateibereich wird es ähnlich gehandhabt
