### ISSUE TITLE
After copying Courseware blocks, the link may point to an old, unsupported player resulting in an error

### ISSUE THREAD

**Issue by Sturek** [elan-ev/studip-opencast-plugin#800]
![grafik](https://github.com/elan-ev/studip-opencast-plugin/assets/6900803/10f8bcd4-d391-44b4-94f1-c9697c85d6a7)

This Courseware page with the Opencast block was copied from another course and only shows this error message, as it links to a player that Opencast no longer provides. The explicit link to they player is written to the block data, it would be better if it was just the video ID and the block would then use the correct player itself.

**Comment by lkiesow** [comment]
In general, it might be a good idea to never explicitly link to an Opencast player since it can change, cease to exist, … in the future.
Opencast provides `/play/<id>` links which always lead to the configured default player.

**Comment by tgloeggl** [comment]
fixed in https://github.com/elan-ev/studip-opencast-plugin/commit/8b9dd8e39cf4f4dd39b5b81da417daa8d14d8478
