### ISSUE TITLE
Nutzerfreundlichkeit der ServerCards im Admin Bereich

### ISSUE THREAD

**Issue by ssrahn** [elan-ev/studip-opencast-plugin#832]
- [x] Duplizierte URLs sollten nicht über die DB angelegt werden können
  - Prüfen, ob dies der Fall ist
- [x] Bei Fehler im Verbindungstest des Servers sollte "LTI" aus der message entfernt werden
  - Zudem sollte der Fehler innerhalb der ServerCard nicht als Error angezeigt werden, da er sonst gelöscht wird
- [x] Für das Ausrufezeichen in der ServerCard bei Verbindungsproblemen sollte ein Tooltip angezeigt werden
  - Tooltip ist buggy, sollte noch geprüft werden
- [x] Server sollten inaktiv geschaltet werden können
  - Statt der Server ID zeige ein Switch an, mit dem ein Server (in)aktiv geschaltet werden kann
  - Nutze dafür die StudIP Checkbox
  - Deaktivierbarkeit führt zu:
    - Nur aktivierte Server werden in default server Eingabe angezeigt
    - Default Server wird bei (de)aktivierung geprüft und ggf neu gesetzt
    - Videos eines deaktivierten Servers werden nicht angezeigt
    - Cronjobs überspringen deaktivierten Server
    - In der simple_config_list werden nur aktive Server angezeigt
    - Bei keinen aktiven Servern wird OC Navigation nicht angezeigt
- [x] Wie in #843 erwähnt, scheint das tooltip buggy zu sein
- [x] Nutze statt der Checkbox das Studip-Checkbox Icon

**Comment by ssrahn** [comment]
@tgloeggl Kannst du den Bug beim tooltip bestätigen? Das ploppt in meinem Testsystem einfach auf, sobald das Tooltip eingehängt wird und verschwindet erst, wenn man mit der Maus drüber hovert (Ist aber nur bei den ServerCards so).. Hier nochmal ein Bild davon:
![image](https://github.com/elan-ev/studip-opencast-plugin/assets/41595254/4ed66a10-70dd-45e4-bea1-3a1a4dbba60d)
Hättest du ne Ahnung, wieso das auftritt?

**Comment by tgloeggl** [comment]
Buggy tooltip habe ich behoben. :)
