### ISSUE TITLE
Messages sollten nicht generell global angezeigt werden

### ISSUE THREAD

**Issue by ssrahn** [elan-ev/studip-opencast-plugin#833]
Fehler die innerhalb eines Dialogs erscheinen, sollten nicht ebenfalls im Hintergrund angezeigt werden. Diese sind nur für den Dialog relevant und könnten die Message Box spammen.
Sinnvoller wäre eine Aufteilung der Message Listen in eine globale und eine Dialog Liste.
Die Liste für Dialoge gilt somit nur für die Messages, die für den Dialog relevant sind und werden beim Schließen des Dialogs gelöscht.

**Comment by tgloeggl** [comment]
ErrorComponent sollte weg, und stattdessen auch den Message-Weg gehen.

**Comment by ssrahn** [comment]
- Removed Error Component
- Errors from Error component are now visible in MessageList.
  - They have a "global" attribute, which makes them visible in every MessageList
