### ISSUE TITLE
Nach Datum sortieren

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/studip-opencast-plugin#85]
Standardsortierung sollete nach Datum sein. Es scheint aber danach sortiert zu werden, wann die Aufzeichnung fertig verarbeitet wurde (?)

**Comment by lkiesow** [comment]
Korrektur: Keine Ahnung wonach sortiert wird. Nicht nach Verarbeitungsfertigstellung.

**Comment by lkiesow** [comment]
Nach dem zurücksetzen der Sortierung scheint es nun absteigend nach Datum sortiert zu sein.

Aber wie sortiere ich manuell? Drag'n'drop funktioniert nicht.

**Comment by tgloeggl** [comment]
Siehe #54 - Das individuelle Sortieren wird ausgebaut. Das löst genau dieses Problem hier.
