### ISSUE TITLE
"Aus Wiedergabeliste entfernen" löscht Videos ggf. dauerhaft

### ISSUE THREAD

**Issue by alinastolzenburg** [elan-ev/studip-opencast-plugin#850]
Wenn ich ein Video aus einer Wiedergabeliste entferne und es nur in dieser ist, ist es anschließend komplett weg. Das erwarte ich nicht - außerdem gibt es keine Warnung die mich darauf hinweist. Beim Löschen gibt es die Möglichkeit Videos wiederherzustellen an dieser Stelle nicht.
Ich erwarte als Nutzerin dass das Video wenn ich es nur aus der Playlist entferne noch im Arbeitsplatz unter "Videos" zu finden ist.

**Comment by dennis531** [comment]
Konntest du die Videos zuvor im Arbeitsbereich sehen?

Wenn du nämlich keine Lese-, Schreib- oder Besitzerrechte auf das gelöschte Video besitzt, kannst du es im Arbeitsbereich im Nachhinein nicht auffinden. Bei Root und Admins sieht die Rechtevergabe anders aus, aber davon bin ich nicht ausgegangen.

**Comment by alinastolzenburg** [comment]
Ich habe es gerade nochmal versucht zu reproduzieren um sicher zu gehen. Also das besagte Video habe ich zuvor sowohl im arbeitsplatz als auch meiner Veranstaltung gefunden. Nun kann ich das o.g. Problem allerdings gar nicht mehr reproduzieren das Video bleibt wie erwartet im Arbeitsplatz bestehen. Wenn es dir genauso geht können wir hier gerne wieder schließen.

**Comment by dennis531** [comment]
Das Problem konnte ich gestern nicht reproduzieren, daher auch meine Frage. Auch die Löschenfunktion scheint korrekt zu funktionieren. Ich schließe dieses Issue einfach mal.
