### ISSUE TITLE
Aufzeichnungen werden wärend der Verarbeitung fehlerhaft dargestellt

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/studip-opencast-plugin#86]
Wenn man wärend der Verarbeitung auf das Event klickt bekommt man einen Player mit fehlern und unsinnige Metadatenfelder. Es sollte entwender nichts passieren oder man sollte angezeigt bekommen, dass das Ereignis noch verarbeitet wird:

![screenshot from 2018-04-17 20-45-35](https://user-images.githubusercontent.com/1008395/38890250-26e92af4-4281-11e8-9b15-f32bc470d7d0.png)

**Comment by tgloeggl** [comment]
Ist behoben, player-dev wurd gemerged
