### ISSUE TITLE
Creating a playlist results in an InvalidArgumentException

### ISSUE THREAD

**Issue by Sturek** [elan-ev/studip-opencast-plugin#864]
When creating a playlist in a course, this happens:

![Image](https://github.com/elan-ev/studip-opencast-plugin/assets/6900803/0cf107cc-2403-499b-91f2-663065bcf46d)

The playlist is still created.

**Comment by kai-wng-uos** [comment]
The playlists I've created earleir are now gone. When I try creating a new one, I get the same error.

**Comment by Sturek** [comment]
The error does not occur most times now, but sometimes it does and the playlist is then also **not** created.

**Comment by kai-wng-uos** [comment]
> The error does not occur most times now, but sometimes it does and the playlist is then also **not** created.

I still get the error everytime I create a new playlist. At least they were all actually created...
Also, the order of playlists in the menu is randomized everytime you **add or delete** a playlist. Very confusing.

**Comment by kai-wng-uos** [comment]
I found that the error only occurs when creating playlists from a course, not from the workplace.

**Comment by kai-wng-uos** [comment]
Just tried it in studip-test and it gives me a different error: 


![Image](https://github.com/elan-ev/studip-opencast-plugin/assets/152959695/49a31405-3964-496c-babf-8e165f1b31cc)

**Comment by dennis531** [comment]
This problem should only occur if opencast is deactivated in the course. Perhaps it has been deactivated by another person?

**Comment by dennis531** [comment]
This bug should be solved in #922. The ghost playlist is another problem as the user can not completely delete playlists from the system due to the lack of the "Arbeitsplatz".

**Comment by kai-wng-uos** [comment]
> This bug should be solved in [#922](https://github.com/elan-ev/studip-opencast-plugin/pull/922). The ghost playlist is another problem as the user can not completely delete playlists from the system due to the lack of the "Arbeitsplatz".

works fine now. One minor thing: when klicking add playlist, the dialog window opens, but I can't type a title right away. I have to manually click the title box. Thats a little annoying, can u change that without too much effort?
