### ISSUE TITLE
Workplace: Playlist action "Verknüpfte Kurse"  doesn't open

### ISSUE THREAD

**Issue by dennis531** [elan-ev/studip-opencast-plugin#866]
Also, am I the only one for whom the "Verknüpfte Kurse" button in the menu doesn't work from the workplace?

![Image](https://github.com/elan-ev/studip-opencast-plugin/assets/152959695/faccd6a1-0b52-419b-a376-f1f5ea5ece0a)

It just closes the menu and nothing happens.

_Originally posted by @kai-wng-uos in https://github.com/elan-ev/studip-opencast-plugin/issues/797#issuecomment-1863117565_

**Comment by kai-wng-uos** [comment]
fixed
