### ISSUE TITLE
Drop down menu missing on mobile devices

### ISSUE THREAD

**Issue by kai-wng-uos** [elan-ev/studip-opencast-plugin#868]
On my mobile device (iPhone SE 2022), the drop down menu is completely missing for the OC tab. All options available on the left side of the screen on Desktop are thus unavailable.

**Comment by kai-wng-uos** [comment]
![Image](https://github.com/elan-ev/studip-opencast-plugin/assets/152959695/364a72d4-4c5a-4b4b-a75c-770c9cd9f438)

**Comment by kai-wng-uos** [comment]
Better, but playlist management options are still not visible.



![Image](https://github.com/elan-ev/studip-opencast-plugin/assets/152959695/fd55b5e4-a793-41e2-8bdb-328150536ad3)

**Comment by ferishili** [comment]
> Better, but playlist management options are still not visible.
> 
> ![Image](https://private-user-images.githubusercontent.com/152959695/301116924-fd55b5e4-a793-41e2-8bdb-328150536ad3.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2OTUyMTksIm5iZiI6MTcwNjY5NDkxOSwicGF0aCI6Ii8xNTI5NTk2OTUvMzAxMTE2OTI0LWZkNTViNWU0LWE3OTMtNDFlMi04YmRiLTMyODE1MDUzNmFkMy5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMzFUMDk1NTE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTI4MTcwYjNlYjI2OTk1YmRhNGZhZjk3N2M2MjJlMTQ4MDFjMWRiMmJhMzI5YWI3YWVmZjEwNTFlNjRkYjFiZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2ZdamBWWXnLRJ1ukhvF5fzLMintiHPRTFiMJP4bv4Dc)

They are there, but in sidebar, this image is the navigation!

![Screenshot 2024-01-31 at 10 57 07](https://github.com/elan-ev/studip-opencast-plugin/assets/53179227/c9670bcf-7acc-4f49-b3dc-ee2c40de8b38)

**Comment by kai-wng-uos** [comment]
Ah, you're right, sorry! :)
