### ISSUE TITLE
Nicht sinnvolle Fortschrittsanzeige

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/studip-opencast-plugin#87]
Nach dem Hochladen eines Videos wird eine Fortschrittsanzeige angezeigt. Leider ändert sich wärend der Verarbeitung die Anzahl der Gesamtschritte. Daher springt der Fortschritt zwischenzeitlich auch zurück. Das ist keine sinnvolle Fortschrittsanzeige.

**Comment by lkiesow** [comment]
> Das ist richtig, gibt aber den von Opencast kommunizierten Zustand an.

Nur, dass Opencast diesen Zustand nirgendwo als Gesamtzustand kommuniziert, das Plugin aber schon.

Das Plugin schaut sich den Workflow an und zählt die operationen. Das hat leider nur bedingt etwas mit dem Fortschritt zu tun da jederzeit weitere Operationen und Workflows inkludiert werden können. Kurz: Das Plugin hat keine sinnvollen Daten zur Darstellung als Fortschrittsanzeige und es kann besser ein generisches „In Verarbeitung“ darstellen als einen nicht korrekten Fortschritt.

**Comment by CGreweling** [comment]
Sehe ich auch so wie Jano, ohne Anzahl schritte wäre gut!
Die schritte Anzahl stammt noch von Opencast 1.6. Da hatte diese sich während der Verabeitung auch nicht geändert.

**Comment by tgloeggl** [comment]
Es wird jetzt schlicht kein Fortschritt mehr angezeigt, sondern nur das Opencast-Logo und der Hinweis, dass sich das Video in Bearbeitung befindet. Als title-tag für das Logo ist noch die Anzahl der momentanen Schritte sowie der von Opencast gelieferte Name des aktuell durchgeführten Workflows.
