### ISSUE TITLE
Not all available playlists are visible in the linking dialog drop-down

### ISSUE THREAD

**Issue by Sturek** [elan-ev/studip-opencast-plugin#875]
There should be more playlists available here. Also illustrates #792 

![Image](https://github.com/elan-ev/studip-opencast-plugin/assets/6900803/dbc2d094-60cf-4d11-913d-17abe2dd1367)

![Image](https://github.com/elan-ev/studip-opencast-plugin/assets/6900803/7d9d066a-8f63-402b-b5bd-64203dce7708)

**Comment by kai-wng-uos** [comment]
When I change the default playlist in the "Test Lehrveranstaltung", the playlist disappears from the playlist menu, both when I try to add a plylist to another course and when I try to change the default playlist. As this only happens with the pre-made Kurswiedergabeliste, I assume it coul also be a test system issue?


https://github.com/elan-ev/studip-opencast-plugin/assets/152959695/bf131768-4396-4e59-80b6-2516758bdbb7

**Comment by dennis531** [comment]
This issue should be done. I created a new issue for the latter problem.
