### ISSUE TITLE
Students only see the course playlist, none of the other playlists in a course

### ISSUE THREAD

**Issue by Sturek** [elan-ev/studip-opencast-plugin#877]
Logging in as a student, I can only see the "course playlist" and none of the others.

dozent:

![Image](https://github.com/elan-ev/studip-opencast-plugin/assets/6900803/2e003b03-0508-4fc6-874c-a3f674b194d8)

autor:

![Image](https://github.com/elan-ev/studip-opencast-plugin/assets/6900803/29ce3830-82f3-4100-ba1b-05095e6082cd)

**Comment by dennis531** [comment]
This problem should be solved by #893
