### ISSUE TITLE
"Kurswiedergabeliste" is a confusing name, the same playlist has two names

### ISSUE THREAD

**Issue by Sturek** [elan-ev/studip-opencast-plugin#878]
The "Kurswiedergabeliste" is called that only in that specific course. Outside of that couse, its name is identical to the title of the course. This is confusing, as the same playlist can be called two things. Either the name should be "Kurswiedergabeliste" everywhere, but then #792 is an even bigger problem, or it should be named after the course everywhere, which does not look great and is also not very helpful. When #792 is resolved, I would prefer the first solution.

**Comment by tgloeggl** [comment]
#792

**Comment by dennis531** [comment]
Alternatively, no playlist could be created initially and the user has to create the first playlist manually. In this case, the user would specify the name of the first playlist. This should solve this issue.

**Comment by kai-wng-uos** [comment]
that would match the procedure in V2, where users also have to create a series before being able to add/ schedule videos.

**Comment by ferishili** [comment]
What should happen to already created course playlists?

**Comment by kai-wng-uos** [comment]
> What should happen to already created course playlists?
> 
> I came up with this solution (tooltip):
> 
> ![Image](https://private-user-images.githubusercontent.com/53179227/295533984-0651b9b2-ff57-4d1c-b46e-42fcaa1d8ae4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4OTU0NDQsIm5iZiI6MTcwNDg5NTE0NCwicGF0aCI6Ii81MzE3OTIyNy8yOTU1MzM5ODQtMDY1MWI5YjItZmY1Ny00ZDFjLWI0NmUtNDJmY2FhMWQ4YWU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDEzNTkwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3Njc4OTRmYmQyYjNkMDQzOTY0YjRhODY1NDZjNDI0YjBmODUzODFiYjk3MmE2NzY0MDJiNGUxNGFmZjQ2NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NPj2Zw-k9TnXRiSZ3MZ8cnu5XNBF1lPSxmTBQWlsVFE)
> 
> Would this be helpful?

I like the info icon, but I think the more confusing scenario is opening the playlists in your workplace and having all these playlists named after the courses. i don't think users will neccessarily make the connection to the course playlists even with this info icon. Maybe we need a way of clarifying this in the playlists overview, eg. highlighting course playlists in a different colour or something similar?

**Comment by ferishili** [comment]
My concept, which I am halfway through, is to combine the idea of forcing users to create the default course playlist upon creating a new course (input the title as they like) + maintaining the "Kurswiedergabeliste" with info icon that shows the actual name. Editing the name is also included!

More updates + first test draft will come soon.

**Comment by tgloeggl** [comment]
After some discussion with Farbod we came up with the following changes to our plan:

# Course

## No default playlist present
User has to create a new playlist or link an existing one (which is enforced to be the default)

## Default playlist present
- New entry in action menu "Change default playlist"
  - Dialog opens up with dropdown of all playlists in this course
  - User chooses one and stores it
- Default playlist is denoted by a checkmark in die "Playlists"-part of the sidebar
- No more "shadowing" of playlist name, always show the whole thing
- Playlistnames are shortened to stay in one line in the sidebar (with ...)

**Comment by Sturek** [comment]
And for the migration, the single playlist that will be created from the series in v2 will automatically be the default playlist, I reckon?

**Comment by Sturek** [comment]
I agree. The only issue is Open Cast Studio recordings. For those, they should just appear in the playlist that is active when OC Studio is started.
