### ISSUE TITLE
Fehlgeschlagene Verarbeitung wird nicht richtig dargestellt

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/studip-opencast-plugin#88]
Stud.IP behauptet, dass ein hochgeladenes Video in Verarbeitung ist wenn die Verarbeitung fehlschlägt:

![screenshot from 2018-04-17 20-59-02](https://user-images.githubusercontent.com/1008395/38890851-e1995c24-4282-11e8-8280-e1a54fa89305.png)

**Comment by tgloeggl** [comment]
Ist behoben.
