### ISSUE TITLE
Live search

### ISSUE THREAD

**Issue by kai-wng-uos** [elan-ev/studip-opencast-plugin#880]
There is no live search in the SOP currently. We have live search in the Opencast Courseware block. This is inconsistent, if live search is working in the CW Block, I would expect it to work in the Plugin as well.

**Comment by ssrahn** [comment]
Implemented a global live search with input delay (800ms)

**Comment by kai-wng-uos** [comment]
Thanks! For my money, the delay is a bit long. But it seems consistent with the live search in the CW Block, so I guess we can leave it at that.
