### ISSUE TITLE
Add warnings that other playlists will be affected when a video is marked for deletion or edited

### ISSUE THREAD

**Issue by Sturek** [elan-ev/studip-opencast-plugin#885]
As videos exist only once and are linked to playlists, editing or deleting them may affect playlists on different courses. This may be unexpected for some users and it is easy to misremember which playlists will be affected. Thus, we need a message warning users that other playlists (in other courses) will be affected.

This warning should include:
- wording such as "Wenn Sie dieses Video verändern gelten diese Veränderungen für alle Wiedergabelisten zu denen das Video hinzugefügt wurde. Sollten Sie dies nicht beabsichtigen, laden Sie das Video erneut hoch und bearbeiten Sie diese Kopie."
- Buttons "Trotzdem bearbeiten" and "Abbrechen"
- A list of playlists (and the courses that these playlists exist in) that the video has been added to

This warning should only pop up when other playlists than the currently selected playlist would be affected. In the work place it should only pop up if the video has been added to any playlist.

Actions that should trigger this warning:
- cutting the video in OC Studio
- changing meta data in "Video bearbeiten" dialog, e.g. visibility settings
- Adding subtitles

A similar warning should be triggered when the video is marked for deletion in the work place, if the video has been added to any playlists.

**Comment by dennis531** [comment]
Actions that should trigger this warning:
- cutting the video in OC Studio
- changing meta data in "Video bearbeiten" dialog, e.g. visibility settings
- Adding subtitles
- _restore the video "Wiederherstellen"_

**Comment by kai-wng-uos** [comment]
Instead of adding the warning to "Wiederherstellen", I would add it to "Zum Löschen markieren". Otherwise great!

**Comment by dennis531** [comment]
In https://github.com/elan-ev/studip-opencast-plugin/pull/905#issue-2094079467 the changes are described in detail. The action "Zum Löschen markieren" contains a list of linked playlists at the bottom of the dialog. This list is only visible if the video is at least one playlist. The action "Wiederherstellen" works similar. It displays all playlists into which the video will be inserted after the restore.
