### ISSUE TITLE
Seperate course-wide and playlist specific actions in the actions box in courses

### ISSUE THREAD

**Issue by Sturek** [elan-ev/studip-opencast-plugin#887]
#### Playlist specific (maybe just "Aktionen" or "Wiedergabeliste bearbeiten" (this would require changing "Wiedergabeliste bearbeiten" to something like "Metadaten der Wiedergabeliste bearbeiten")
- Add Video
- Sort Videos
- Edit playlist

#### Course-wide (maybe "Veranstaltungsweite Aktionen")
- Record video (as it will be added to the course playlist, maybe switch to that playlist when this button is clicked?)
- Allow/disallow student uploads
- Copy all videos (wording should be changed to something like "Alle Videos kopieren")

**Comment by ssrahn** [comment]
![image](https://github.com/elan-ev/studip-opencast-plugin/assets/41595254/619bd23c-14e2-4bd9-a77b-53978876a740)

Any further suggestions?

**Comment by kai-wng-uos** [comment]
I find "veranstaltungsweite Aktionen" a bit bumpy. Mybe we can come up with another name for this tab? Otherwise I think its great!
