### ISSUE TITLE
„Daten vom Server entfernen“ funktioniert nicht

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/studip-opencast-plugin#89]
Nach dem aktualisieren der Episodenliste wird ein in der Verarbeitung fehlgeschlagenes Video in der Episodenliste als fehlerhaft markiert. Ein klick auf „Daten vom Server entfernen“ zeigt aber leider keinen Effekt:

![screenshot from 2018-04-17 21-07-08](https://user-images.githubusercontent.com/1008395/38891166-cca888f2-4283-11e8-81c7-6dad803abcf2.png)

**Comment by lkiesow** [comment]
Das Löschen auf Seite Opencast's entfernt nach einem „Episodenliste aktualisieren“ auch den Eintrag aus Stud.IP

**Comment by tgloeggl** [comment]
Diverse Probleme in diesem Zusammenhang und dieses Problem selbst wurden gelöst bei #99
