### ISSUE TITLE
Script-Injection im Stud.IP-Opencast-Plugin 

### ISSUE THREAD

**Issue by noesting** [elan-ev/studip-opencast-plugin#91]
das Stud.IP-Opencast-Plugin rendered beliebigen HTML Code bzpw. in der
Videobeschreibung. Zusammen mit der Tatsache, dass dieser Text frei
angegeben werden kann können Nutzer also beliebigen Code in die Seite
laden.

Ein Beispielscreenshot ist angehangen. Man beachte, dass der erste Teil
der Beschreibung Fett dargestellt wird.

Das ist etwas, was möglichst Umgehend gefixt werden sollte.

![screenshot_from_2018-04-17_21-20-47](https://user-images.githubusercontent.com/4244926/38975954-fdd52584-43af-11e8-8b82-4963503a7a49.png)

**Comment by tgloeggl** [comment]
Das Problem ist mittlerweile gelöst worden während der Umgestaltung der UI
