### ISSUE TITLE
The `Update Metadata` workflow should not be started when preceding workflows failed

### ISSUE THREAD

**Issue by tibroc** [elan-ev/studip-opencast-plugin#915]
Currently the cronjobs seem to trigger `update metadata` workflows even if the initial workflow of the event failed (see https://github.com/elan-ev/studip-opencast-plugin/issues/910). This has a confusing effect in opencast because the event will be shown in the admin UI as "finished" instead of "failed" because the update metadata workflow finished correctly (although the overall event status should still be failed).

**Comment by dennis531** [comment]
I think you mean the `republish-metadata` workflow. The only places where the workflow is triggered are after editing the video in the UI and in the `checkEventACL` function triggered by the "Opencast - Queue" cronjob:
https://github.com/elan-ev/studip-opencast-plugin/blob/e589d297e93d1d0ef1415ecf4bcf8e2595923025/lib/Models/Videos.php#L762

After #916 this workflow should not be triggered by the cronjob anymore when uploading videos. Still, this workflow is executed for recordings in OC Studio, as Studio runs independently of this plugin and does not set the required ACLs. One problem is that the plugin does not know the event ID of the recorded video a priori.
