### ISSUE TITLE
Falsches Vorschaubild und falscher Downloadlink

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/studip-opencast-plugin#92]
Bei einer Slides-Only-Aufzeichnung wird in der Liste der Aufzeichnungen das Vorschaubild der nächsten Aufzeichnung angezeigt. Siehe letzte Aufzeichnung. Sie hat das Vorschaubild der vorletzten Aufzeichnung::

![screenshot from 2018-04-20 12-02-55](https://user-images.githubusercontent.com/1008395/39049585-607c1e98-44a2-11e8-813d-77f6f09383b9.png)

**Comment by tgloeggl** [comment]
Ist durch die neue Darstellung ebenfalls erledigt.

**Comment by lkiesow** [comment]
Das ist nicht richtig. Das Problem besteht immer noch und eigentlich hat das Update es eher verschlimmert, da nun ein kaputter Link auch direkt angezeigt wird:

![screenshot from 2018-05-04 12-11-35](https://user-images.githubusercontent.com/1008395/39625695-e7cd70b6-4f9e-11e8-9333-8bd80db388fd.png)

Das letzte Video hat nur einen Videostream. Es ist nur ein Screencast. Es wird aber dennoch ein Kamera-Vorschaubild angezeigt und ein falsches Video zum Download angeboten.

**Comment by lkiesow** [comment]
Beispiel für einen Fehler im Code ist [OCCourseModel.class.php#L223](https://github.com/elan-ev/studip-opencast-plugin/blob/63775261a80d77003f4e80d11a5a459dabd8d9bd/models/OCCourseModel.class.php#L223) denn `$preview` wird nur gesetzt wenn es ein Attachment vom Typ `presenter/search+preview` gibt. Gibt es keins wird der alte Wert der Variable genommen. In der Schleife ist das dann das Vorschaubild der letzten Episode.

Das Problem besteht in gleicher Weise für andere Daten wie z.B. die Aufzeichnungen.
