### ISSUE TITLE
Gelöschte Aufzeichnungen werden weiterhin dargestellt

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/studip-opencast-plugin#94]
In Opencast gelöschte Aufzeichnungen werden weiterhin in Stud.IP dargestellt wobei der Player mit einem Felhler abbricht und auch schon die Vorschaubilder, … kaputt dargestellt werden:

![screenshot from 2018-04-21 01-09-40](https://user-images.githubusercontent.com/1008395/39077295-338e1d0a-4501-11e8-87e4-f8b665c73d98.png)

**Comment by CGreweling** [comment]
Das wird wohl an der 30min? Aktualisierung liegen. Sollte verschwinden wenn man links auf Epiosdenliste Aktualisieren klickt. Einfach Lösungsidee dafür?

**Comment by lkiesow** [comment]
Erste Idee: Wenn die geladenen Ressourcen (z.B. Vorschaubilder) ein 404
liefern ggf könnte man automatisch einen Rebuild des Stud.IP-Caches
triggern und Außerdem das Event schon temporär nicht mehr anzeigen.

**Comment by tgloeggl** [comment]
Das Problem ist behoben, die gelöschten Episoden verschwinden nun.
