### ISSUE TITLE
Kompatibilität v2 und OC 16 - Anpassung an API-Änderung

### ISSUE THREAD

**Issue by asudau** [elan-ev/studip-opencast-plugin#968]
Für die Kompatibilität von SOP v2 und Opencast 16 sind aufgrund von API-Änderungen noch ein paar Anpassungen nötig.  
  
Beispiel für Anpassungen basierend auf der API-Änderung: https://github.com/lkiesow/opencast/commit/28287cfcf9640de37c81e67fba2e7f622e63e77d

**Comment by tgloeggl** [comment]
Für V2 sind Anpassungen in SOCP notwendig, für V3 in der opencast-php-library ( https://github.com/elan-ev/opencast-php-library/issues/21 )

**Comment by tgloeggl** [comment]
fixed in V2
